### ISSUE TITLE
Complete and test Public Fit Count page

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/PoMS#10]
Complete and test Pulbic Fit Count page inc copying spatial references from previous years.

**Comment by andrewvanbreda** [comment]
AVB note to myself (page complete apart from): 

1. "other" habitat option needs to be dynamic (AVB Fixed: Code was in a node.x.js file)

2. target flower options missing icons

3. "Type of flower counted" is set automatically in original form on iRecord (AVB Fixed: Code was in a node.x.js file)

4. Start Time missing time control (AVB: moved into separate issue so doesn't need to be considered here)

5. Weather controls are missing (AVB: FIXED)

6. copying spatial references from previous years currently missing (this is a new requirement and not available on iRecord).

7. Attribute groups need framesets

8. Need to check saving works (Tested successfully when went live).

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Hi Biren,

Are you able to send me these results from the live Warehouse please. Thanks

select image_path from indicia.cache_termlists_terms where termlist_id = 669;

select image_path from indicia.termlists_terms where termlist_id = 669;

**Comment by BirenRathod** [comment]
@andrewvanbreda 
First query should be like this 
select preferred_image_path from indicia.cache_termlists_terms where termlist_id = 669;

Below are the results.
[FItCount_Image.zip](https://github.com/BiologicalRecordsCentre/PoMS/files/6124444/FItCount_Image.zip)

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Thanks Biren, 

Image_path worked ok on my machine, but don't think it matters, preferred_image_path should be equivalent for purposes of my test.

Um........that result is interesting, as the images are not in the cache_table.
How often do scheduled_tasks run on live?
Are you still getting that same result after scheduled_tasks have run?

Thanks
Andy

**Comment by DavidRoy** [comment]
Note that the work_queue has a lot of jobs at the moment as we doing some big imports...

**Comment by andrewvanbreda** [comment]
@DavidRoy Thanks for the note. @BirenRathod Probably not worth rerunning those now, will revisit this tomorrow.

**Comment by BirenRathod** [comment]
@andrewvanbreda I just checked both have got same results, no need to run scheduled tasks.

**Comment by andrewvanbreda** [comment]
@BirenRathod Thanks Biren. Ok will look into this tomorrow. I noticed actually editing these terms in the Warehouse UI is resulting in an error, so might relate to what we are seeing here.

**Comment by kitenetter** [comment]
@andrewvanbreda I expect this is on your list already, but the attributes for First name, Last name and Email should only appear if the user is not logged in.

In you comment [above](https://github.com/BiologicalRecordsCentre/PoMS/issues/10#issuecomment-789716674), point 6 is not needed for the FIT Count forms, it is a request for the 1 km survey form (where we would ideally like to be able to populate a detailed grid reference based on the user having selected a particular pan-trap station - we can discuss when the focus moves to the 1 km form).

**Comment by kitenetter** [comment]
As far as I can see the only issue left to resolve is the display of icons on the recording form - I think these were for the amount of flower cover? This is a nice-to-have rather than an essential, so is not high priority.

**Comment by andrewvanbreda** [comment]
Raised as a general Indicia issue
https://github.com/Indicia-Team/client_helpers/issues/122

**Comment by andrewvanbreda** [comment]
Not that the requirement for copying spatial references was abandoned after discussion as not possible
