### ISSUE TITLE
Data grid on Map of Fit Counts needs horizontal scroll bar

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/PoMS#102]
For narrow screens, the right hand columns are hidden

![fit](https://user-images.githubusercontent.com/2699478/118936131-2aafa180-b944-11eb-829f-1e408d585dca.png)

**Comment by andrewvanbreda** [comment]
@DavidRoy 
Ok will check with John about fixing this in best way

**Comment by andrewvanbreda** [comment]
@DavidRoy 
Hi David,
I have added some responsive options to the English grid at
https://ukpoms.org.uk/fit-counts-map

Is this better for you? (I don't have smartphone, so am checking on an emulator which shows it is better to me)

If better will apply to other grids.

**Comment by andrewvanbreda** [comment]
@DavidRoy 
Have also changed the welsh of that form. For some reason it doesn't seem to be quite as good at behaving in responsive situation although it is helping. Would be interested to know if that is ok for you?

**Comment by BirenRathod** [comment]
@andrewvanbreda 
On my one it shows in vertical mode as attached screenshot below. So no horizontal scroll bar at the bottom. Although landscape mode is fine.
![PoMS_Screenshot_Mobile](https://user-images.githubusercontent.com/5941255/119140456-164ed000-ba3c-11eb-8afd-c151faa9f723.jpg)

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Thanks Biren.
Yes I wasn't expecting a horizontal scrollbar, but to instead drop less important columns like ID.
Having said that this isn't right, as it looks like it is dropping the columns from the right too (like insect count), there  shouldn't be just 3 columns.
I will have a think as I have no existing scrollbar option to work with.

**Comment by andrewvanbreda** [comment]
@DavidRoy
Note have switched options off on live for now, so no need to check anymore

**Comment by DavidRoy** [comment]
@andrewvanbreda you can test out the page on different screens using developer tools in chrome (cntrol-shift-I then control-shift-m) and choose mobile device/screen size?  The table is still truncated on tablets and phones, making right-hand columns inaccessible

**Comment by andrewvanbreda** [comment]
@DavidRoy
Yes that it what I had been doing. But it did someone thing unexpected, losing the right hand columns wasn't something I was seeing in those tools, it was only supposed to remove the less important ones like ID to make room.
Will investigate

**Comment by andrewvanbreda** [comment]
@DavidRoy @BirenRathod @kitenetter 
Just had another look at this, and switched the test site theme temporarily.
It is the theme that is breaking it, but it is also breaking the Edit icons (which may just be off the right of screen).
So what I will do is have quick play with theme on test site when get chance. Hopefully if I set the style setting on report_grid it will fix this but don't want to be spending long time on this area as it is really outside the scope of my work to fix a custom theme. As say if I can't quickly fix, may need to go back to Steve.

**Comment by DavidRoy** [comment]
Thanks @andrewvanbreda.  I agree that you should not spend long on this.
@kitenetter - can you ask julian and steve about this?

**Comment by andrewvanbreda** [comment]
@DavidRoy 
I think this should be fixed now (not by me I might add, but by the theme design team, and Biren helped to put on site)
Close if you are happy,  otherwise perhaps let Martin know so he can investigate further with theme design team.

**Comment by DavidRoy** [comment]
Thanks!
