### ISSUE TITLE
Image displaying incorrectly

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#103]
On this page:
https://ukpoms.org.uk/research

The chart is displaying in a wide box and displacing the text. I can't see any problems in edit view.

Let me know if I need to delete the image and add it again.

**Comment by BirenRathod** [comment]
@kitenetter  It has resolved now. Also if you add any image without caption , please add class called body_image. you can see example on this -> https://ukpoms.org.uk/fit-counts page. I know bit fiddely but this is how Julian done on whole site using class.

**Comment by kitenetter** [comment]
Thanks @BirenRathod 
Does the class have to be added using the "source" view and adding "class="body_image""?

**Comment by BirenRathod** [comment]
@kitenetter Yes, that is correct. This is only for non caption image. you need to add class to "<"p">" tag.

**Comment by kitenetter** [comment]
@BirenRathod 
I've just added an image to this (unpublished) article:
https://ukpoms.org.uk/node/38

The image is displaying twice - the smaller image is the one that I want to show, but it seems to be including the original image by default.

How can I remove the original image?

**Comment by BirenRathod** [comment]
@kitenetter  That is because , you have used the article content. if it is simple page , use basic page which does what you expected to do.

**Comment by kitenetter** [comment]
Yes, I used the article because I needed to add an article! This is to appear in the "Latest news" feed. We need to be able to add articles!

**Comment by BirenRathod** [comment]
@kitenetter In that case, you don't need to add in the body, just need to upload the image which you did. I have implemented the size now , so it will be display as expected.

**Comment by kitenetter** [comment]
Thanks @BirenRathod that's fine - now published. Closing.
