### ISSUE TITLE
FIT Count Map showing dots as well as 1km squares - should just be blurred to 1km?

### ISSUE THREAD

**Issue by CCarvell** [BiologicalRecordsCentre/PoMS#104]
NOTE I am accessing the new website as a ‘public’ user and NOT logged in, so that I can see what I think most people will see……and same thing happens on my phone as on PC screen.
@andrewvanbreda @kitenetter 
Still two issues to address on the FIT Counts map page:
1.	When you zoom in, you can see the 1km square of each count showing as agreed (I think) BUT you can also see a dot or small square at the exact count location/ address. See screen shot. Also in the table “Spatial ref output” there are some 6-fig grid refs showing which I thought would not show to the ‘public’ but only potentially be visible to logged in users? The same happens for Martin’s place at Little Kimble! 
Is this something to do with my Admin status, even though I am NOT logged in?
2.	At the top of the counts table, there is still one count dated February 2021 – this may be in error – but can that be removed and as Andy suggests, it would be good to order the table of listed counts with most recent first, but not urgent.

![image](https://user-images.githubusercontent.com/44494345/118958238-23df5980-b959-11eb-89e9-e1e4b8286a91.png)

**Comment by CCarvell** [comment]
apologies this overlaps with issue #61

**Comment by kitenetter** [comment]
I'm pretty sure the February count (sample ID 12703302) was added via the old iRecord form, and has come across with the transfer of data. I have deleted it via the warehouse.

The 1 km squares issue is covered in #61 so I will close this one.
