### ISSUE TITLE
Survey drop-down filter not working on Fit Count Map

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/PoMS#109]
Survey drop-down filter not working on Fit Count Map, the grid isn't returning when this is applied

**Comment by kitenetter** [comment]
@andrewvanbreda also, the filter dropdown doesn't include the app records as a third option - I think it should?

**Comment by andrewvanbreda** [comment]
@kitenetter 
It is ok for me. What page are you seeing this? Does it still do this after a browser cache clearance?

**Comment by kitenetter** [comment]
@andrewvanbreda I've just cleared the cache and gone to:
https://ukpoms.org.uk/fit-counts-map

using Chrome and not being logged in. I get the same result as on my normal Firefox log-in - only two of the three surveys are showing in the drop-down list for the survey filter:

![image](https://user-images.githubusercontent.com/16039111/119720055-6c1ee000-be61-11eb-90f4-1c0ef9da7870.png)

**Comment by andrewvanbreda** [comment]
@kitenetter 
How odd. Ok thanks for letting me know.
I have no explanation for that at the moment, my machine is showing it fine.

I have worked out the issue with the Survey drop-down, it is an annoying one (but simple to fix).
There is nothing actually wrong with the report logic, but the problem is I called the drop-down "survey_id" in the code, and that word is reserved for special use.
I should be able to apply a quick fix tomorrow, as just need to change this word in the reports (and give them a test).
I will also change them to show newest first

**Comment by andrewvanbreda** [comment]
@kitenetter 
The drop-down bit of this is fixed, ironically it was caching issue on my machine that stopped me seeing it.
Caused by an old line of code accidentally left in. Report not fixed yet.

**Comment by andrewvanbreda** [comment]
@kitenetter @BirenRathod 
Hi,
I have committed a fix for this problem. I think it is best to put the site into maintenance mode first before putting the fix onto the site.
Martin, I assume it would be ok to have site into maintenance mode for short time?. (Note: these changes also change the report so newest samples are now displayed first).

Biren: after Martin confirms it is ok, could you put site into maintenance mode before pulling the projects/PoMS reports folder. After this, let me know, and I will check and configure the site (in theory simple) before I take it out of maintenance mode.
Probably best to check with me before you do this so you know I am available to check the site after pull.
Cheers

**Comment by kitenetter** [comment]
@andrewvanbreda that should be fine - hopefully it will only be offline for a short time, since this is the first day this year with decent weather for people to do FIT Counts!

**Comment by andrewvanbreda** [comment]
@BirenRathod @kitenetter 
It should only be 10 mins really.

**Comment by BirenRathod** [comment]
@kitenetter  Let me know when you ready.

**Comment by kitenetter** [comment]
@BirenRathod 
Any time is fine for me as long as @andrewvanbreda is ready!

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Yes can do now. So put into maintenance mode, pull the reports, then let me know so I can check. Cheers

**Comment by BirenRathod** [comment]
@andrewvanbreda & @kitenetter anytime from now.

**Comment by andrewvanbreda** [comment]
@BirenRathod Thanks I will check

**Comment by BirenRathod** [comment]
@andrewvanbreda The site is under maintenance mode and I have pulled all reports now.

**Comment by andrewvanbreda** [comment]
@BirenRathod @kitenetter 
This seems to have worked so have taken out of maintenance mode.
Martin can you close if happy.

**Comment by andrewvanbreda** [comment]
Actually, realised I raised this, so I can close it
