### ISSUE TITLE
Setup reports such they work with app data

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/PoMS#11]
App data will go into its own survey, make sure report grids on site can cope with this, in particular that there is a recording form on the site which can be accessed for editing of existing app data.

**Comment by andrewvanbreda** [comment]
AVB note to myself: Elastic Search syntax for multiple surveys is as follows:
(noting displayed inside <> which are not included here as confuses the display of the comment)
input type="hidden" class="es-filter-param" data-es-bool-clause="must" data-es-query-type="terms" data-es-field="metadata.survey.id" value="[636,637,638]"

**Comment by andrewvanbreda** [comment]
AVB Note to myself: Survey 641 is app survey

**Comment by andrewvanbreda** [comment]
Hi @kazlauskis ,

Just trying to setup the website so it will work with app data.
However I have run into a problem.

To show app data on the website, I need to add your survey 641 to the survey filter on the website data grids.
So my data grids will show data from surveys 636,637,638,641 in total

However in the Warehouse survey 641 currently points to a website called Fit Count which is website 134, not 136 which is the Pollinator Scheme website.

Is 134 this "headless" website that has been talked about?
Does that mean the only way around this is to get one of these website sharing agreements setup?, else I can't see the data on my site.
I had previously assumed all the websites were going to have the same website ID, which is something I discussed with Martin/John the other day, although I am not sure what is happening with this headless website.
Thanks for any assistance

**Comment by kazlauskis** [comment]
Yes, site `134` is the "headless" website dedicated to the app user accounts. 

@johnvanbreda @DavidRoy can you advise us on the data sharing options?

**Comment by DavidRoy** [comment]
@kazlauskis we concluded that it is best to have everything under website .id =136.  Is this a major headache for you!

**Comment by kazlauskis** [comment]
@johnvanbreda do you know if using our new JWT authentication the warehouse will accept a record for a survey that belongs to a different website than the website in the token (in the `iss` claim)?

**Comment by johnvanbreda** [comment]
@kazlauskis At the moment, the code will overwrite any website ID with the one in the iss claim. But, if the scope is set to editing, then we could change the code to only do this if the website ID is not provided, otherwise it will accept the one in the occurrence's values as long as the website can be edited (according to the website sharing agreements).

**Comment by kazlauskis** [comment]
Thanks, yeah we could change the warehouse code (and the Drupal scopes) to use the sharing agreements to allow **write** data to other sites.

@DavidRoy given the time we have left, what's the reason that we don't use the sharing agreements to **read** the data from the "headless" website?

**Comment by andrewvanbreda** [comment]
@DavidRoy @kazlauskis 
Hi Karolis,
Had a meeting with David, Claire and Martin this morning.
I will be summarising (in a very short document) the current plan regarding the project structure and this will give you the opportunity to put arguments for any changes. Will try to get this to you by tomorrow.

**Comment by andrewvanbreda** [comment]
@DavidRoy @kazlauskis
Here is that little overview, with a few notes on what to consider. Note this was originally written because my meeting with David/Martin/Claire had indicated there was some conversation regarding the current state of the project structure. I will email it to them too

I am actually quite easy regarding what the solution is, I think actually a lot of it depends on your view of things Karolis
[Current PoMS Project Structure.docx](https://github.com/BiologicalRecordsCentre/PoMS/files/6118773/Current.PoMS.Project.Structure.docx)

**Comment by kazlauskis** [comment]
Thanks, I agree, there are multiple ways around this. 

> 1. Above structure uses just one website ID (apart from the app headless).  The original thinking for this is it would be a bit simpler to setup, and (at the time) we didn’t think there were any disadvantages to this. As mentioned, the exception to this is the app survey points to a different website ID (134). This means some kind of website agreement would need to be setup to share 134 with the PoMS website. Once agreement setup, reports should be able to display the data automatically from website/app.

Having a sharing agreement between the 134 and 136 sites would work well from my perspective. My favourite option.

> 2. Would it be better to use a separate website ID for ALL websites?

Each website having it's own warehouse ID sounds more 'correct' to me though I haven't done sharing agreements so I am not sure what that involves.

>  3. Could the app be changed so that the headless website is also 136 so there is literally one website ID for whole project?

Yes, but the other way round. With the current authentication set up the PoMS site would have to have the URL in the warehouse changed to match the FIT website URL. In such a case, the app would be able to upload and retrieve data as if authorized by the PoMS site. Bending the system this way is hacky but this option is the easiest as it would involve only 1 line change in the config.

**Comment by andrewvanbreda** [comment]
Hi all,

My current thinking is perhaps option 1 might be best (although am happy to be persuaded otherwise).

I think several reasons for this

- It is good for Karolis

- Having to spoken to John the other day, I don't think there are any particular disadvantages to use the one website ID for the websites themselves.

- Also perhaps it is an elegant solution because if the app is being used in several countries and is all going into 134, then perhaps it makes sense if all the websites go into 136. This would give a consistent structure.

There is one thing I can perhaps think of for not doing the above.

Would you ever have the situation where you would want to absoutely prevent another site country's site from seeing the British data?
The data can be separated geographically, but I mean actually prevent it as part of a data contract or something similar. I am assuming this isn't the case as it is all one project.
If that were the case, then perhaps lots of website IDs might be the way to go.

@DavidRoy
Do you have an opinion on the situation, as I think you had some concerns the other day I wasn't clear on.

**Comment by DavidRoy** [comment]
thanks for all the thinking on this. I'm happy to go with option 1 and I'll setup the website agreement

**Comment by andrewvanbreda** [comment]
Note the website now how intelligent edit icons.
So should go to appropriate input form and only appear at correct time. I will test further before closure.

My Records = Always get edit icon, automatically takes user to correct input form
Public Fit Map = Edit icon for your own records only, automatically takes user to correct input form
List samples for administrator = Always get edit icon, automatically takes user to correct input form

This should also work with app data, but this is untested

**Comment by andrewvanbreda** [comment]
Closing this as testing will be completed under issue #41
