### ISSUE TITLE
FIT Count map - attributes missing from grid display?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#110]
On https://ukpoms.org.uk/fit-counts-map the two most recent counts (added via the app) are missing their habitat and target flower. The data for these attributes has been entered and can be seen in the warehouse, but isn't displaying in the grid:

![image](https://user-images.githubusercontent.com/16039111/119816446-9d8cbf80-bee4-11eb-8b09-83b4dda7846f.png)

**Comment by andrewvanbreda** [comment]
@kitenetter 
This problem is being caused because the cache table hasn't been filled in for that sample, so isn't an issue with what the report is trying to do, it  isn't that the data isn't there for it to collect.
I will wait a bit and see if it fills in, if this delay is too great, we might have to switch to slower non-cached version of report (which the welsh version of the page is running anyway).

**Comment by kitenetter** [comment]
Thanks @andrewvanbreda - I think we can live with a delay as long as it isn't hugely long, good to have the page loading quickly.

Closing.

**Comment by andrewvanbreda** [comment]
@kitenetter 
Am just going to re-open this at moment, it is odd they haven't filled in yet. I would expect the delay to be shorted, wonder if the warehouse is busy.

**Comment by andrewvanbreda** [comment]
Checking with John if there is a Warehouse issue today

**Comment by andrewvanbreda** [comment]
@kitenetter 
Am going to switch the report to the slower version as the grid is filling up with empty cells as data coming in.
Can switch back when resolved.

**Comment by andrewvanbreda** [comment]
This is fixed and have switched back the report. 
Just waiting for confirmation of what problem was from John

**Comment by andrewvanbreda** [comment]
@kitenetter 
Received confirmation from JVB that this was because a work_queue/scheduled_task got stuck on the Warehouse because of a technical issue, this meant th cache attributes were not filling in.
Closing as fixed (Note: this issue would have affected other projects also)
