### ISSUE TITLE
Allow users to edit their own counts

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#112]
On the "My results" page https://ukpoms.org.uk/my-results users do not currently have an edit button available. Need to add this.

**Comment by andrewvanbreda** [comment]
@kitenetter 
Ok will try to fix this, the code is actually present that does this, but not sure why they aren't showing at moment, will let you know

**Comment by andrewvanbreda** [comment]
@kitenetter @CCarvell 
This looks like a theme problem, so you will need to contact theme designers.
Switching theme does show the icon. Actually in Safari it doesn't display at all, but in Firefox the icon is there but is tiny (see to the right of the screenshots below). Have also attached a screenshot of the html, it is the action-button that doesn't display
![button-html](https://user-images.githubusercontent.com/2463614/121077797-fa835200-c7cf-11eb-9e40-1d63c0731073.png)
![Button Safari](https://user-images.githubusercontent.com/2463614/121077801-fbb47f00-c7cf-11eb-809c-80f010ab16b3.jpg)
![Button Firefox](https://user-images.githubusercontent.com/2463614/121077805-fce5ac00-c7cf-11eb-8be8-218a3eada4d9.jpg)

**Comment by kitenetter** [comment]
@andrewvanbreda I've just found from previous emails that we did discuss the edit button functionality with Julian back in May, at which point they said:

> I've had a quick look for you this morning and if you just need to be able to scroll horizontally on the table on smaller displays you can just add the following CSS rule to the stylesheet:
> 
> .report-grid-container {overflow-x: auto;}
> 
> I have updated the master stylesheet file and attached it to this email so if Biren (cc'd) wants to update the main CSS in the theme with the attached and clear the cache, that should hopefully fix the issue for you?
> 
> Let me know how you get on.

They also attached file style.css which was copied to you.

Does that resolve this issue or are there additional problems that Julian's information doesn't cover?

**Comment by BirenRathod** [comment]
@kitenetter I have already added that while ago but this could have different class name then report-grid-container one.

**Comment by kitenetter** [comment]
@andrewvanbreda do you need me to pursue anything with Steve/Julian?

**Comment by andrewvanbreda** [comment]
@kitenetter 
Yes please do. If you look at the lower half of the screenshot above, you can see actually the icons do display, but they are far too small (like minuscule). In Safari they are not present at all. So this is not related to horizontal scrollbar as far as I can see.
Also switching themes shows the icons fine.

**Comment by kitenetter** [comment]
Following today's CSS update the edit buttons are visible, but are not yet being filtered to the type of record entered, i.e. for my FIT Count I can currently see a button to edit the FIT Count and a button to edit a 1 km survey.

**Comment by andrewvanbreda** [comment]
@kitenetter Ok, I will take a look. I probably can't fix immediately, I will removed them from the Fit Count Map for now until I can fix. I don't think you would actually be able to see the record, it will moan you are trying to edit a record that isn't yours.

**Comment by andrewvanbreda** [comment]
@kitenetter 
Ok have removed the icons from My Records and Fit Count in both languages for the minute until I fix.

The problem I saw was different to what you were describing. The Fit Count Map had an edit icon next to every record, when it should just be your own. I will look at as soon as I can.
I did test this, so not sure what has happened.

**Comment by andrewvanbreda** [comment]
@kitenetter 
Fixed.
The problem was simple (but annoying given the effort to get the logic right).

The actual code logic wasn't wrong, the problem was that these forms used to have the pan-trap data on them.
This was removed from the report, but the icon was accidently left by me on the page.
So the report no longer controlled that icon, and as such it displayed the entire time.

I have tested this. But check it Monday and close if happy.

The other thing is, I am not sure how you want the welsh forms to display. Currently the edit icon for 1km in Welsh will lead to the English form.
Am not sure how best to deal with that, unless we remove the icon in that situation.

**Comment by kitenetter** [comment]
@andrewvanbreda the edit buttons now seem to be working as expected, thanks.

We are not expecting any 1 km counts to be entered in Welsh (and there is only an English form with which to enter the 1 km results) so I don't think any further action is required.

I think we can close this one?
