### ISSUE TITLE
Problem with entering 1 km FIT Counts

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#113]
A 1 km survey volunteer reports:

> There appears to be an error with the website, unless I clear the 1km square field (I had it locked) before adding a second set of data the form returns 'please select a 1km square' and then overrides data I have added when I re-enter the 1km location. This has resulted in a FIT count with no accurate grid reference.

I haven't had a chance to check this myself. It may only be a problem if the padlock is applied to lock the attribute, in which case a short-term solution would be to remove the padlock so that the user has to re-enter the 1 km square each time.

The same issue may arise for the 1 km pan-trap form, but again I haven't yet been able to check.

**Comment by andrewvanbreda** [comment]
@kitenetter
Note will look as soon as possible

**Comment by andrewvanbreda** [comment]
@kitenetter 
I have removed padlock on 1km and pan trap forms on live and test.

I would imagine this behaviour would have been same in iRecord (the fields and javascript code driving it are unaltered).
Altering the code that came across from iRecord is beyond scope of current budget, although I do realise there is a requirement for copying the spatial reference over from previous samples, am not sure whether or not this will fall under that as that remains to be implemented (still as haven't had time yet).

**Comment by kitenetter** [comment]
There is no requirement to copy spatial refs from previous sample for the FIT Count form (it is only for the pan-trap form that we'd like to be able to copy over the precise grids).

Removing the padlocks is probably all that is needed at the moment, so this can probably be closed?
