### ISSUE TITLE
Pan-trap data entry form is not storing the sample location ID

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#115]
Applies to:
https://ukpoms.org.uk/add-1km-samples

The 1 km square location ID is not being saved into location_id in the samples table. 

As a result, this page is not getting updated correctly:
https://ukpoms.org.uk/square-volunteer-pantrap-statuses

and the samples are being stored as sensitive, which I don't think we intended.

**Comment by andrewvanbreda** [comment]
@kitenetter 
I will have to look at this tomorrow.
It seems to me iRecord is using a field that wouldn't normally store the location_id either (it uses imp-location:name).
So it seems to me that iRecord might of been doing something "funny" that has failed to copy across to the new website correctly.

The sensitive thing was actually deliberate, I didn't know it wasn't supposed to be like that.
I can switch it off easily, but I will leave it on as if we need to do mass data correction we don't want a mish-mash of data in different states, it will be easier to handle if we know the data is all the same.

**Comment by andrewvanbreda** [comment]
@kitenetter 
I have fixed this as of 10:15 on the 22 June (mentioning time as maybe useful dealing with existing data). Also removed privacy protection at that time.

Problem was so subtle, but unfortunately it stopped it working at all. It related to iRecord getting the data from a report, and the new website getting the data directly from the database table.

Will have to think how to correct the existing data.

**Comment by andrewvanbreda** [comment]
Note the 1km form configuration looks to be correct

**Comment by andrewvanbreda** [comment]
@kitenetter 
I think there are 207 samples that need correction.
I believe this can be done, as although the spatial reference that is entered will not match up with the square numbers, I think the first 4 digits always do.
The exception to this I think are squares SE1845, SE1867 which share the first 4 digits so I cannot use that rule, so will have to treat as special case and can probably use a manual correction.
I will fix the privacy_precisions also.

Can you confirm you are happy to do an automated link to the location using this logic as a basis, I will write the sql to send to Biren if you are.
Thanks

**Comment by kitenetter** [comment]
@andrewvanbreda here are the location links that need to be added for the samples. I make it 206 that need correcting, but that will be because I've just deleted my test data entry from yesterday.

[PanTrap_1km_location_edits.xlsx](https://github.com/BiologicalRecordsCentre/PoMS/files/6693478/PanTrap_1km_location_edits.xlsx)

**Comment by andrewvanbreda** [comment]
@kitenetter 
OK thanks, will see if I can use this list instead for the updates instead of the vaguer algorithm I mentioned.

**Comment by andrewvanbreda** [comment]
@kitenetter @BirenRathod 
OK am not going to use that spreadsheet for corrections;
Trying to copy out all the IDS for an update is very time consuming, but more importantly more liable to mistakes than automatic I think.
We can use to verify the result.

Firstly I should say, we don't need to worry about those squares I mentioned as they aren't even involved in this.

@BirenRathod can you run these two statements.
The first is an update statement, but as you will see, it just sets the updated_on to itself, so won't doing anything, however will give us an idea of the affected row numbers (i.e if the number of affected rows is right, it is much more likely the sql is ok.
So this first statement I just need to know the number of affected rows/

The second is pretty much the same statement, but written as a select, so I can see what IDs will be inserted into the samples.

update indicia.samples smp
set updated_on=smp.updated_on
from indicia.locations l
where LEFT(l.centroid_sref,4) = LEFT(smp.entered_sref,4) 
AND smp.survey_id = 638 and smp.location_id is NULL AND smp.entered_sref_system='OSGB' AND smp.deleted=false 
and l.location_type_id = 13870 AND l.deleted=false;

select smp.id,smp.entered_sref,l.id,l.centroid_sref
from indicia.samples smp
join indicia.locations l on LEFT(l.centroid_sref,4) = LEFT(smp.entered_sref,4) and l.location_type_id = 13870 AND l.deleted=false
where smp.survey_id = 638 and smp.location_id is NULL AND smp.entered_sref_system='OSGB' AND smp.deleted=false;

**Comment by BirenRathod** [comment]
@andrewvanbreda 
First query returned with 206 updated rows.
I have attached result of second query below.
[data-1624363172375.zip](https://github.com/BiologicalRecordsCentre/PoMS/files/6694036/data-1624363172375.zip)

**Comment by andrewvanbreda** [comment]
@BirenRathod 
This looks like the right result (didn't try whole spreadsheet, but checking a random).

Can you run the following two statements please

update indicia.samples smp
set privacy_precision=null, location_id = l.id, updated_by_id = 5553, updated_on = now()
from indicia.locations l
where LEFT(l.centroid_sref,4) = LEFT(smp.entered_sref,4) 
AND smp.survey_id = 638 and smp.location_id is NULL AND smp.entered_sref_system='OSGB' AND smp.deleted=false 
and l.location_type_id = 13870 AND l.deleted=false;

insert into indicia.work_queue(task, entity, record_id, cost_estimate, priority, created_on)
select 'task_cache_builder_update', 'sample', id, 100, 2, now()
from indicia.samples
where survey_id = 638 and updated_by_id = 5553;

**Comment by BirenRathod** [comment]
@andrewvanbreda It has updated 206 records.

**Comment by BirenRathod** [comment]
@andrewvanbreda All done.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
@kitenetter 
Thanks Biren, thanks for the help getting this sorted out.
Martin this should be fixed now but it may take a little time to filter through the work_queue

**Comment by kitenetter** [comment]
@kitenetter to do final check and close if all okay

**Comment by kitenetter** [comment]
All okay, closing.
