### ISSUE TITLE
1 km pan-trap data entry issues

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#116]
Aplies to https://ukpoms.org.uk/add-1km-samples

The auto-complete for the 1 km squares finds the first letter very quickly but fails to narrow the choices down as you add the second letter and the initial number - may be related to #115 

When the square has been selected from the auto-complete list, the map should zoom in to the square - I guess this may also be related to #115 

Date-picker is hidden behind map

**Comment by andrewvanbreda** [comment]
1.
This is controlled by the response from the Warehouse not the website, am also not seeing this issue.
Do you have an example entry that is causing the problem, also browser/system used.
I just tried and response was immediate.

2. Yes this is related to that.
But I am confused as iRecord doesn't use a field that would store in location_id, it uses a field that would store to location_name text.
So it must be doing something funny. I will have to investigate as part of the other issue.

3.
Date picker is know in another issue, I previously tried a fix, but it actually breaks the map. Haven't got a working solution yet.

@kitenetter
Can you let me know about number 1, cheers.

**Comment by kitenetter** [comment]
@andrewvanbreda I can no longer reproduce the problem with the auto-complete, it's working fine this morning, and is also zooming in to the map correctly.

**Comment by andrewvanbreda** [comment]
@kitenetter 
Zoom was fixed as part of #115
Fixing that one automatically caused the zoom to start working.

I will close this then as the date picker problem is already know, and I think the first point might of been the Warehouse having a bad moment.
