### ISSUE TITLE
Improve presentation of yellow help areas

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/PoMS#117]
Experiment with basic html instead as some users find the yellow help hard to read.

**Comment by andrewvanbreda** [comment]
@kitenetter 
How about this test page. The yellow replaced with a Strong bold paragraph apart from the bit about saving at the bottom which is emphasis italic (just because it looked better to my eyes like that). Best to look at the test page when logged out so you can also see the personal details section. Let me know your thoughts.

https://test-ceh-poms.pantheonsite.io/enter-fit-count

**Comment by andrewvanbreda** [comment]
IGNORE THIS FOR THE MINUTE
I just noticed the changes I made a few weeks ago have been overwritten for some reason

**Comment by kitenetter** [comment]
Let me know if this can be reinstated

**Comment by andrewvanbreda** [comment]
@kitenetter 
Done. 
Let me know if you like this styling and will apply to other pages and live.

(Just to note, I am aware the "How much of your 50x50cm patch was occupied by the target flowers?" termlist has the wrong size icons next to them on the test site, so please ignore that for this issue).

**Comment by andrewvanbreda** [comment]
Note these text changes will not be available on test after Biren clones live onto the test site (until I reinstate the change anyway). I will write a note once I have done that.

**Comment by BirenRathod** [comment]
@andrewvanbreda This is why I asked if I can clone first test to dev then you will not lose anything.

**Comment by kitenetter** [comment]
Not sure if changes were made to the live site, but in any case this has not been raised as an issue recently. Closing.
