### ISSUE TITLE
Setup user roles and permissions on site

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/PoMS#12]
As per issue title

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy

Am a bit confused by the roles the site will have. I have the following information from one of the documents.
Are the "1km square survey - Flower-Insect Timed Counts" and "1km square survey - pan-trap samples" entered by users with the same user role then? ( PoMS volunteer)

1 | PoMS volunteer * | Carry out field survey, record data on paper form, collect insect specimens to send to UKCEH | n/a | n/a
2 | PoMS volunteer * | Transcribe data onto website form | ENTER pan-trap data | Sample data (linked to PoMS locations) plus occurrence data for flower counts
2a | PoMS volunteer* | If needed, edit data previously entered | EDIT pan-trap SAMPLE data [a report to select existing sample, which is then edited] |  
3 | UKCEH staff ** | Sort insect specimens into taxon groups and  count | BYCATCH data: select pan-traps [a report to select existing sample, which is then edited] | Occurrence data for insect groups
4 | Consultant entomologists ** | Identify bee and hoverfly specimens to species | SPECIES data: select pan-traps [a report to select existing sample, which is then edited] | Occurrence data for insect species

**Comment by kitenetter** [comment]
Yes, the role "PoMS volunteer" applies to the set of people who carry out the 1km square surveys for us, which includes pan-trapping and FIT Counts. This set of FIT Counts is stored in a separate survey to the public FIT Counts.

Martin



________________________________

**Comment by andrewvanbreda** [comment]
Thanks Martin. This information will help me setup the roles correctly.

**Comment by andrewvanbreda** [comment]
@kitenetter 
Just setting this up.
Do we even need the PoMS volunteer role on the site actually, as shouldn't all registered users have that role level?

**Comment by kitenetter** [comment]
@andrewvanbreda I hadn't noticed that the [list above](https://github.com/BiologicalRecordsCentre/PoMS/issues/12#issuecomment-793794451) has drifted a bit from our original specification, which is given in this document:

[PoMS recording forms and user roles.docx](https://github.com/BiologicalRecordsCentre/PoMS/files/6185094/PoMS.recording.forms.and.user.roles.docx)

Is that document okay, or do you need any further info?

**Comment by andrewvanbreda** [comment]
@kitenetter Am not sure to be honest. Let me complete what I think should happen, I will then describe it to you, then you can raise your hand for changes.

**Comment by andrewvanbreda** [comment]
@kitenetter 
Have tested permissions and this is how it is currently setup


All testing done directly copying the URL into address bar as some items not yet available in menu.
Also checked items appear in menu where appropriate.

ANONYMOUS USER
Enter Public Fit Date (English) - Can Access
Enter Public Fit Date (Welsh) - Can Access
Fit Count Map (English) - Can access
Fit Count Map (Welsh) - Can access

1km entry (English) - Can't access
1km entry (Welsh) - Can't access
Pan-trap entry (English) - Can't access
Pan-trap entry (Welsh) - Can't access
My results (English) - Can't access
My results (Welsh) - Can't access
Administrator samples list (English) - Can't access
Administrator samples list (Welsh) - Can't access
Administrator list squares (English) - Can't access
Administrator list squares (Welsh) - Can't access
Pantrap square allocation status (English) - Can't access
Pantrap square allocation status (Welsh) - Can't access
User details (English) - Can't access
User details (Welsh) - Can't access
Bycatch data list for CEH staff (English) - Can't access
Bycatch data list for CEH staff (Welsh) - Can't access
Species data list for Consultants (English) - Can't access
Species data list for Consultants (Welsh) - Can't access
Edit Square (English) - Can't access
Edit Square (Welsh) - Can't access



AUTHENTICATED USER (PoMS Volunteer)
Enter Public Fit Date (English) - Can Access
Enter Public Fit Date (Welsh) - Can Access
1km entry (English) - Can access
1km entry (Welsh) - Can access
Pan-trap entry (English) - Can access
Pan-trap entry (Welsh) - Can access
Fit Count Map (English) - Can access
Fit Count Map (Welsh) - Can access
My results (English) - Can access
My results (Welsh) - Can access

Administrator samples list (English) - Can't access
Administrator samples list (Welsh) - Can't access
Administrator list squares (English) - Can't access
Administrator list squares (Welsh) - Can't access
Pantrap square allocation status (English) - Can't access
Pantrap square allocation status (Welsh) - Can't access
User details (English) - Can't access
User details (Welsh) - Can't access
Bycatch data list for CEH staff (English) - Can't access
Bycatch data list for CEH staff (Welsh) - Can't access
Species data list for Consultants (English) - Can't access
Species data list for Consultants (Welsh) - Can't access
Edit Square (English) - Can't access
Edit Square (Welsh) - Can't access



UKCEH STAFF
Enter Public Fit Date (English) - Can Access
Enter Public Fit Date (Welsh) - Can Access
1km entry (English) - Can access
1km entry (Welsh) - Can access
Pan-trap entry (English) - Can access
Pan-trap entry (Welsh) - Can access
Fit Count Map (English) - Can access
Fit Count Map (Welsh) - Can access
My results (English) - Can access
My results (Welsh) - Can access
Bycatch data list for CEH staff (English) - Can access
Bycatch data list for CEH staff (Welsh) - Can access

Administrator samples list (English) - Can't access
Administrator samples list (Welsh) - Can't access
Administrator list squares (English) - Can't access
Administrator list squares (Welsh) - Can't access
Pantrap square allocation status (English) - Can't access
Pantrap square allocation status (Welsh) - Can't access
User details (English) - Can't access
User details (Welsh) - Can't access
Species data list for Consultants (English) - Can't access
Species data list for Consultants (Welsh) - Can't access
Edit Square (English) - Can't access
Edit Square (Welsh) - Can't access



CONSULTANT ENTOMOLOGISTS
Enter Public Fit Date (English) - Can Access
Enter Public Fit Date (Welsh) - Can Access
1km entry (English) - Can access
1km entry (Welsh) - Can access
Pan-trap entry (English) - Can access
Pan-trap entry (Welsh) - Can access
Fit Count Map (English) - Can access
Fit Count Map (Welsh) - Can access
My results (English) - Can access
My results (Welsh) - Can access
Species data list for Consultants (English) - Can access
Species data list for Consultants (Welsh) - Can access


Administrator samples list (English) - Can't access
Administrator samples list (Welsh) - Can't access
Administrator list squares (English) - Can't access
Administrator list squares (Welsh) - Can't access
Pantrap square allocation status (English) - Can't access
Pantrap square allocation status (Welsh) - Can't access
User details (English) - Can't access
User details (Welsh) - Can't access
Bycatch data list for CEH staff (English) - Can't access
Bycatch data list for CEH staff (Welsh) - Can't access
Edit Square (English) - Can't access
Edit Square (Welsh) - Can't access

**Comment by kitenetter** [comment]
@andrewvanbreda 
Your list of permissions is not quite what I was expecting. In particular, the "PoMS volunteer" role is different to the "Authenticated user" role, and there are a few changes in the page permissions. See:

[PoMS roles and page access permissions.docx](https://github.com/BiologicalRecordsCentre/PoMS/files/6508314/PoMS.roles.and.page.access.permissions.docx)

Let me know if you want me to make any changes to the roles or permissions on the site.

**Comment by andrewvanbreda** [comment]
@kitenetter 
Ok, I will try to make the changes, I had originally followed this table as best I could

![Screen Shot 2021-05-18 at 13 17 05](https://user-images.githubusercontent.com/2463614/118810538-e5d42e00-b8a3-11eb-8a02-33806f44664f.png)

But will try to change to match document as best I can

**Comment by andrewvanbreda** [comment]
@kitenetter 
Changes made.
I can't test every combination though at this time, but can check important ones tomorrow morning.
Leave open for now.
Also there may need to be some alterations depending on how I implement UKCEH staff, consultants going forward as not sure if they will have their own forms or just open existing form in special mode.

**Comment by andrewvanbreda** [comment]
The following have been tested for every combination of access in the "PoMS roles and page access permissions.docx" Word document Martin posted above.
User roles "Anonymous User", "Authenticated User", "1KM Square Volunteer", "UKCEH Staff", "Consultant Entomologists" tested.
Note: some of these are not in the menu system yet, but have been tested by going directly to URL.

https://ukpoms.org.uk/1km-fit-count
https://ukpoms.org.uk/cy/1km-fit-count
https://ukpoms.org.uk/add-1km-samples
https://ukpoms.org.uk/cy/add-1km-samples
https://ukpoms.org.uk/my-results
https://ukpoms.org.uk/cy/my-results
https://ukpoms.org.uk/square-volunteer-pantrap-statuses
https://ukpoms.org.uk/cy/square-volunteer-pantrap-statuses
https://ukpoms.org.uk/select-samples-bycatch-data
https://ukpoms.org.uk/cy/select-samples-bycatch-data
https://ukpoms.org.uk/select-samples-species-data
https://ukpoms.org.uk/cy/select-samples-species-data
https://ukpoms.org.uk/node/4 (samples list)
https://ukpoms.org.uk/cy/node/4 (samples list)
https://ukpoms.org.uk/node/13  (squares list)
https://ukpoms.org.uk/cy/node/13 (squares list)
https://ukpoms.org.uk/users
https://ukpoms.org.uk/cy/users
https://ukpoms.org.uk/edit-square?location_id=186486
https://ukpoms.org.uk/cy/edit-square?location_id=186486

Unregistered users can access these pages, untested for other users, but assume they can access these

https://ukpoms.org.uk/enter-fit-count
https://ukpoms.org.uk/cy/enter-fit-count
https://ukpoms.org.uk/fit-counts-map
https://ukpoms.org.uk/cy/fit-counts-map
https://ukpoms.org.uk (home)
https://ukpoms.org.uk/cy (home)
https://ukpoms.org.uk/news
https://ukpoms.org.uk/cy/news
https://ukpoms.org.uk/faqs
https://ukpoms.org.uk/cy/faqs
https://ukpoms.org.uk/about
https://ukpoms.org.uk/cy/about
https://ukpoms.org.uk/contact
https://ukpoms.org.uk/cy/contact
https://ukpoms.org.uk/taking-part
https://ukpoms.org.uk/cy/taking-part
https://ukpoms.org.uk/fit-counts
https://ukpoms.org.uk/cy/fit-counts
https://ukpoms.org.uk/fit-count-app
https://ukpoms.org.uk/cy/fit-count-app
https://ukpoms.org.uk/one-km-square-survey
https://ukpoms.org.uk/cy/one-km-square-survey
https://ukpoms.org.uk/species-recording
https://ukpoms.org.uk/cy/cofnodi-rhywogaethau
https://ukpoms.org.uk/reports
https://ukpoms.org.uk/cy/reports
https://ukpoms.org.uk/research
https://ukpoms.org.uk/cy/research
https://ukpoms.org.uk/data
https://ukpoms.org.uk/cy/data
