### ISSUE TITLE
Year filters should be newest year first

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/PoMS#120]

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Whenever you get a chance could you pull these reports please. These are versions that aren't live so should be safe to do. Cheers

projects/PoMS/blurred_poms_results_cache_3
projects/PoMS/blurred_poms_results_lingual_3
projects/PoMS/blurred_poms_results_mapping_lingual_3
projects/PoMS/blurred_poms_results_mapping_cache_3.xml
projects/PoMS/my_pan_trap_results_in_detail_lingual_2.xml
projects/PoMS/my_pan_trap_results_in_detail_mapping_lingual_2.xml
projects/PoMS/my_poms_results_in_detail_lingual_3
projects/PoMS/my_poms_results_in_detail_mapping_lingual_2.xml
projects/PoMS/poms_results_in_detail_admin_cache_3
projects/PoMS/poms_results_in_detail_admin_lingual_3
projects/PoMS/poms_results_in_detail_mapping_admin_cache_3.xml
projects/PoMS/poms_results_in_detail_mapping_admin_lingual_3.xml

**Comment by BirenRathod** [comment]
@andrewvanbreda  these are gone live now.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Thanks Biren :)

**Comment by andrewvanbreda** [comment]
@kitenetter
This is live now. It will also add a new year to the filter automatically each January.
The Target Flower column is also improved, instead of just saying "Other please describe below" (when there is no below in the case of the grid), it says "Other" with the other flower in brackets.
