### ISSUE TITLE
Form to allow 1km square volunteers to edit their pan-trap data

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#124]
Relates to #118 

1km square volunteers enter pan-trap data here:
https://ukpoms.org.uk/add-1km-samples

At the moment they are unable to edit that data.

We need a report that displays the pan-trap data and provides an edit button.

I think this probably needs a new page, “My pan-trap results”, that is only available to users with the 1 km square surveyor role. 

Alternatively we could have a page that displays pan-trap samples for all locations, but only displays an edit button for samples entered by the currently logged-in user (which was how this used to work in iRecord).

The equivalent page on iRecord is the first of the three links given in #118

**Comment by kitenetter** [comment]
Hi @andrewvanbreda - next time you're able to work on the PoMS website I'd be grateful if you could progress this issue as a priority. We are getting an increasingly long list of records that need to be edited and I fear that we could end up with incorrect data getting in to the results.

**Comment by andrewvanbreda** [comment]
@kitenetter 
Ok yes, I have been doing Plant Portal, but I don't think that is going live today.
Let me see if I can do this one now.

**Comment by andrewvanbreda** [comment]
@BirenRathod @kitenetter 
Hi Biren,

I have written a couple of simple reports to handle this at a basic level for now,
so the user can see the iRecord columns and see points on a map.
We can adjust from there as needed.
Biren, when you get a chance can you pull these two new reports onto live.
my_pan_trap_results_in_detail_lingual.xml
my_pan_trap_results_in_detail_mapping_lingual.xml

Cheers

**Comment by BirenRathod** [comment]
@andrewvanbreda I have pulled those reports now.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Thanks Biren for quick response

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Hi Biren,

Would you be able to pull those again as made a couple of improvements.

Cheers

**Comment by BirenRathod** [comment]
@andrewvanbreda Done.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Thanks Biren. I knew you had before I saw your message as I saw the two changes come through (y)

**Comment by andrewvanbreda** [comment]
@kitenetter 
Martin. This is now live.
It is just a basic page for now with no download, but allows editing.
You would have to let me know whether you want a download with extra columns (or the same columns as the grid).
Note the Welsh page just shows the same as the English at the moment.

**Comment by kitenetter** [comment]
Many thanks @andrewvanbreda and @BirenRathod - I've just tested that and all works as expected. 

We don't need a download, nor anything different for the Welsh page.
