### ISSUE TITLE
Limit reports to UK only

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/PoMS#125]
@BirenRathod 
Can you pull the PoMS reports folder on live warehouse please. 
There are lots of new reports (well new files for altered versions of old reports). 
Should be safe to pull, they are all new reports apart from one of them which is an edit, and that one has only been deployed to test so far.

Thanks

**Comment by BirenRathod** [comment]
@andrewvanbreda All reports gone live now.

**Comment by andrewvanbreda** [comment]
@kitenetter 
Deployed to live.
Following pages now limited to UK, Isle of Man, Jersey, Guernsey

(English & Welsh) 
Fit Count Map inc grid, map, result count
List of Samples for administrators inc grid, map, result count

Left the My Results pages, as you'll always want to see your results no matter where you put them (even it is put on the moon we would want the user to be able to correct that).
1km, and pan-trap also excluded as discussed, we don't need these  exclusions.
