### ISSUE TITLE
Add pan trap data - English names for plants not available

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#126]
On the pan-trap data entry form:
https://ukpoms.org.uk/add-1km-samples

there is an occurrence grid for entering flower counts. The grid will only accept scientific names, but it should accept English names as well. I can't see any reason for the English names to be unavailable; the form seems to be set up to allow English names:

![image](https://user-images.githubusercontent.com/16039111/127356745-552a0fc1-70f1-43f8-ad9b-dcd0c063dbd0.png)

**Comment by andrewvanbreda** [comment]
@kitenetter 
At the moment I cannot explain this, I set test site up to match iRecord and it is still doing it so will need to look tomorrow

**Comment by andrewvanbreda** [comment]
Note it isn't the settings as even setting to All Names Are Available results in "Australian Blackwood" for example not being found

**Comment by andrewvanbreda** [comment]
@kitenetter 
Have looked into this.
I believe this is a bug in Indicia. The language option to show preferred terms in particular language for term lists is getting accidentally mixed into the options on the species grid so the species grid also wrongly thinks its search should be preferred only.
I will speak to John about the best way to fix.

**Comment by andrewvanbreda** [comment]
@kitenetter 
Have a fix working on test site. I will deploy this shortly. The site will be offline for about 10 minutes (with usual maintenance mode message being displayed).

**Comment by andrewvanbreda** [comment]
@kitenetter 
Deployed. Close if happy, or let me know if not (although I did check it myself).
Actually a good sign is I noticed it also fixed another problem with the translation of the names in the species which I was previously having to override with jQuery

**Comment by andrewvanbreda** [comment]
@kitenetter 
Am going to close this one to reduce number of open issues. Just re-open if you feel you need to.
