### ISSUE TITLE
Add emails to "People" table

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#127]
Please add a column for email address, in the same way you did for the FIT Count website.

**Comment by BirenRathod** [comment]
@kitenetter Email column added now on people list. Also, I found some spam users, could you please delete them? usually end with .site extension. Seems like spam module is not working properly. I will find an another solution for it.

**Comment by kitenetter** [comment]
Thanks @BirenRathod - it was the spam users that made me ask you for the email column! I will get rid of them. Closing this issue.
