### ISSUE TITLE
Provide csv download for list of survey square statuses

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#128]
On the 'survey statuses' page in the Admin menu (https://ukpoms.org.uk/square-volunteer-pantrap-statuses) can we add a option to download the grid into a csv file. 

The page itself is only visible to the admin role at the moment, and the download button should also be specifically restricted to the admin role if possible (in case we make the page more widely accessible in future).

**Comment by andrewvanbreda** [comment]
Hi @kitenetter 
I have enabled this option.

As the page is currently for admins only, I just enabled the download option.

To limit the download specifically to administrators would require separate versions of the page for public/admin which is outside the current budget for the project.
This can be taken into account if there is an enhancement in the future to open this page to the public.

Please close if happy with the change, or leave open if you want to get the download to be limited to admins, although that would require further budget.
I can create a Github label for issues that would require extra budget if you like.

**Comment by andrewvanbreda** [comment]
@kitenetter 
Actually I just noticed something funny with way site is setup.
The "PoMS.roles.and.page.access.permissions" page specifies that "1km square volunteers" and "UKCEH Staff" can access this page.
However these users don't have rights to the Administration menu which these pages were placed into.
So they have the odd situation where they cannot access this page from the menu system, but if they know the URL, they can go to the page.
Can you clarify how this is supposed to be as it also affects your requirement in this issue.
For now I left the download option available on that page.

**Comment by kitenetter** [comment]
Thanks @andrewvanbreda - I'll have a think about who needs to access this page. For now at least the download is fine the way you've implemented it.

**Comment by kitenetter** [comment]
We are not in fact using [survey statuses](https://ukpoms.org.uk/square-volunteer-pantrap-statuses) for anything at the moment, and don't have time to update it, so I have unpublished it for now. Will review if a need subsequently arises.

Closing this issue.
