### ISSUE TITLE
Size of text in species recording grids

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#130]
The grids we use on the PoMS website all have a larger font than I would like, and for the species data entry form the current font is very congested:

![image](https://user-images.githubusercontent.com/16039111/133482541-77b67b48-abf5-4e26-947c-03cfb0278820.png)

That is from https://ukpoms.org.uk/node/44/edit

@BirenRathod are you able to adjust the font size in these grids or do I need to go back to Steve Dixon?

**Comment by BirenRathod** [comment]
@kitenetter When you say adjust font size, do you want me to increase or decrease? Also, do you want me to do same for dropdown too?

**Comment by kitenetter** [comment]
This has not been raised as an issue recently. Closing.
