### ISSUE TITLE
Target Flower not showing in some grids unless Other option is used

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/PoMS#132]
@BirenRathod 
Hi Biren,
I noticed a (silly) bug, whenever you get a chance, can you pull these two reports (which I assume will be next week).
Thanks

reports/projects/PoMS/blurred_poms_results_cache_3.xml
reports/projects/PoMS/poms_results_in_detail_admin_cache_3.xml

**Comment by BirenRathod** [comment]
@andrewvanbreda Did you commit this to master branch? I have pulled the repository but nothing updated.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Thanks Biren,
Yes the push had failed, am not sure how I didn't notice that.
I have now pushed the change.

**Comment by BirenRathod** [comment]
@andrewvanbreda Both reports gone live now.

**Comment by andrewvanbreda** [comment]
@BirenRathod @kitenetter 
Thanks Biren, this is working now.
Note I changed issue title because I just noticed the original title was wrong, the problem related to the Target Flower..
