### ISSUE TITLE
Photos missing

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#133]
I just edited this page:
https://ukpoms.org.uk/species-recording

The photos that were previously showing on the page have now disappeared. I'm not sure if they were missing before I did the edit, or if the edit has caused them to be lost.

Is there an easy way of reinstating them or do I have to manually re-insert them?

**Comment by BirenRathod** [comment]
@kitenetter When I clicked edit, all images were there. So I just re-added them at their original place.

**Comment by kitenetter** [comment]
Thanks @BirenRathod 

Why did they get lost, and how can I stop this happening again?

**Comment by BirenRathod** [comment]
@kitenetter It is not your fault actually. I just noticed that the backup hasn't restored the style folder which used by these images. I have now copied those.
