### ISSUE TITLE
Photos not uploading on Drupal 9

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/PoMS#134]
@BirenRathod @kitenetter @CCarvell 
I just noticed a problem after reading someone's comment on a Sample, the new Drupal 9 site image uploading is not working.

https://ukpoms.org.uk/enter-fit-count

Output stream error clicking on Add Photo button.

Biren are you able to look at what is happening here?

**Comment by BirenRathod** [comment]
@andrewvanbreda There are some pending commit to release on live ukpoms. Can I do it first? So I could find out the problem .

**Comment by andrewvanbreda** [comment]
@BirenRathod Yes please do as all those commits are to do with logging, or stuff we will need but isn't deployed yet. So not of it will affect site. Those commits can be copied to live.

**Comment by BirenRathod** [comment]
@andrewvanbreda It has resolved now. The file helper_config you added last, it has got interim_image_folder variable left which I have commented now.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
OK great thanks. Ok, that explains why it passed testing.

@kitenetter @CCarvell 
There might now be some samples which people will need to upload pictures to.
I dunno if it would be worth us querying the database for samples in the time between now and when the language fix was done, and then you could email the people involved if you get you that info?

**Comment by kitenetter** [comment]
There are samples without photos but the photos are not mandatory and it might be more trouble than it is worth to email people and ask them to edit them. What date did the problem start?

**Comment by andrewvanbreda** [comment]
@kitenetter 
It would have been about 3pm on Thursday 23rd September.

I did see one sample comment of someone actually saying they couldn't upload their photos.
The sample ID was 15619068.
We could get Biren to query the database so we can see the comments since Thursday and contact the people who actually said that are having trouble?
