### ISSUE TITLE
Linking samples to emails

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#137]
If a user adds a public FIT Count to the PoMS website, their email address gets stored in cache_samples_nonfunctional.attr_email.

However, if a user adds a 1 km square FIT Count, no email address is stored in cache_samples_nonfunctional.attr_email.

Is there a reason for this difference?

**Comment by andrewvanbreda** [comment]
@kitenetter 
Going by the name of that field I would imagine it only stores the email from users who entered their email who filled in the Public FIT Count page unregistered. This is stored in an attribute.
Now I am not sure, but that page might also store the email address of registered users in that attribute automatically.

The other pages do not support unregistered users, so there is no need for this attribute.
So I think to find the email address in that case you would have to join to the user table using the created_by_id field, then join from users to people table, then get email from there.
