### ISSUE TITLE
Make project squares work on new website

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/PoMS#14]
Project squares need to work on new website.
Also look on iRecord to see if "1km square survey - Flower-Insect Timed Counts" & "1km square survey - pan-trap samples " use different squares.

**Comment by kitenetter** [comment]
There is only one set of 1km squares, and it is used for both those surveys. The squares are all set up in the warehouse locations table, and have type = "PoMS 1km squares".

A couple of squares have had to be discarded over the years, so I'm fairly sure that the warehouse list contains more than the 75 squares that we currently use.

**Comment by andrewvanbreda** [comment]
@kitenetter 
Thanks, this is very useful information. I will add these to the new website then.
Thanks again

**Comment by andrewvanbreda** [comment]
Squares now working in square maintenance area, and on applicable forms.
