### ISSUE TITLE
"Read more" link not working on news page

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#145]
On this page:
https://ukpoms.org.uk/news

there is a "Read more" link, set up via the "Pager" in the view settings. However, the "Read more" link does not function, and the older news stories are inaccessible.

Hoping this is an easy fix but let me know if not!

**Comment by andrewvanbreda** [comment]
@kitenetter 
Has this gone wrong recently? or was it always like this
I didn't setup the News view, but from what I can tell we don't actually control this functionality, it is Drupal. This leaves me with very few options apart from trying to switch it on/off, clearing caches, fiddling with a few settings.
Nothing working.

@BirenRathod 
Do you have any ideas? Might it be a bug in Drupal 9.4?

One possibility is to extend the list so all news stories are shown, but that might make the page very long.

**Comment by kitenetter** [comment]
Not sure if it has gone wrong recently, as we've only recently acquired more than six news stories!

Let's see if Biren can suggest anything.

**Comment by andrewvanbreda** [comment]
@kitenetter 
Just looked at NPMS and noticed it has a similar More button that doesn't work, however in that case there is a pager setup.
I have changed UKPoMS so that it uses a pager instead of a "Read More..." link.
At least now it works, even if it is working differently.

**Comment by andrewvanbreda** [comment]
@kitenetter 
Can you check if the new method is satisfactory, and close if ok, or reassign to Biren if not.
Cheers

**Comment by kitenetter** [comment]
@andrewvanbreda that has had a weird effect on the home page, which used to have a functioning "Read more" link. It is now listing all the news stories, with an odd pagination link at the bottom.

I'm happy with the pager here:
https://ukpoms.org.uk/news

but would prefer the home page to go back to what it was.

**Comment by andrewvanbreda** [comment]
@kitenetter 
I have changed it to show 6 items at a time, same as before (it was previously showing 10)
I have also changed tit o be a less intrusive mini arrow style pager
I don't think I can do any better than the way it is now, so if you need the Read More link you will need to assign to Biren again.

**Comment by andrewvanbreda** [comment]
@kitenetter 
Sorry I misunderood the issue. I will take action now to make sure home page not affected, and only news page is. Will let you know when done.

**Comment by andrewvanbreda** [comment]
@kitenetter 
I have changed New page to have the full pager, but 6 only News items per page.
Homepage should be the way it is before, it is using the same settings, although I can't see the Read More link, but as I say that page is now using same settings.
Can you check if it looks like it used to?
If not, can you tell me after which part of the page that Read More link was appearing after.
Thanks.

**Comment by andrewvanbreda** [comment]
Oh I can see a News Sidebar with Read More link on right side of homepage if that is what you meant.

**Comment by kitenetter** [comment]
That looks fine @andrewvanbreda many thanks (and yes it was the sidebar that I meant).

Closing.
