### ISSUE TITLE
Menu item displaying incorrectly

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#146]
Under "Add your results" there is a menu item "1 km FIT Counts" that should only be visible to users with the role "1KM Square Volunteer". At the moment it is visible to all users. If someone without the role clicks on the link, the page is inaccessible, which is fine but it would be preferable for it not to appear in the menu at all.

**Comment by andrewvanbreda** [comment]
@kitenetter 
Fixed.
The site was actually setup correctly, but when I rebuilt the permissions cache it fixed it.
Why that would corrupt I do not know. 
Please check it and then close this issue if happy, or comment further.

**Comment by kitenetter** [comment]
Thanks @andrewvanbreda - closing.
