### ISSUE TITLE
Typo in pan-trap form instructions

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/PoMS#147]
Hi @kitenetter 

I have noticed a typo on the pan-trap form, and it is also appearing on the SPRING website

"You will need to fill in a separate for for each of the five pan-traps in your square, each time you carry out a survey visit."
("for" appearing twice).

Can you confirm what this should say to I can change it on both sites?

**Comment by kitenetter** [comment]
@andrewvanbreda which form do you mean, is it one of the PDF forms?

**Comment by andrewvanbreda** [comment]
@kitenetter Near top of pan-trap data entry page

https://ukpoms.org.uk/add-1km-samples

**Comment by kitenetter** [comment]
Thanks - it should say:
"You will need to fill in a separate form for each of the five pan-traps"

I have corrected it on the English version of the UK PoMS website.

**Comment by andrewvanbreda** [comment]
@kitenetter 
Great.
I have also adjusted UK PoMS test, & SPRING Live/Test (with slightly altered wording as that project uses 10 pan-traps)
