### ISSUE TITLE
Website page revisions

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#149]
At the moment, every time we make even a minor edit to a PoMS page, it defaults to creating a new revision. I don't think this is necessary, and it presumably results in extra storage of all the versions that we don't need (and also makes it impossible to delete the older images that are no longer needed).

Is it possible to change the default so that it does not create a revision unless we need it to?

**Comment by andrewvanbreda** [comment]
Hi @kitenetter

There is a list of content types here,

https://ukpoms.org.uk/admin/structure/types/

Currently there are 4 types.

There is a mini menu on the right side of each row if you click the down arrow icon.

If you select the "Edit" option from the drop-down. You would be taken to these 4 pages depending on which content type you select.

https://ukpoms.org.uk/admin/structure/types/manage/article?destination=/admin/structure/types

https://ukpoms.org.uk/admin/structure/types/manage/page?destination=/admin/structure/types

https://ukpoms.org.uk/admin/structure/types/manage/brcvis?destination=/admin/structure/types

https://ukpoms.org.uk/admin/structure/types/manage/iform_page?destination=/admin/structure/types

In the bottom left of these pages are some options. 
Click on "Publishing options".
Make sure the "Create new revision" box is off, and click "Save content type".

I have switched off Create Revisions on all content type for now.

Please test this is working, as I am not creating content for the site, but am pretty sure that should work.
I will switch revisioning off on the dev/test site once you are happy, so let me know.

**Comment by kitenetter** [comment]
Thanks @andrewvanbreda that certainly seems to have sorted it out for page edits, and good to know how to control the setting as well. Closing.
