### ISSUE TITLE
Linking FIT Counts to local projects

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#151]
This is to pick up from earlier discussions e.g. #148 and the [list of local projects on the app github](https://github.com/NERC-CEH/fit-count-app/issues/130). See also the [specification document on Google Drive](https://docs.google.com/document/d/14J1cLm7rqEd2MRhgx-bTT5nxeGSqevDKLc2vPgzUS_s/edit?usp=sharing).

Next steps:
1. I think we need another meeting to agree how we are going to tackle this
2. I'm still uncertain whether we need to develop the full set of "Activity" functionality, or whether we can find a simpler tagging solution - hopefully we can make a quick decision on which of these options is the most realistic to focus on
3. Set a realistic timeline for development work

@andrewvanbreda @kazlauskis last time we discussed this we said that we would be able to work on it during May, but I'm aware that some time has passed - is May still realistic?

I will send a doodle to arrange an initial catch-up meeting.

**Comment by kazlauskis** [comment]
Yes, I am still good to work on this 👍

**Comment by kitenetter** [comment]
Have sent out a calendar appointment for 10am on Thurs 11 May.

@kazlauskis a question regarding the tagging option. If we were to go down that route, I think we would have a new custom attribute for the FIT Count survey that would hold the list of projects. If that list was to change, how easy is it to update the list within the app? Can termlists only be updated by doing a full app update, or is there a way of pulling terms from the warehouse on a more regular basis?

**Comment by kazlauskis** [comment]
If someone could write us a report that returns the latest list of projects, we can make it so that the app refreshes its terms internally regularly without a manual update in the app stores.

**Comment by kitenetter** [comment]
Following this morning's meeting we will set up specific issues to develop the tagging approach. Closing this issue.
