### ISSUE TITLE
Create projects termlist

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/PoMS#152]
Create a list of projects to that samples can be linked to.
List does not need to be complete to start with, but some project will be useful for Karolis to begin his work..

Each project to be linked to a country via an attribute.

We need to consider how these data structures will work. 
The current assumption will be all the attributes will be pointers (ids) rather than plain text.
But need to make sure we have consider how this will work, if for instance, we need to mark a project as finished (use an attribute?)

**Comment by kitenetter** [comment]
I think the use of IDs will work, as long as we can filter the list on an attribute for whether the project is active or not. The use of IDs will also cover us for situations where a project name may need to change during its lifetime.

Here is an initial list of the projects that I think will be happy to work with us during 2023:

[projects termlist.xlsx](https://github.com/BiologicalRecordsCentre/PoMS/files/11452636/projects.termlist.xlsx)

That file gives the project name, plus an attribute for country, and an attribute for status.

Country attribute: not sure if it is best to use a full country name, or the two-letter codes that we have used elsewhere. For now the only entry is "UK".

Status attribute: for now I have marked projects as "active" in this column, which would change to "expired" on completion of the project. Alternatively we could call this attribute "Active" and then use a true/false value. Either approach would work from my perspective.

**Comment by andrewvanbreda** [comment]
@kitenetter
OK thanks. I will create this list and let you know if have questions.

**Comment by kitenetter** [comment]
I've been liaising with the projects and already have a couple of requests to change names in the termlist. I can always make changes myself once the list is in the warehouse, but if you want to change it now it is:
- "Green Futures Newton Abbot" should be replaced with "The Bradley Bug Project"
- "Kent Plan Bee" should be "Kent's Plan Bee"

**Comment by kitenetter** [comment]
And a third change - I didn't do a very good job of guessing what people would want!
- "RHS pollinator counts" should be "RHS Plants for Pollinator Counts"

**Comment by andrewvanbreda** [comment]
Hi @kitenetter 
I just went to create this, but I just stumbled across this on the Warehouse.
https://warehouse1.indicia.org.uk/index.php/termlist/edit/797
I hope you have a Warehouse login to see this with?
Could you let me know what that termlist is "FIT Count project (PoMS)".
I assume this new termlist we are creating is different to this existing one?
Under the assumption it is different, could you let me know what this old termlist is used for (so termlists can be named appropriately).

**Comment by kitenetter** [comment]
@andrewvanbreda that termlist was set up last time we tried to implement a tagging system. It didn't work very well, partly because the list ended up being a mix of actual projects plus a tag for "how did you hear about PoMS". It was implemented on the old iRecord forms for PoMS, but suspended as it wasn't producing useful results.

I have now renamed it to "FIT Count project (PoMS) - expired" but let me know if that's not a good solution.

The termlist that we are currently discussing is a new one and I think it is best to ignore the old one.

**Comment by andrewvanbreda** [comment]
@kitenetter @kazlauskis 
I have created that list now.
For now I didn't create a specific attribute for "Active" because I think we can use the "Allow Data Entry" flag. If it isn't suitable we can always add the attribute, it is better that way round, than create an attribute then find we don't want to use it later.
I have attached to the project to a country using the sample term attribute we already use for attaching countries to samples (to determine the terms the sample should have available to them).

**Comment by kitenetter** [comment]
@andrewvanbreda @kazlauskis we have had a request to provide links to the websites for the projects that we are listing. I can see the value in doing this: it will give users more understanding of what the projects are, and how their FIT Count data will be used. But I'm not sure how best to include this extra information in the app and website interfaces.

Perhaps when a user selects a project, the link to it could be displayed on the app page?

In any case, does it make sense to add another attribute to the termlist so that we store the relevant website URLs? We can then decide later how best to make use of the link.

**Comment by andrewvanbreda** [comment]
@kitenetter 
Yes it would seem sensible to put it into an attribute.
@kazlauskis will need to comment on how he would want it stored.

**Comment by kitenetter** [comment]
The websites are:

- RHS Plants for Pollinator Counts: https://www.rhs.org.uk/science/conservation-biodiversity/wildlife/plants-for-pollinators
- The Bradley Bug Project: https://www.greenfutures-newtonabbot.co.uk/bradley-bug-recovery-network
- Kent's Plan Bee: https://www.kent.gov.uk/environment-waste-and-planning/nature-and-biodiversity/pollinators/kents-plan-bee-pollinator-action-plan
- Kingston University Biodiversity: https://kingstonunibiodiversity.blogspot.com/

**Comment by andrewvanbreda** [comment]
@kitenetter 
OK, I will just wait for Karolis to respond before doing anything

**Comment by kazlauskis** [comment]
> In any case, does it make sense to add another attribute to the termlist so that we store the relevant website URLs? We can then decide later how best to make use of the link.

Yes, we can show a link to the project in the app. I agree it makes sense to attach the URL to the project term as an attribute.

**Comment by andrewvanbreda** [comment]
@kitenetter 
Have created the attribute and filled them in with those URLs

**Comment by andrewvanbreda** [comment]
Hi @kazlauskis 
I am just creating the report you requested.
Am I correct in thinking this should return a list of project names for a country as a mandatory filter?

If so, can I check the following.

1. Do you want the project website URL attribute returned as a column? 
2. Do you want me to return the Allow Data Entry flag which we will use to indicate if project is active? or do you want me to automatically exclude the inactive ones completely?
3. How do you want to supply the country as a filter
termlists_term ID? (warehouse database ID e.g. 18965 for United Kingdom)
county code? (e.g. UK for United Kingdom)

**Comment by kazlauskis** [comment]
1. Yes
2. Exclude obsolete projects
3. I can use the warehouse ID or an ISO code, whatever is easier for you. I suggest we make the country filter param optional. By default, it should return all projects.

Also, please return the project ID (for survey upload) as well as the project name (for display).

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod,

Could you pull this report for Karolis please
projects/PoMS/get_projects_for_country

@kazlauskis 
This report returns these columns
id
name
country_name
country_code
website_url

It takes these mandatory parameters (the first two are the term attribute IDs that hold a project's country/website)
country_for_project_tt_attribute_id=8
url_for_project_tt_attribute_id=10
countries_termlist_id=974
projects_termlist_id=1050

These are also the 2 optional parameters we spoke about
country_id
country_code

The country_id is a warehouse termlists_term ID (e.g. 18965 for UK).

Obsolete projects are excluded based on the state of the Allow Data Entry flag (also projects can be deleted using standard deletion)

Not supplying optional parameters returns all projects.
Either code or ID can be supplied, if both are supplied, then both must be right or nothing will return.

I have also created a sample attribute that uses the project termlist as it's lookup, and allows us to save a project ID against a sample.
The Sample Attribute is called "Project" and has sample attribute ID 1759.
This attribute is currently only linked to the "FIT Count App" and "PoMS FIT Count (website)" surveys.

@kitenetter 
Are you able to confirm exactly which surveys will use the new project functionality?
For instance, UKPoMS also has a 1km survey which I am not currently including.

**Comment by BirenRathod** [comment]
@andrewvanbreda This has gone live now.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Thanks Biren

**Comment by kazlauskis** [comment]
@andrewvanbreda thanks, the report works well. One question, though, what if a project is global or is available to a number of countries, what would the `country_code` attribute value look like then?

**Comment by kitenetter** [comment]
@andrewvanbreda these projects apply only to the public FIT Count survey, and are not applicable to the 1 km square surveys.

@kazlauskis we have no requests or plans to introduce global or multi-country projects. I guess this is something that might be requested one day, but for now the focus is very much on projects that are within individual countries (and only within the UK so far),

**Comment by andrewvanbreda** [comment]
@kazlauskis
The report joins to the country attribute, so the project must be assigned a country before it will appear.
If this changes in the future and we do have global, in that case the report would need a change to Left Join and the country code would just be a blank cell.

**Comment by kazlauskis** [comment]
@andrewvanbreda Does that mean that the report can return the same project twice if it is assigned to two countries, or will the list be unique?

**Comment by andrewvanbreda** [comment]
@kazlauskis 
I hadn't thought about this because I got the impression it was one country per project.
I think actually the report would probably handle this as appearing as two rows, this could easily be changed if needed to be one row, with the countries displayed in one cell as a comma separated list.
However if it were the case that projects could have more than one country, it would have implications regarding other elements of this work.

@kazlauskis @kazlauskis 
Should we just close this "Create projects termlist" issue and open a issue for design discussion?

**Comment by kitenetter** [comment]
At the moment I am not aware of any requests for projects to be applicable in more than one country. I guess this might be something we might get asked about in future.

@CCarvell @DavidRoy do you foresee any requirement for projects to be applicable in more than one country?

**Comment by kitenetter** [comment]
As far as I'm aware the projects termlist is working for the UK, and is not (yet) needed elsewhere. Closing.
