### ISSUE TITLE
Write report that returns a list of projects and uses a country parameter

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/PoMS#153]
Code for Karolis so he can start his work.

**Comment by kitenetter** [comment]
Needs to include the status (active/expired) parameter as well.

**Comment by andrewvanbreda** [comment]
Done as part of this issue
https://github.com/BiologicalRecordsCentre/PoMS/issues/152

Note that the Active flag is included as we will use the Allow Data Entry flag on the project term.
