### ISSUE TITLE
Problems with adding data on Chrome

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#156]
This applies to the 1 km square form at:
https://ukpoms.org.uk/add-1km-samples

Accessed 27 June using Chrome - this appears to be a specific issue for Chrome, and these problems do not apply when using Edge.

**1 - Map display**
The map is not currently visible.

**2 - tabbing between fields**
Normally I use the tab key to move from one data entry field to the next, but if I use the tab on this form it jumps to the plant species list at the end - I'm sure it used to allow tabbing between consecutive fields before.

**3 - Unable to delete plant records**
Towards the bottom of the form is an add list grid, for the flower counts. It should be possible to delete and to edit entries that have been added to the list, but the delete button is not functioning, and there is no edit button (the edit button is missing on Edge as well as Chrome, not certain whether it was there before but I thought it was a standard function for 'add a list' type forms).

**Comment by andrewvanbreda** [comment]
Hi @kitenetter 
I have fixed the Edit on both English/Welsh versions.
This is a standard function, but it needs to be switched on.

I cannot reproduce the other problem, but am not running the latest Google Chrome very either, it is also on a Mac.
Do you know if your Google Chrome recently updated, I wonder if perhaps that version has issues.
Is there an error if you press F12 to go to the development tools area of Chrome?

**Comment by kitenetter** [comment]
I think Chrome did get an update yesterday, currently showing "Version 114.0.5735.134".

**Issue warning**:
`Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform`
`A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. Starting in Chrome 101, the amount of information available in the User Agent string will be reduced.
To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.
Note that for performance reasons, only the first access to one of the properties is shown.`

**Console errors** (these have some additional details in Chrome, let me know if you need all of that as well):
`jQuery.Deferred exception: indiciaFns.cookie is not a function TypeError: indiciaFns.cookie is not a function
    at https://ukpoms.org.uk/modules/custom/iform/media/js/indicia.locks.js?v=9.5.9:70:16
    at HTMLDocument.<anonymous> (https://ukpoms.org.uk/modules/custom/iform/media/js/indicia.locks.js?v=9.5.9:76:4)
    at e (https://ukpoms.org.uk/core/assets/vendor/jquery/jquery.min.js?v=3.6.3:2:30310)
    at t (https://ukpoms.org.uk/core/assets/vendor/jquery/jquery.min.js?v=3.6.3:2:30612) undefined`

`jQuery.Deferred exception: indicia.locks.initControls is not a function TypeError: indicia.locks.initControls is not a function
    at HTMLDocument.<anonymous> (https://ukpoms.org.uk/add-1km-samples:1032:15)
    at e (https://ukpoms.org.uk/core/assets/vendor/jquery/jquery.min.js?v=3.6.3:2:30310)
    at t (https://ukpoms.org.uk/core/assets/vendor/jquery/jquery.min.js?v=3.6.3:2:30612) undefined`

`Uncaught TypeError: indiciaFns.cookie is not a function
    at indicia.locks.js?v=9.5.9:70:16
    at HTMLDocument.<anonymous> (indicia.locks.js?v=9.5.9:76:4)
    at e (jquery.min.js?v=3.6.3:2:30310)
    at t (jquery.min.js?v=3.6.3:2:30612)`

`Uncaught TypeError: indicia.locks.initControls is not a function
    at HTMLDocument.<anonymous> (add-1km-samples:1032:15)
    at e (jquery.min.js?v=3.6.3:2:30310)
    at t (jquery.min.js?v=3.6.3:2:30612)`

**Comment by andrewvanbreda** [comment]
@kitenetter 
Ok, thanks for those logs. 
Those would certainly cause problems. I will look into this.

**Comment by kitenetter** [comment]
Chrome has just done another minor update and is now showing "Version 114.0.5735.199".

**Comment by andrewvanbreda** [comment]
Hi @kitenetter 
Thanks. Don't worry about reporting further updates unless you notice it fix it.

**Comment by johnvanbreda** [comment]
I am seeing no errors on this page, using Chrome Version 114.0.5735.134 on Windows 11.

Maybe worth masquerading as the same user as Martin @andrewvanbreda?

**Comment by andrewvanbreda** [comment]
@johnvanbreda @kitenetter 
Thanks John for the info.
Martin I tried masquerading as the account with you name on, but that account doesn't actually have rights to see the page you are mentioning.
Which user account are you using?

**Comment by kitenetter** [comment]
I was using "PoMS support" which has admin rights.

**Comment by kitenetter** [comment]
I've just masqueraded as a normal user with 1 km square survey permissions. In that case the tabbing between fields is working correctly, but the map is not displaying.

When I go back to the "PoMS support" account the map is not visible, and the tabbing between fields is not working.

**Comment by andrewvanbreda** [comment]
Hi @kitenetter @johnvanbreda
My new computer has just arrived, so am able to check the latest Google Chrome.
version 114.0.5735.198
This is running fine even with that user.
It is running in Mac OS though.

Martin: 
Does it do the same on another Windows machine?
Does it do the same if your browser's caches are cleared?

John has checked and said it is fine on Windows 11.
Perhaps Martin, if you could answer those questions above, then one thing could do is ask if John could check the PoMS Support user on Windows 11.
(I will get myself access to Windows 11 for future, but can't do that right now)

On the plus side, although this is hard to track down, it means users won't be seeing this problem widespread either.

**Comment by johnvanbreda** [comment]
Checked again this morning (Version 114.0.5735.199 (Official Build) (64-bit)) masquerading as the PoMS Support login. The map and tabbing both work fine and there is nothing in the console.

**Comment by andrewvanbreda** [comment]
@johnvanbreda 
Thanks for checkling.
Martin are you able to check then if it happens in these situations.
@kitenetter 
Does it do the same on another machine similar to your own, does that have problem too?
Does it do the same if your browser's caches are cleared?

**Comment by kitenetter** [comment]
Can no longer see any problems with Chrome. Closing.
