### ISSUE TITLE
Switching to Welsh doesn't show flag correctly

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/PoMS#157]
@kitenetter 
Dunno if this is something you'd want to get Biren to look at, look what happens if switch to Welsh language.
Flag failing to show, and specifically on Chrome I noticed it puts in a missing icon placeholder.

![Screen Shot 2023-06-27 at 12 02 15](https://github.com/BiologicalRecordsCentre/PoMS/assets/2463614/a16cb749-2555-4637-868b-b3be8764bc69)

**Comment by kitenetter** [comment]
@BirenRathod what controls the small flag icons next to the language names? Is it easy to fix this?

**Comment by BirenRathod** [comment]
@kitenetter it needs an icon of that flag. Most countries' icons are included in the language module but not Welsh. There are some missing for other countries too. so if I find the icon, I will add it. Adding an icon is easy but finding one is a bit difficult.

**Comment by BirenRathod** [comment]
@kitenetter Welsh flag updated on both these sites ukpoms & fitcount.
