### ISSUE TITLE
Improve Language Switcher visually

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/PoMS#16]
1. Language Switch looks wrong with UKBMS theme.
2. Need Welsh flag for language switcher. Note this can be any royalty free image, however note that as David correctly pointed out, why is this not working automatically. Other sites it is not necessary to specify the flag.

**Comment by andrewvanbreda** [comment]
2. Flag fixed. Languageicons module doesn't have an icon of its own for Welsh, so have made one

**Comment by andrewvanbreda** [comment]
@kitenetter @DavidRoy 
I have put this on one line so looks better than it did.

However, can you let me know where you want this to go on the page asthat will need a little work as will need to create a new theme region for it to go in (otherwise it does funny things like appear on top of menus).
I don't want to do that then find it isn't in the place you want.

**Comment by DavidRoy** [comment]
@andrewvanbreda better but I think it should be top right, like this on https://butterfly-monitoring.net/....
![image](https://user-images.githubusercontent.com/2699478/110848350-e6e64f00-82a5-11eb-9b39-f6ad80b3204a.png)

**Comment by andrewvanbreda** [comment]
@DavidRoy 
Ok thanks. Yes I realise it can't stay where it is.

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod 

Need to get the Language Switcher to be in the top-right position like the butterfly monitoring.

In order to do this I think I need to create an extra region call Top Sidebar that is present on the butterfly site but not PoMS.
Trying to read about this on the internet, from what I can work out, the regions are defined in a .info.yml file in the theme folder.
Is this configuration something that you can simply be copied over from butterfly monitoring? or is it more complex than that. Sorry am not familiar with setting up regions for blocks, so feel free to tell me I am talking nonsense :D

Thanks for any help/information you can provide

**Comment by BirenRathod** [comment]
@andrewvanbreda 
I added top bar on butterfly while ago and on fit count about two days ago. So same again I have added on PoMS today.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Thanks Biren. That looks really good now. I think as the flag icons are a bit bigger now I will try and add some higher resolution ones at some point, but I don't think this issue needs to be left open anymore.

**Comment by BirenRathod** [comment]
@andrewvanbreda No problem. When ever you get chance please update the welsh flag to higher resolution one.
