### ISSUE TITLE
Any issues with Drupal 10 website

### ISSUE THREAD

**Issue by robin-hutchinson** [BiologicalRecordsCentre/PoMS#160]
This issue is for recording any issues found while testing the PoMS website in Drupal 10

http://test-ceh-ukpoms-d10.pantheonsite.io/

**Comment by kitenetter** [comment]
The [flower-insect charts page](https://[test-ceh-ukpoms-d10.pantheonsite.io/flower-charts](https://test-ceh-ukpoms-d10.pantheonsite.io/flower-charts)) produces an error: "The website encountered an unexpected error. Please try again later."

May need input from @burkmarr?

**Comment by BirenRathod** [comment]
@burkmarr The error comes from this page -> Error: Call to undefined function drupal_get_path() in loadLibs() (line 400 of /code/web/modules/custom/brc_vis/brc_vis.module).

**Comment by burkmarr** [comment]
@kitenetter and @BirenRathod - I will hopefully look at this tomorrow. Struggling to set a new laptop at the moment.

**Comment by BirenRathod** [comment]
Thanks, @burkmarr. looking forward too. please check if that is the same issue on the new iRecord Drupal 10 website.

**Comment by burkmarr** [comment]
@BirenRathod - I'm failing to start any of the Drupal 10 websites with Lando in my development environment. As well as this one (UKPOMS) I've also tried with the Drupal 10 versions of UKBMS and iRecord. Also copying in @JimBacon in case you have any insights.This is the error I see:

![image](https://github.com/BiologicalRecordsCentre/PoMS/assets/9275178/8e443553-3a92-469a-8146-bb4ed81a7edc)

@JimBacon - do you have any insights Jim?

**Comment by BirenRathod** [comment]
@burkmarr As it suggests run composer update and that should update the files of composer. 
Basically, you need to check or update the files of the composer where it has been installed. This will be in /usr/local/bin/composer folder. These are basically dependencies files. 

Also, try updating pantheon-system/upstream-manager by using composer.

**Comment by burkmarr** [comment]
I managed to get it running locally by running `lando composer self-update 2.3.0` and `lando composer update` before running `lando start`.

**Comment by kitenetter** [comment]
Just logged in to the D10 site, with user "PoMS support", and got this error:
`There was an SQL error: ERROR: duplicate key value violates unique constraint "ix_unique_email_address" DETAIL: Key (email_address)=(poms@ceh.ac.uk) already exists. - UPDATE "people" SET "email_address" = 'poms@ceh.ac.uk' WHERE "id" = '103163'`

However, it has allowed me to log in and seems to be functioning okay.

**Comment by kitenetter** [comment]
Flower-insect charts seem to working well now.

Tried to test the log-in process but the captcha is not displaying an image:
![image](https://github.com/BiologicalRecordsCentre/PoMS/assets/16039111/e3f0e44d-bea4-47f5-9f7a-10c946eede00)

**Comment by kitenetter** [comment]
Biren has gently informed me that I am way behind the times, and that we moved the main website to Drupal 10 some time ago! Closing.
