### ISSUE TITLE
Captcha image not appearing

### ISSUE THREAD

**Issue by robin-hutchinson** [BiologicalRecordsCentre/PoMS#161]
On the FIT Count website to reset passwords, the captcha image doesn't appear:

![image](https://github.com/BiologicalRecordsCentre/PoMS/assets/95474755/601f4975-09a7-46cc-be6b-8ff5128305bb)

**Comment by BirenRathod** [comment]
@robin-hutchinson That has been implemented now.

**Comment by robin-hutchinson** [comment]
Thanks Biren!
