### ISSUE TITLE
Reports for Consultant Entomologists to download their own insect data

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/PoMS#162]
Development as per title detailed in emails received by @kitenetter

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod 
Would you be able to pull these 2 reports whever you get a chance please.
Thanks
	reports/projects/PoMS/my_ukpoms_insect_data_for_experts.xml
	reports/projects/PoMS/my_ukpoms_insect_data_for_experts_mapping.xml

**Comment by BirenRathod** [comment]
@andrewvanbreda Sorry for the late response to this. Those reports were updated last night.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Great thanks :)

**Comment by andrewvanbreda** [comment]
Hi @kitenetter 
How about this or similar?
https://ukpoms.org.uk/my-pan-trap-occurrences-insect-species-data

I guess having checked this, I have only come up with one question.
Currently the system will return occurrences the current user created, however that is different to the identified field.
I assume you mean users to be able to download occurrences they created, even when the Identified By is different.
Example is Occurrence ID
23445879
This has been created by Ivan, but is Identified By yourself, so is appearing in Ivan's report.

**Comment by kitenetter** [comment]
@andrewvanbreda this looks great, just what is needed. I will set the default year to 2023 and add it to the menu. Closing.

**Comment by andrewvanbreda** [comment]
Problems reported to me by Robin.

1. Plant data from the main Pan Trap form is appearing on the report

2. On the enter species data page, the response of entering species and male/female is reported as being slow.

3. Click edit on a row is sometimes going to the main pan trap data entry form

4. "Is there a way to add the notes / free text section to the download as some specimens had notes re determination etc that might be of use but this seems to be missing now for the 2022 download? It seems to be in the occurrence comment field on the csv for my test of this years data."

5. "Direct data upload functionality?: Re uploading directly from our spreadsheets: is this functionality feasible / pending for this year? It would save a lot of time on the data entry part of the process as discussed at the QA (and I believe help reduce data entry errors).
If this will be available do you have a basic spreadsheet layout so I could make sure my data sheet is ready to go once I get into the IDing?"

**Comment by andrewvanbreda** [comment]
1. Fixed (limited by taxon groups as a report param)
2. Report back to Robin that I think this is internet connection issue, or perhaps the warehouse was busy at the time.
3. FIxed
4. Fixed, some hidden configuratino in the background was hiding report columns.
5. Have mentioned to Robin that I think Martin already mentioned to me that this might be a future possibility.

**Comment by andrewvanbreda** [comment]
Closing various improvments to the colomns shown to the user also.
Have contacted Robin to say work is complete
