### ISSUE TITLE
Home page displaying incorrectly

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#165]
I just edited some text on the home page, and the photos and logos are now displaying incorrectly, their proportions are distorted. I'm not certain whether this was a result of the text edit or whether it was already distorted before.

Can we restore it to the correct display?

**Comment by BirenRathod** [comment]
@kitenetter Do you know what has changed? the test site is fine. see here https://test-ceh-ukpoms-d10.pantheonsite.io/. Is it something I changed?

**Comment by kitenetter** [comment]
I edited the text for the sentence "The UKPoMS survey season in 2024 starts again on 1 April and runs to 30 September – please read on to find out how to get involved!" After saving that text edit, I noticed that the images had displaying incorrectly.

I am not absolutely certain that they were correct before the text edit but I think they were. I don't know why a text edit would cause the images to go wrong.

On the test site the images are shown (on the edit view) as "HTML object", but that label does not appear on the live site edit view. I don't know if that is significant.

**Comment by BirenRathod** [comment]
@kitenetter This has been resolved now.
