### ISSUE TITLE
Sample not displaying

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#167]
Sample ID 26697643 is a 1 km square survey sample that has been entered by one of our volunteers. As far as I can see the sample was entered correctly, and it is visible on the user's "My pan-trap results" page. However, it is missing from the "Select pan-trap samples to add insect BYCATCH data", and if I run my normal SQL query to extract the data from the warehouse this particular sample is excluded.

@andrewvanbreda can you suggest any reason for this?

**Comment by andrewvanbreda** [comment]
Hi @kitenetter 
I think it is working, but the report filter must be set to 2023, it has been entered as a 2023 sample.

**Comment by kitenetter** [comment]
Thanks @andrewvanbreda I hadn't spotted the year, but that will explain it. I will edit the record.
