### ISSUE TITLE
Data not displaying on PoMS website

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#169]
Hi @andrewvanbreda the PoMS reporting pages are not showing any maps or data at the moment, at least not for me. Pages including:
https://ukpoms.org.uk/fit-counts-map
https://ukpoms.org.uk/select-samples-bycatch-data
https://ukpoms.org.uk/select-samples-species-data

Are you seeing the same issue?

**Comment by andrewvanbreda** [comment]
Hi @kitenetter ,
It is noted here
https://github.com/BiologicalRecordsCentre/UKBMS-online/issues/367

I will put the site into maintenance mode.
Biren, the map problem seems to be on a few sites. Are you able to look into it? as that isn't the same as UKBMS out of date issue. I note also that SPRING still hasn't got its maps missing even  after the fix you applied to get rid of the error log message.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
This may change things.
I not on UKPoMS we are getting similar Drupal errors to UKBMS, but PoMS should be fine, it should be fine with iForm updates unlike UKBMS.
This means perhaps the route of the Drupal messages is not only because UKBMS is out of date with its iForm
https://ukpoms.org.uk/fit-count-target-flower-checking

Those errors are persisting after cache clearence.

![Screenshot 2024-12-02 at 11 32 55](https://github.com/user-attachments/assets/8a1b44a8-eb01-4bfb-8094-2f32add9b61a)

**Comment by BirenRathod** [comment]
@andrewvanbreda the error on above page suggest that there is a js error of this function -> Uncaught TypeError: jQuery(...).indiciaFootableReport is not a function.

I have uninstall the toolbar module on ukpoms & dev ukbms which has stop generating the durpalmenuHorizontal error. And that suggest thet the map error is not relate to that. But  they both generate the same above error of jQuery. 

I think this suggest that it needs changes in media folder and Please involve @johnvanbreda in it.

**Comment by andrewvanbreda** [comment]
@BirenRathod
OK I will send him an email as I don't know anything about the development of this.
I do note that UKBMS dev does still throw lots of other Javascript errors when trying to use the pages.

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod ,

I have finished checking a cloned version of the site from about a week or 2 ago with iForm update, and it looks OK.
So I think we can do a UKBMS full iForm update if needed.
Note there is some risk to this, as I can't test some elements of the site (such as site assignments).
Gary was going to take a look at this, but I think this is getting urgent enough not to wait for him.

However, as noted in my email to you, doing that will not fix the other errors being experienced this morning. Things like missing maps/Drupal Javascript errors are occurring on other sites such as UKPoMS. The errors also still occurred on my UKBMS multidev site even after it was manually iForm updated.

I suggest getting those problems fixed on all sites before we do an iForm update on UKBMS though......unless we need to iForm update UKBMS to get it working.

If you need help from John, I might suggest contacting him directly (although I did mail him).

Note that the following sites are all in maintenance mode at the moment

UKBMS
SPRING
UKPOMS

**Comment by andrewvanbreda** [comment]
Sorry that note should of gone in the UKBMS github thread, although it is still relevant here so I will leave it here and paste into other thread also

**Comment by BirenRathod** [comment]
@andrewvanbreda  thanks for these update.

I suggest we fix issues related to the map first. I already emailed to @johnvanbreda about it.

**Comment by johnvanbreda** [comment]
There seem to be 2 copies of jQuery on the pages which have problems.
E.g. on https://ukpoms.org.uk/enter-fit-count there is an error because `$.fn.indiciaMapPanel.georeferenceLookupSettings` is not defined. However, `jQuery.fn.indiciaMapPanel.georeferenceLookupSettings` is defined. As jQuery and $ are supposed to be synonyms, these should be identical.

I can see a comment in the Pantheon logs on UKBMS (I don't have POMS access) which is "jquery library upgraded in ukbms theme.". Why is there a copy of jQuery loaded by the theme? Shouldn't we be using the one provided by Drupal?

**Comment by BirenRathod** [comment]
@johnvanbreda the jQuery added in the theme folder by the theme developer. Not sure why did they add it? but I will remove it and see if theme works fine.

**Comment by BirenRathod** [comment]
@johnvanbreda I have removed the jQuery from the theme on https://dev-brc-ukbms-d10.pantheonsite.io/

**Comment by BirenRathod** [comment]
@andrewvanbreda fixes have been done on poms & spring sites now.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Thanks for doing that, although I am finding a problem with the menu on both those sites. Clicking the the "Menu" square in the top right doesn't expand it.

Cache clearing and browser switching hasn't helped. It isn't reacting to any clicks

SPRING has this in the drupal logs in case that is relevant
User warning: The following theme is missing from the file system: jquery_ui_draggable in Drupal\Core\Extension\ExtensionPathResolver->getPathname() (line 63 of /code/web/core/lib/Drupal/Core/Extension/ExtensionPathResolver.php)

**Comment by kitenetter** [comment]
@andrewvanbreda @BirenRathod is there any news on reinstating the menu links?

**Comment by BirenRathod** [comment]
@kitenetter I was updating the site with my code changes since morning and will be finishing soon.

**Comment by BirenRathod** [comment]
@kitenetter just finished now.

**Comment by kitenetter** [comment]
Thanks @BirenRathod and @andrewvanbreda - as far as I can tell the menus and the report pages are now back to normal. Closing.
