### ISSUE TITLE
PoMS logo for website theme

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/PoMS#18]
https://test-ceh-poms.pantheonsite.io/

Replace UKBMS logo with PoMs logo
@kitenetter to add logo file to this issue
@BirenRathod to add to site

**Comment by kitenetter** [comment]
Logo options:

PoMS_Logo_WithoutStrap_Positive_Black
![PoMS_Logo_WithoutStrap_Positive_Black](https://user-images.githubusercontent.com/16039111/110043972-468da900-7d40-11eb-800a-e1819875e8ff.png)

PoMS_Logo_WithoutStrap_Positive_WhiteOut
![PoMS_Logo_WithoutStrap_Positive_WhiteOut](https://user-images.githubusercontent.com/16039111/110043976-47263f80-7d40-11eb-9224-83d16763481f.png)

PoMS_Logo_WithStrap_Positive_Black
![PoMS_Logo_WithStrap_Positive_Black](https://user-images.githubusercontent.com/16039111/110043978-47bed600-7d40-11eb-87ac-b802440b9106.png)

PoMS_Logo_WithStrap_WhiteOut
![PoMS_Logo_WithStrap_WhiteOut](https://user-images.githubusercontent.com/16039111/110043981-48576c80-7d40-11eb-9c83-c5d7bab75624.png)

I imagine we will want to have the strapline on the home page?

Also available as .jpg or .eps - let me know if this is needed.

The three insects (i.e. without the text "PoMS") are also available as a separate image.

**Comment by BirenRathod** [comment]
Thanks @kitenetter. No strap line needed. This should be fine. Also I need three insects without text for icon.

**Comment by kitenetter** [comment]
PoMS_Logo_IconOnly_WhiteOut
![PoMS_Logo_IconOnly_WhiteOut](https://user-images.githubusercontent.com/16039111/110045102-1941fa80-7d42-11eb-901d-8949e3c5fe11.png)

PoMS_Logo_IconOnly_Black
![PoMS_Logo_IconOnly_Black](https://user-images.githubusercontent.com/16039111/110045104-1a732780-7d42-11eb-82c6-5e967a79df6d.png)

PoMS_Logo_IconOnly_Twitter
![PoMS_Logo_IconOnly_Twitter](https://user-images.githubusercontent.com/16039111/110045106-1a732780-7d42-11eb-94fc-deaed3e86f37.png)

**Comment by BirenRathod** [comment]
Thanks, @kitenetter

**Comment by BirenRathod** [comment]
@DavidRoy Logo and icon has uploaded now.

**Comment by kitenetter** [comment]
Closing.
