### ISSUE TITLE
Background image for home page

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/PoMS#19]
Currently has a butterfly
@kitenetter to provide image file for background
@BirenRathod to replace current image

**Comment by BirenRathod** [comment]
@kitenetter I need about six images min if possible. the size will be 3504 x 2360

**Comment by kitenetter** [comment]
Most of my photos are a bit smaller than that. Do you want me to resize them to exactly 3504 x 2360 pixels?

And are we using all six (e.g. in a scrolling banner) or do you just need a choice for a single background photo, as shown with the butterfly on the test site?

**Comment by kitenetter** [comment]
Six photos here:
https://1drv.ms/u/s!Ak5pqPfqMN7VhcQ8WIIUc7D2APMgfg?e=8l8wOG

**Comment by BirenRathod** [comment]
Thanks @kitenetter.  The background images hard coded, so I do need six photos at least. Otherwise I have to make six copies of one photos. Anyway thanks again.

**Comment by DavidRoy** [comment]
@BirenRathod this is only a temporary design until Steve Dixon can work on the site.  so please use the images as best you can but some repetition of images is fine.

**Comment by BirenRathod** [comment]
@DavidRoy All background images uploaded.

**Comment by CCarvell** [comment]
@kitenetter @BirenRathod sorry to come to this late - thanks for the photos Martin!
It would be great if we could please use the two images of Nadine's that have been used a lot for PoMS to date, to keep some recognisable identity. These are the versions that I have saved - some are also on here: 
https://drive.google.com/drive/folders/13FETxdP-UVEYK8D027d0tA7It8D6tOrH

Are these of suitable size? 
![solitary bee_Andrena nitida_Dandelion_Nadine Mitschunas](https://user-images.githubusercontent.com/44494345/110629495-1f016b00-819c-11eb-8c21-6ca8537daa01.jpg)
![Andrena haemorrhoa_apple_Nadine Mitschunas](https://user-images.githubusercontent.com/44494345/110629772-7a335d80-819c-11eb-9e38-20fd62949f81.jpg)

**Comment by BirenRathod** [comment]
@CCarvell 
Thanks for images. I have uploaded those images. you need to clear the cookies from your browser to see those changes.

**Comment by CCarvell** [comment]
@BirenRathod thanks - sorry but can you please tell me how to clear the cookies from my browser?!

**Comment by BirenRathod** [comment]
@CCarvell On Chrome, you can click on three dots at top right hand corner -> More tools -> clear browsing data.  There will be popup windows appears showing options selected. This depends on your browser settings. One important one to select checkbox is "Cached images and files" and press "Clear data" button.

**Comment by DavidRoy** [comment]
@CCarvell you'll have to check that 'clear images' is also ticked

**Comment by kitenetter** [comment]
I think we have now dealt with the photos - closing.
