### ISSUE TITLE
Privacy policy & T&Cs

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/PoMS#2]
Required on website.

Also needs to integrate with FitCount app privacy and T&C
https://github.com/NERC-CEH/fit-count-app/issues/2

**Comment by kitenetter** [comment]
Privacy Notice:

[PoMS Privacy Notice v1.docx](https://github.com/BiologicalRecordsCentre/PoMS/files/6108563/PoMS.Privacy.Notice.v1.docx)

I have given the URL for this policy as:
http://ukpoms.org.uk/privacy-notice

[The FIT Count app has a similar, but separate, Privacy Notice.]

**Comment by DavidRoy** [comment]
@BirenRathod can you create a page for this on https://test-ceh-poms.pantheonsite.io/ and add a link in the page footer template

**Comment by kitenetter** [comment]
@BirenRathod I've found a typo in the Terms of use - can you give me editing permissions so that I can correct it?

**Comment by kitenetter** [comment]
Terms of use:

[PoMS Terms of Use v1.docx](https://github.com/BiologicalRecordsCentre/PoMS/files/6109141/PoMS.Terms.of.Use.v1.docx)

I have given the URL for this policy as:
http://ukpoms.org.uk/terms

**Comment by BirenRathod** [comment]
@DavidRoy  & @kitenetter Terms of use and privacy pages have been added.

**Comment by kitenetter** [comment]
I think we can close this.
