### ISSUE TITLE
Move node.x.js files across from iRecord

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/PoMS#21]
As per issue title

**Comment by BirenRathod** [comment]
I have sent you zip files.

**Comment by andrewvanbreda** [comment]
Thanks Biren.

AVB note to myself: This is done, but I need to finishing testing all functionality when the site is more complete.
Also need to consider how to store these files safely as they were transferred using SFTP

**Comment by andrewvanbreda** [comment]
Closing this as have checked this, and the JS logic is active and running.
Further tests will be done on these pages naturally before go live.
