### ISSUE TITLE
Implement Transifex-Drupal module

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/PoMS#23]
There is a Drupal module for Transifex. 
David Roy sets up Transifex for website

Here are my notes:
See https://docs.transifex.com/drupal/drupal-8
 Modules required:
 	• https://www.drupal.org/project/tmgmt (includes Content Entity Source, Locales Sources)
 	• https://www.drupal.org/project/tmgmt_transifex
 	
 Copy over transifex module fixes from ABLE latest as this contains some patches.
 Enable translation management core, content entity source, locales 
 source, and transifex connector modules Translations > Providers > Transifex, edit it and add the API key.
 Set the remote language mappings to match the codes on the Transifex project page languages tab).
 Set "auto accept finished translations"
 In Indicia helper_config.php, set $delegate_translation_to_hostsite to 
 TRUE On the Configuration > Regional and Language > Content language and translation section, turn off translation of the Indicia params and url alias.

**Comment by DavidRoy** [comment]
@BirenRathod could you install these modules from the ABLE site (www.butterfly-monitoring.net)

**Comment by BirenRathod** [comment]
@DavidRoy Both modules available for PoMS. Just to enable them for the site.

**Comment by DavidRoy** [comment]
@BirenRathod are these modules copied over from the ABLE site, as John applied some patches

**Comment by BirenRathod** [comment]
@DavidRoy He didn't do any implementation in the module. Those modules rolled out from upstream.

**Comment by DavidRoy** [comment]
@johnvanbreda can you advise on how to connect up Transifex and Drupal through this module (e.g. is a key needed?) and whether we've pulled the right module across.

**Comment by BirenRathod** [comment]
@DavidRoy Once it is enabled, the transfix module will create api key which Andy can use and store in helper_config file.

**Comment by BirenRathod** [comment]
Also @DavidRoy you need to register the site on this www.transifex.com website.

**Comment by BirenRathod** [comment]
@DavidRoy Sorry the api key, you will get it from transfix website once you register it. I don't have log in details about it.

**Comment by johnvanbreda** [comment]
For reference, I kept some notes last time I set this up:

> See https://docs.transifex.com/drupal/drupal-8
> Modules required:
> 	• https://www.drupal.org/project/tmgmt (includes Content Entity Source, Locales Sources)
> 	• https://www.drupal.org/project/tmgmt_transifex
> 	
> Copy over transifex module fixes from ABLE latest as this contains some patches.
> Enable translation management core, content entity source, locales source, and transifex connector modules
> Translations > Providers > Transifex, edit it and add the API key.
> Set the remote language mappings to match the codes on the Transifex project page languages tab).
> Set "auto accept finished translations"
> In Indicia helper_config.php, set $delegate_translation_to_hostsite to TRUE
> On the Configuration > Regional and Language > Content language and translation section, turn off translation of the Indicia params and url alias.

Note in particular that the version of the Transifex module available for download is broken, but the one used in the ABLE/EBMS project should be OK.

**Comment by andrewvanbreda** [comment]
Am closing this to reduce number of open issues, as am sure this must now be covered by #55. Please reopen if I have misunderstood.
