### ISSUE TITLE
Website colour themes

### ISSUE THREAD

**Issue by CCarvell** [BiologicalRecordsCentre/PoMS#25]
@BirenRathod David has suggested that you might be able to edit the colours on the current PoMS web pages. 
I would like it to stand apart from UKBMS and NPMS if possible, and also mirror some of the look and feel of the FIT Count app, but bear in mind that we will work with Steve Dixon to improve the design interface after the initial soft launch.
Could the current dark navy blue (as per UKBMS) be replaced with the deep cerise pink within the FIT Count logo and app screen? We may still retain the blue/purple for some elements on some pages.
Could the orange lettering then also be replaced, either with the orange tone used in the app, or with the pink? Current use of dark blue/black text on the webpages looks fine.

@kazlauskis may have a specific colour palette that he used?
![01 App home screen](https://user-images.githubusercontent.com/44494345/110631589-97692b80-819e-11eb-825f-8d69bcecf877.png)
![05 App save count](https://user-images.githubusercontent.com/44494345/110631616-9df7a300-819e-11eb-913b-2356b4a37cd8.png)

**Comment by kazlauskis** [comment]
Primary colour (purple): `#ba107a`
Secondary colour (orange): `#f4a901`

**Comment by BirenRathod** [comment]
@kazlauskis Thanks for that. I have already implemented that.

**Comment by BirenRathod** [comment]
@CCarvell Also, I have implemented the color scheme through out the website. See if anything missing or noticed on it.

**Comment by CCarvell** [comment]
@andrewvanbreda these colour themes will be used by Steve Dixon in his design templates and we'll have them incorporated hopefully before initial launch of the site.

**Comment by andrewvanbreda** [comment]
@CCarvell 
That is fine, I just assigned this to you in case you hadn't seen Biren's comment. We probably need an issue label to indicate that no work is required on a particular issue at this time.

**Comment by kitenetter** [comment]
I think we can close this for now, pending Steve's design work.
