### ISSUE TITLE
Problem creating account on test website

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#26]
I think I've created an account but got an error message about the confirmation email:

![image](https://user-images.githubusercontent.com/16039111/110644116-af47ac00-81ac-11eb-88fc-0e4eccbdbd9d.png)

So I haven't been able to set a password.

Not sure if this is something for @BirenRathod or @andrewvanbreda ?

**Comment by BirenRathod** [comment]
@kitenetter I will check that. Also, I made you and admin. Do you have password or shall I reset it?

**Comment by kitenetter** [comment]
I don't have the password, so please reset it and let me know.

**Comment by kitenetter** [comment]
@andrewvanbreda has now sent me a password (apologies for confusion between this issue and a separate email thread!)

**Comment by andrewvanbreda** [comment]
Yes it is the emails on the site not working, not limited to the registration.

**Comment by BirenRathod** [comment]
@kitenetter  & @andrewvanbreda Unable to send email problem has been resolved now.

**Comment by kitenetter** [comment]
I think we can close this.
