### ISSUE TITLE
Use of logos

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#27]
How should we handle logos on the website, do we need to show all partners and all funders? I assume we do, and the options for displaying them include:
1. Full set of clickable individual logos in the pink footer bar on all pages
2. Full set of clickable individual logos in the pink footer bar on home page only (and/or on the About page)
3. Static graphics on the home page only (and/or on the About page) which is equivalent to what we currently have on the UKCEH website

@DavidRoy are you the admin for this repository? Please can you assign this to Claire, or set up the repository so that I can do so (not sure if I'm unable to do this due to limits on my role, or on Claire's).

**Comment by kitenetter** [comment]
For comparison, UKBMS has all logos in the footer on all pages (but only has four logos).

NPMS has nine clickable logos on the home page, but only has NPMS itself in the footer, so on most pages it is only the NPMS logo that is displayed.

**Comment by kitenetter** [comment]
Discovered that I can tag @CCarvell but cannot assign tasks to her.

**Comment by DavidRoy** [comment]
@CCarvell needs to accept her invite....sent several days ago ;-)

**Comment by CCarvell** [comment]
Invite now accepted from Friday, apologies! Great work Martin thank you.

Logos - we do need to show all partner and all funder logos.

Can we try Option 2: Full set of clickable individual logos in the pink footer bar on home page and on the About page. 
Also leave the links within the "Who we are" section".
For all other pages can we just have the PoMS logo in the pink footer bar, like NPMS?

Do we need to ask some/all Partners for 'transparent background' versions of logos, or do we already have these for BC, BTO etc?

**Comment by kitenetter** [comment]
Info from Paulette on what we need from partners/funders:
"It will depend on the colours within each specific logo if you need whiteout versions or not, but you will need transparent for all of them and should ask for png versions."

I will start contacting partners/funders for suitable logos.

@BirenRathod Can you set up the PoMS logo so that it appears in the pink footer bar for every page? Here is the white-out version of the logo, which I think is what we will need:

[PoMS_Logo_WithoutStrap_Positive_WhiteOut.zip](https://github.com/BiologicalRecordsCentre/PoMS/files/6129224/PoMS_Logo_WithoutStrap_Positive_WhiteOut.zip)

@BirenRathod can you also confirm that we will be able to have a custom footer strip for the home page and the About page, so that we show all the partner logos on those two pages?

**Comment by kitenetter** [comment]
Given time constraints at the moment, I've used a stopgap measure, which is to add all partner and funder logos as a static image on the Home and About pages.

I suggest we revisit this when it is possible to get Steve Dixon involved with the design. I will obtain copies of logos from partners/funders in preparation for that.

@BirenRathod if you can add the white-out PoMS logo to the footer for all pages that would be great. No need to do anything different for the Home and About pages at the moment.

**Comment by BirenRathod** [comment]
@kitenetter I have added white logo of POMs on the footer. Also added copyright text and links of terms use & privacy aligned.

@kitenetter  I can set up the clickable logo footer for home & about page. if you want me to do that, I can go ahead and do that.

**Comment by DavidRoy** [comment]
@kitenetter I've been thinking whether the main PoMs logo top-right should be smaller?  Also it could and in the same pink colour as other parts of the site

**Comment by kitenetter** [comment]
@DavidRoy do you mean top-left? If so I agree it could be smaller and it would be good if the top white strip was less deep. Not sure about the colour but have no objection to using the dark pink.

**Comment by DavidRoy** [comment]
@kitenetter yes, I meant top left, sorry!
@BirenRathod can you reduce the size of the main PoMs logo by 50%

@CCarvell do you have a view on dark pink or black for main top-left logo?

**Comment by BirenRathod** [comment]
@DavidRoy , @kitenetter PoMs logo has been reduced in size.

**Comment by BirenRathod** [comment]
@kitenetter 
I have added the reference logo footer on home page and about page. The only missing logo is welsh gov. If you have can you pass it to me. 

Let me know about ref logo footer, if you need any amendments.

**Comment by kitenetter** [comment]
Thanks @BirenRathod but the problem is that we do not have the correct set of logos available - the ones we have are a mix of transparent and white backgrounds and look rather messy on the shaded colour background. So I think we should leave them out of the footer for now.

@DavidRoy @CCarvell to confirm.

**Comment by BirenRathod** [comment]
@kitenetter If the white background is the only concern, I can create the transparent, so they look identical. But I still need welsh logo.

**Comment by BirenRathod** [comment]
@kitenetter They are all now without white background. Please clear the cookies from browser if can't see that.

**Comment by CCarvell** [comment]
@BirenRathod I can see all the logos you have created with transparent background - thanks - but the University of Leeds is all white so doesn't look right. Attached is the version we have for PoMS.
![University of Leeds](https://user-images.githubusercontent.com/44494345/111157073-5bfba200-858e-11eb-9eeb-870bac845535.PNG)
Funders logos - attached is the Welsh Gov logo that we hold. 
But I think we should display all funder logos in equal size ratio, so that SG and Daera are not both smaller. If we can fix this and have all logos transparent against the pink footer, great - but if not then leave the temporary solution provided by Martin above.
![New WG logo_approved for website](https://user-images.githubusercontent.com/44494345/111157137-703f9f00-858e-11eb-9d31-99fbc1734c23.jpg)

@DavidRoy @BirenRathod main top left PoMS logo is better thanks. 
I don't have a strong view about black vs dark pink. Perhaps leave the black here? What I do note is that the current version is not totally clear/ high quality on my screen. 
@kitenetter do we need to supply Biren with an original EPS version of PoMS with strapline from this set?
P:\NEC06214_UK Pollinator Monitoring and Research Partnership\Logos\PoMS_Logo_new\PoMS_Logo_new

**Comment by BirenRathod** [comment]
Thanks, @CCarvell for providing both these logos, much needed.

Also, about current version is not totally clear of PoMS logo, Can you share some screenshot, so I can understand more clearly. I can't see any problem on my screen.

**Comment by BirenRathod** [comment]
@kitenetter , @CCarvell All logos have been updated now.

**Comment by CCarvell** [comment]
@kitenetter given that Biren added all the partner and funder logos to the bottom of the Home and About pages, with live links, should we now remove your pink-framed image above this containing all the logos?
My one comment would be for @BirenRathod to remove the pink line that is between the two rows of partner logos. Leave the pink line separating the funders as they need to be clearly distinct.

**Comment by BirenRathod** [comment]
@CCarvell I will wait until Julian make changes to the theme otherwise I have to make those changes again. 
@kitenetter can remove pink-framed image as it is in the content.

**Comment by kitenetter** [comment]
Logos now displaying correctly within the new theme.

Closing.
