### ISSUE TITLE
Web page: About PoMS

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#28]
Web page now drafted at:
https://test-ceh-poms.pantheonsite.io/about

I have added the logos as static images, but we may need to change that, see #27. At the moment I only have logos on white backgrounds so they don't look very good on the shaded page.

@CCarvell to check that this text is up to date.

@BirenRathod I have tried to set this page up as a submenu item under the "Home" main menu, and it displays correctly on the About page itself, but does not display under that menu when I go back to the Home page.

**Comment by BirenRathod** [comment]
@kitenetter Can you see now?

**Comment by kitenetter** [comment]
Yes, thanks @BirenRathod the menu is now working on the Home page.

**Comment by kitenetter** [comment]
@BirenRathod I've hit the same menu problem again. I've added a top-level menu "Taking part" but from the home page it is not displaing the sub-menu "FIT Counts". Can you let me know what I need to do to make these menus work - the same situation will arise with a few more menus to add.

**Comment by BirenRathod** [comment]
@kitenetter It is now displaying the submenu. Well, you need me to that magic. :). you just need to check  "show as expanded" checkbox of the parent menu item.

**Comment by kitenetter** [comment]
Thanks @BirenRathod 
There are plenty of places where I need your magic, don't worry about that!

**Comment by CCarvell** [comment]
@kitenetter what's the best way for me to feedback comments on text? Edits in a separate Issue?

I think we should have a short section within the About PoMS page that links to each of the National Pollinator Strategies for Defra, WG, SG and Daera. They would each need to be referred to correctly by name!
Something like
"PoMS aims to engage individuals and communities in taking action for pollinators, and in helping provide evidence to the UKs four national pollinator strategies:
National Pollinator Strategy (England) https://www.gov.uk/government/publications/national-pollinator-strategy-for-bees-and-other-pollinators-in-england 
Scotland
Wales 
All-Ireland Pollinator Plan

**Comment by kitenetter** [comment]
@CCarvell I'm happy to pick up edits from you in whatever form is easiest for you to provide them - via github is fine, or in an email or Word doc. Will add the pollinator strategies in now.

**Comment by kitenetter** [comment]
Closing
