### ISSUE TITLE
Consider user of NPMS theme for project

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/PoMS#3]
There is initially a problem where NPMS is Drupal 7 and PoMS is Drupal 8

**Comment by BirenRathod** [comment]
@andrewvanbreda, @DavidRoy  
I have created PoMS theme identical to https://test-ukbms8.pantheonsite.io/. It does require to change background images. I could do once we get it.

**Comment by BirenRathod** [comment]
@andrewvanbreda The theme is available to test on test site. So when ever you get chance, you can test it.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Thanks Biren,

Have just switched to it. Will let you know how I get on. We will need to deal with it saying UK Butterfly Monitoring Scheme at some point, but that is fine for now.
Thanks

**Comment by BirenRathod** [comment]
@andrewvanbreda Yes, that is also part of changing images. So we need images, logo & icon.

**Comment by DavidRoy** [comment]
Closing this as we can pick up specific design changes as specific issues
