### ISSUE TITLE
Website images

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#30]
When using the Image upload options from the foot of the Basic page, it is not possible to add a caption before inserting the image.

After inserting the image, it is possible to tick a box to add the caption, but if I do that it loses the link to the previously uploaded image and I have to upload it again, which then loses the settings previously chosen for the original upload.

Can we add the ability to have a caption as part of the main Image upload?

**Comment by BirenRathod** [comment]
@kitenetter Please select "Basic html" from below text editor which should work. meanwhile I will sort out this problem for full HTML.

**Comment by kitenetter** [comment]
I think this is now working - thanks @BirenRathod 

Closing.
