### ISSUE TITLE
Contact form for PoMS

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#31]
We need to provide a contact form. This could be a standard contact form based on a user account.

The contact form needs to go to poms@ceh.ac.uk

That email address is currently registered to the "admin" account.

The "PoMS support" account is registered to my own CEH account.

In some ways it would be best if the "PoMS support" account was seen as the main contact point for PoMS, and for that account to be linked to poms@ceh.ac.uk

But that means we'd have to find a different email address for the "admin" account.

Which of these options works best:
1. Keep "admin" account linked to poms@ and use the contact form for "admin" as the contact point for website enquiries
2. Rename the "admin" account as "PoMS support" - do we have to have an account called "admin"?
3. Assign a different email address to "admin" - is it better to use a non-person-specific email? If so maybe we should use brc@ ?

**Comment by BirenRathod** [comment]
@kitenetter 
If you want to use poms@ceh.ac.uk for PoMS support, I can change admin to email to one of mine as I need for login purpose & drupal update purpose. 
Also, you can use poms@ceh.ac.uk for contact forms.

**Comment by BirenRathod** [comment]
or best we could use brc@ email address.

**Comment by kitenetter** [comment]
@BirenRathod if you are happy to use the brc@ address then let's do that. Is it okay for me to edit the email for the admin account or do you want to do that?

**Comment by BirenRathod** [comment]
@kitenetter I done it as it has required an admin password.

**Comment by kitenetter** [comment]
Contact form now set up:
https://test-ceh-poms.pantheonsite.io/user/12/contact

We will presumably need to check which user ID needs to be allocated to this when the website moves from test to live.

Closing for now.
