### ISSUE TITLE
How-to videos within website x3

### ISSUE THREAD

**Issue by CCarvell** [BiologicalRecordsCentre/PoMS#34]
Note NEW videos have been prepared in English and Welsh - Claire to get Paulette to upload to YouTube and provide the new links. 
Martin? to embed within webpages and/or provide Welsh versions to Andy/ Elen?

**Comment by kitenetter** [comment]
That is fine. The current videos can stay there as placeholders, and any text surrounding them can be translated. The new videos will just require an edit to the links, and can be updated as soon as available.

Note that we also have the 2020 webinar video which won't be available in translation, and is presumably best edited out of the Welsh version of this page:
https://test-ceh-poms.pantheonsite.io/reports

**Comment by kitenetter** [comment]
The videos include screenshots of the website recording forms etc. so we are currently waiting for the website design to be as close to final as possible before updating the screenshots in the videos.

**Comment by kitenetter** [comment]
New versions of the YouTube videos now updated on English and Welsh pages.

Closing.
