### ISSUE TITLE
Webpage text edits for Martin (using bold to highlight changes) v1

### ISSUE THREAD

**Issue by CCarvell** [BiologicalRecordsCentre/PoMS#35]
**Home page:** 
Under Choose an Activity: 
Adopt a 1 km square and help us carry out a systematic survey of **insects and flowers**

**Latest news**:
Fine as is. We may be required to add gov links x4 for covid restrictions - and we may also need to continue to update the covid statement on the current UKCEH webpage IF we are only doing a Beta launch of the new website on 1st April. 

**About PoMS**
"aims to establish how insect pollinator populations are changing across **the UK**." 
I think we have to say the UK not Great Britain because Daera NI have now joined the PMRP.

**Comment by kitenetter** [comment]
Those edits done.

**Comment by kitenetter** [comment]
Closing this issue for now - if there are further edits please re-open (or add a new issue).
