### ISSUE TITLE
Indicia forms - FIT Count form

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#37]
Proposals to simplfy form - please can @CCarvell approve or not:

1. Remove the "how did you hear about" question (for reasons discussed for the app)
2. Remove the two user experience questions at the end ("Taking part was ...", "Carrying out was ...") (as they become repetetive for regular recorders, and we could capture similar feedback from a user questionnaire)
3. Remove the "Permission to contact" question (which we intend to ask as part of registration)

**Comment by CCarvell** [comment]
Agree with all 3 proposals, thank you Martin.

Can you find an appropriate place to flag the opportunity to add photos of examples of insects seen, as we discussed by email?

**Comment by kitenetter** [comment]
@andrewvanbreda we can remove the attributes from the recording form as listed in points 1-3 above. The attributes should stay in the survey (to hold the data collected in previous years) but can be removed from the form.

**Comment by kitenetter** [comment]
I think this is now done. Closing.
