### ISSUE TITLE
User registration form

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#38]
(Andy: please reassign to Biren if this is something that he needs to do.)

Remove the "Picture" upload option (not needed).

Remove the "Personal contact form" option (not needed).

Hide the "Indicia Warehouse User ID" so that the user is not presented with a box to fill in.

Remove "PoMS Survey Hear".

Add a mandatory question:
- I am happy for you to contact me in connection with PoMS: yes/no

With help text:
- We would like to contact you via email occasionally to provide updates on the PoMS project - if you are happy for us to do so you please confirm here (we will not pass your email on to third parties)

Add a mandatory tick box:
Confirm that you are aged 13 or over

With help text:
You must be 13 or over to register on this website.

Add a view of the Terms of Use, with a mandatory tick box to confirm acceptance.

See iRecord registration form for examples of these additions:
https://www.brc.ac.uk/irecord/user/register

**Comment by andrewvanbreda** [comment]
Hi @kitenetter 
Yes I am aware of some of these issues, although the detail of exactly what you want is useful.
The naming of the "PoMS Survey Hear" field is actually deliberate at the moment to try to get it to sync with the Warehouse.

**Comment by CCarvell** [comment]
@andrewvanbreda @kitenetter I have been trying to create a User account and Reset my password, and have stalled at the Resolve Multiple Users page: screen shot below. is this a common problem?
That said, I can now view the Enter FIT Counts and FIT Counts map pages to review for translation - perhaps that is due to a development from Biren?

![image](https://user-images.githubusercontent.com/44494345/112039929-7b6d6e80-8b3c-11eb-9c0d-4dcd9700d432.png)

**Comment by andrewvanbreda** [comment]
Hi @CCarvell 
I just fixed the unregistered user permissions. I will review the registration situation, no need to raise another issue for that as we have some open ones to do with registration. What you are seeing there looks like it maybe be a server failure (possibly one-off) rather than a fundamental problem with the site, I will run through the registration when I get a chance.

**Comment by andrewvanbreda** [comment]
@kitenetter 
I have checked this, and both English and Welsh registrations work.

There are 3 problem remaining though (number 1 is for me, 2 is for your translator, 3 for me after you reply)

1. The Over 13 box is not currently mandatory.
This is hard than you might think as off is valid to the computer and I can't see easy way to add code to this page, checking with John.
Actually we could make this as part of the Terms Of Use checkbox, as that checkbox is mandatory as part of the module.

2. The Welsh registration process still has lots of English in it. I noticed following

"First name" 
"Last name" 
"Your identification experience" (including options)
"Are you happy to be contacted?"
"yes"
"no"
"You must be 13 or over to register on this website"
"CAPTCHA"
"This question is for testing whether or not you are a human visitor and to prevent automated spam submissions."

"Image CAPTCHA"
"What code is in the image?" 
"Enter the characters shown in the image."
"Get new captcha!"

"Reset your password" (and probably associated mail)

"A welcome message with further instructions has been sent to your email address".

"Set password"

"This is a one-time login for <username>."
"Click on this button to log in to the site and change your password."

"Your user account is now linked to the central records database."
"You have just used your one-time login link. It is no longer necessary to use this link to log in." 
"Please change your password."


"Site language" 
"This account's preferred language for emails. This is also assumed to be the primary language of this account's profile information." (this might be removed on final site)

Also the the whole registration message is currently in English.


3. I have installed Terms Of Use
@kitenetter 
Do you want this to be the same as iRecord terms of use?.

**Comment by andrewvanbreda** [comment]
Actually there is a 3rd issue.
The terms of use needs setting up. I will deal with that.

**Comment by kitenetter** [comment]
Have sent registration wording to transifex for translation.

**Comment by kitenetter** [comment]
Registration wording with translations:

[PoMS website registration page translations.docx](https://github.com/BiologicalRecordsCentre/PoMS/files/6511138/PoMS.website.registration.page.translations.docx)

Adding translations to the Welsh registration form is not essential for launch.

For point 3, Terms of Use, we should use the PoMS website Terms of Use:
https://test-ceh-poms.pantheonsite.io/terms
https://test-ceh-poms.pantheonsite.io/cy/terms

**Comment by andrewvanbreda** [comment]
@kitenetter 
Have added this although not sure how to do the translation.
Might need a transfer import.
Also at the moment it is displaying in full on the user registration form, you are supposed to be able to link to it but that isn't working at sec.
You can also have it so it is initially collapsed, then you expand it, but that doesn't work well as the checkbox isn't select message also gets hidden in the collapse.

**Comment by andrewvanbreda** [comment]
@kitenetter Oh pleasant surprise, just realised it is clever enough to pick up the welsh translation

**Comment by andrewvanbreda** [comment]
@CCarvell 
I have added these translations to the system. However there is a problem, Drupal is not showing them, I do not know if this is a but in Drupal's translation system not showing translations for user fields. I will have to look into this.
I added the translation for "no" as "nac ydw" however the system already has a translation for "yes" as "ie" so I have not changed this. Can you check this situation with your translator as google suggests there yes & no can be ie/na or ydw/nac ydw but the system can't support both of these at the same time.

**Comment by andrewvanbreda** [comment]
@kitenetter @CCarvell 
Hi,

Have corrected this situation now so the translations are working. Seems there is a separate setup for these translations actually as part of the fields themselves.
Only "I agree with these terms" remains untranslated. I cannot see how that can be done as the module controlling that does not have translation options.
However Biren is going to be deployed a Drupal 9 version of the site which uses a different module for terms and conditions which may resolve this.

So we need to wait for that before finishing this issue.

**Comment by BirenRathod** [comment]
@andrewvanbreda Yes, The legal module will allow to choose the language which has enabled for the site. And then you need to add translated script in it. I have already deployed on test site which you can check if you like.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Thanks for that info. I still have it on my task list to have a quick look at the Drupal 9 site

**Comment by andrewvanbreda** [comment]
@kitenetter 
Just looking at some of the issues.
Don't think this issue needs to be open anymore. The terms and conditions do have a translation.
There seems to a couple of untranslated strings such as "Accept Terms & Conditions of Use" which I guess simply don't have a translation.
Anyway, taking this one off my task list.
