### ISSUE TITLE
Log-in page

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#39]
On:
https://test-ceh-poms.pantheonsite.io/user/login

Change first box so that it allows either a user name or an email address.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Are you able to install the Drupal module needed for this

**Comment by BirenRathod** [comment]
@andrewvanbreda Already installed called "Login with email or username"

**Comment by andrewvanbreda** [comment]
@BirenRathod Ah ok, thanks. I will enable that when I get a sec later

**Comment by andrewvanbreda** [comment]
Done and tested
