### ISSUE TITLE
Setup homepage

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/PoMS#4]
Andrew van Breda to initially setup a placeholder homepage.
CEH to provide homepage content.

**Comment by andrewvanbreda** [comment]
Placeholder welcome page now on site. CEH to provide content.

**Comment by DavidRoy** [comment]
Require PoMs logo and background image for home page

**Comment by DavidRoy** [comment]
links to #18 #19
@kitenetter to provide home page text

**Comment by kitenetter** [comment]
Home page text now added to the existing home page.

I have not added any of the partner logos. Will these be added to the footer strip? I will supply logos to @BirenRathod 

As yet we don't have many controls in place for positioning and resizing images, e.g. I don't think I can control the text buffer around the image.

[Ignore my previous comment about not knowing how to set the page to be the home page, I had overlooked the possiblity of editing the home page itself, which is what I have now done :)]

**Comment by BirenRathod** [comment]
@kitenetter please pass it to me.  I will config the test bit, so you will be able to. actually for home page you just need to add  /home in the url and that is it.

**Comment by kitenetter** [comment]
@BirenRathod I have now edited the existing home page rather than trying to create a new one so I think all is well. Sorry for confusion.

**Comment by BirenRathod** [comment]
@kitenetter No problem. I think Andy has already created one. no need to take action. 
Also, on the home page, click on edit tab, if you right click on image, it will show you "image property" which shows caption checkbox, once you select and close the popup window , it will show text editor below the image where you can add label.

**Comment by BirenRathod** [comment]
@kitenetter If you add images through insert text box appears below the text editor,  it will allow you use zoom in feature too.

**Comment by kitenetter** [comment]
Thanks @BirenRathod but as usual I find the standard Drupal image options rather limiting. If I use the "Add a new file" option at the foot of the page it doesn't allow me to add alternative text to the image (as far as I can see).

The text on the page runs right up to the image, and we need to enable a buffer around the image. But perhaps that is something that can be tackled when we get to the design stage with Steve Dixon?

**Comment by BirenRathod** [comment]
@kitenetter I enabled the alternative text now. Sorry which text runs right up to the image?

**Comment by kitenetter** [comment]
@BirenRathod thanks for the alt text, that's fine now.

Images don't seem to have much if any buffer, e.g. on the Home page the right-hand side of the text runs up very close to the image:

![image](https://user-images.githubusercontent.com/16039111/110670318-2c7f1b00-81c5-11eb-8827-13b000d4ca1b.png)

In some of our Drupal websites (Drupal 7 ones I think) there is an image properties option that allows me to specify buffer spacing and image borders etc. but I can't find an equivalent here.

**Comment by BirenRathod** [comment]
@kitenetter I added spaces for images. Most of those Drupal 7's features have now gone. They are not ideal to use with responsive theme, so discontinue now.

**Comment by kitenetter** [comment]
@CCarvell I have added some covid text to the home page, based on the text used by BBCT. Are you happy for this to go ahead for translation or will it need clearance by our funders?
https://test-ceh-poms.pantheonsite.io/home

**Comment by CCarvell** [comment]
Please await funder/ Team approval of the covid guidance (as per email just sent ) before getting this translated

**Comment by kitenetter** [comment]
We will need to make final confirmation of text for translation on Monday if we possibly can. The home page issues discussed above are now dealt with - closing.
