### ISSUE TITLE
Indicia page - Edit FIT Counts

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#40]
This applies to:
- https://test-ceh-poms.pantheonsite.io/node/11 

This page should only be available to admins, who may need to edit any of the counts. (Users can edit their own counts via the "My records" page.)

Ideally, the columns to display are:
- Record ID
- Date
- Location
- Habitat
- Target Flower
- Photo of target flower
- Total number of insects

(If we can implement elastic for this page we may be able to give the user the choice of which columns to display.)

**Comment by kitenetter** [comment]
Have added "photo of target flower" to the above list.

**Comment by andrewvanbreda** [comment]
Again, I think this will be able to use the report I have committed this evening

**Comment by andrewvanbreda** [comment]
@kitenetter 
Am now wondering actually if this should just be one grid for any type of record which can be selected for editing (not just 1km).
This would mean adding the survey to the record grid.
This might be a lot cleaner as I realised we were starting to get so many record grids.

**Comment by andrewvanbreda** [comment]
Think this issue is now superseded by #48
