### ISSUE TITLE
Question - editing app records

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#41]
Will it be possible for website users (and admins) to edit records that were added via the app?

I'm guessing that this will need a custom editing form for the app records, as the app survey structure is slightly different to the website survey structure.

**Comment by andrewvanbreda** [comment]
@kitenetter 
Yes there is going to be a duplicate entry Public FIT Count page which will point to the same survey as the app.
I created the page, however I cannot finish setting it up as the data agreements aren't in place yet (or weren't last time I looked)

**Comment by DavidRoy** [comment]
@andrewvanbreda the agreements should now be in place
- agreement = 'Pollinator FIT Counts' setup on 134
- joining agreement = 'Pollinator Monitoring Scheme' joining agreement = 'Pollinator FIT Counts'

Let me know if this doesn't give you what you need

**Comment by andrewvanbreda** [comment]
@DavidRoy Thanks I will check this right now and let you know how I get on

**Comment by andrewvanbreda** [comment]
@DavidRoy Um.........I am going to speak to John about this as I can see some challenges with the way this is working. Will get back to you as soon as I have managed to have that conversation. By that I mean some problems that having an agreement might not be able to overcome.

**Comment by DavidRoy** [comment]
ask John if the agreements are setup correctly as I did them

**Comment by andrewvanbreda** [comment]
@DavidRoy Will do, the questions I have actually go beyond whether it is setup correctly, more generally a limitation there may be regarding having the app assigned to website 134 that I hadn't previously thought of.
The question is whether the app data entry editing form on the website will recognise a sharing agreement when the survey is selected for the form. Currently I am still unable to select the app survey for the form I setup. This is too involved for me to just check easily in the code I think.
Anyway I need to double-check before commenting further I think.

**Comment by DavidRoy** [comment]
yes, I'm unclear on this too.

**Comment by andrewvanbreda** [comment]
@DavidRoy @kitenetter 
I have spoken to John about this. I think there were two conclusions from the conversation.

1. In theory we should be fine, actually the situation is simpler than I thought. As the agreement is in place, app records should be editable on a data entry form that is using the non-app survey. So I don't need to select the app survey when setting up the data entry form.

2. The agreement is only partially setup at the moment.
I think 136 is shared with 134, but 134 also needs to be shared with 136. Also am not sure this agreement needs to be completely open as I don't think the app will be editing data from the website.

I also have this third question

3. Does the editing form for the app data on the website need to use different fields to the one for website data? (i.e. are the fields are the app different to the website form?)
If not, I think I can even use the same form.

**Comment by kitenetter** [comment]
@andrewvanbreda the attributes used by the app survey are all present in the website survey in terms of their meaning, but for some of them the app uses a different attribute ID for the same attribute:

**attribute | website_attr_id | app_attr_id**
Flower context | smpAttr:fk_1055 or smpAttr:1055 | smpAttr:fk_1543 or smpAttr:1543
Flower cover within quadrat   (PoMS) | smpAttr:fk_1052 or smpAttr:1052 | smpAttr:fk_1540 or smpAttr:1540
Flower type counted | smpAttr:fk_1054 or smpAttr:1054 | smpAttr:fk_1542 or smpAttr:1542
Habitat (PoMS) | smpAttr:fk_1048 or smpAttr:1048 | smpAttr:fk_1536 or smpAttr:1536
Number of floral units (PoMS) | smpAttr:1053 | smpAttr:1541
Other flower species | smpAttr:1051 | smpAttr:1539
Other habitat detail | smpAttr:1049 | smpAttr:1537
PoMS abundance | occAttr:666 | occAttr:868
Quadrat sun or shade | smpAttr:fk_1061 or smpAttr:1061 | smpAttr:fk_1549 or smpAttr:1549
Target flower species (PoMS) | smpAttr:fk_1050 or smpAttr:1050 | smpAttr:fk_1538 or smpAttr:1538
Time of count start (PoMS) | smpAttr:1056 | smpAttr:1544
Weather: sunshine (PoMS) | smpAttr:fk_1057 or smpAttr:1057 | smpAttr:fk_1545 or smpAttr:1545
Weather: wind (PoMS) | smpAttr:fk_1058 or smpAttr:1058 | smpAttr:fk_1546 or smpAttr:1546

The website survey has a few additional attributes that are not in the app survey, only two of which are significant I think:
Recorder Name
Recorder type (PoMS)

I don't understand how the app deals with Recorder Name, In the iRecord app I don't think it stores it as a custom attribute but I'm not sure how recorder names end up being displayed for app records - @kazlauskis to advise

The app is collecting Recorder type into the user profile, and I think we agreed that for version 2 of the app we would use the profile data to populate a Recorder type attribute in the survey, but again @kazlauskis will need to confirm.

So the two surveys are very similar and maybe the same form will work but I'm not sure if the variations in attribute IDs will necessitate a separate (but very similar) form for the app records.

**Comment by andrewvanbreda** [comment]
@kitenetter 
Thanks for this information. So yes two forms will be required which isn't a problem in itself. I think I would have to progress this further before commenting any further. Will let you know how I get on.

**Comment by kazlauskis** [comment]
I can add **Recorder Name** attribute to the `v1`. 

The reason the app uses different attribute IDs is because the PoMS ones weren't shared to other sites. If you prefer me to reuse the same IDs then I can toggle **Available to other Websites** to the PoMS attributes and reuse those in the app.

**Comment by andrewvanbreda** [comment]
@kazlauskis 
Yes I certainly think it would make it more elegant if we are able to do that now, espiecially for all the reports not to having  to take into account loads of other attributes. If you can, that would definitely be the way to go.
I assume there isn't any existing data that use those other attributes? (because we never had an app before)

**Comment by kazlauskis** [comment]
Thanks, I'll switch to website attributes then.

**Comment by kazlauskis** [comment]
I've done this now. This is the list of all common attributes shared between the website and app surveys:

<img width="284" alt="Screenshot 2021-03-12 at 15 55 16" src="https://user-images.githubusercontent.com/7383162/110964821-83166180-834b-11eb-9864-a5f75dcede6a.png">
<img width="199" alt="Screenshot 2021-03-12 at 15 56 21" src="https://user-images.githubusercontent.com/7383162/110964830-86a9e880-834b-11eb-9e03-07c4164ed172.png">

**Comment by andrewvanbreda** [comment]
@kazlauskis Thanks for the clear overview

**Comment by andrewvanbreda** [comment]
@DavidRoy @kitenetter 
As mentioned in our meeting, the test site wasn't working with App data, that has now been corrected (there was a silly typo from me in the page configuration causing that).
Please leave this issue open for now so I can test some of the logic, and that data from the app can be viewed & edited correctly on the website.

**Comment by kitenetter** [comment]
The editing form seems to be working for my for app records. It includes a mandatory location attribute, but location is not entered within the app, and as far as I can see the mandatory condition is being set by the form, not by the survey structure in the warehouse.

However, location name is mandatory for records entered via the website, and the same form is used for editing website records and app records, so we can't remove the location attribute from the form.

So the question is whether we want to drop the mandatory requirement for a location name when adding records to the website. Or alternatively we retain the mandatory requirement, but anyone editing an app record will have to enter a location name in order to save the edit.

My feeling is that we should retain the mandatory location name, and accept that this could be seen as a minor inconvenience for people editing app records. In other words, everthing is fine as it is and no action is required! (Apologies for thinking things through out loud!)

**Comment by andrewvanbreda** [comment]
@kitenetter 
Thanks for notes I will check them shortly. This area is coded but I have not actually tested it at all yet on the test site. I will look at what you said shortly.

**Comment by andrewvanbreda** [comment]
@kazlauskis @kitenetter 
Hi,
Just looking to test editing app records.
It looks like the data is appears on the website recording forms (mostly) ok.
But I noticed that the field "Name of place where the FIT Count was carried out:" is required on the website (location.name in the database) but seems to be empty in the app data.
Normally I would expect editing a record then clicking would save with no changes, but in this case it is complain a mandatory field is not filled in.
Any thoughts?
It either needs adding to the app or removed from being mandatory from website.

Actually I noticed a problem, the Welsh version of the page does not load the app data, but don't worry about that until I have investigate, I have raised that separately.

**Comment by kitenetter** [comment]
@andrewvanbreda @kazlauskis 

It is correct that the app does not currently store a location name. It's possible that it [may do so in future](https://github.com/NERC-CEH/fit-count-app/issues/69#issuecomment-838542717) but it won't be mandatory in the app.

I don't think this is necessarily a problem. We are not expecting many users to edit their app FIT Counts via the website, and if they do the will be prompted to fill in a location name, which is fine.

We could consider making the location name optional on the web forms if this turns out to cuase difficulties to users.

**Comment by kitenetter** [comment]
So I think we can leave this as it is for now. Please close if you agree.

**Comment by andrewvanbreda** [comment]
@kitenetter 
OK. 
Although it does currently leave me with the problem I can't test saving on the existing app records as I had wanted to save without altering the data.

**Comment by kitenetter** [comment]
You could test using one of the dummy records added prior to 30 April, e.g. those from recorder ViliusStankaitis

**Comment by kitenetter** [comment]
@andrewvanbreda I've just edited one of my own dummy app records and when I saved it asked for a location name, which I added, and then it saved okay, so it looks good to me.

However, the location box is picking up on the list of NNR names,a nd also the PoMS 1km square names, and offers them as an autocomplete, which is not really what we want to happen:

![image](https://user-images.githubusercontent.com/16039111/117832952-d6cef980-b26d-11eb-8ee6-cdb6b4ddfc0c.png)

**Comment by andrewvanbreda** [comment]
@kitenetter 
OK thanks for note. I will take a look at once have done some of the other task.

**Comment by andrewvanbreda** [comment]
@kitenetter 
Hi
Which page is this, this must be the Public FIT count one?
I am not even sure if this field is supposed to show a square at all (it doesn't for me). Isn't it just supposed to be free text?
Please let me know what this field should actually do.

**Comment by kitenetter** [comment]
@andrewvanbreda 
I started from the "My results" page, found one of my app-entered counts, and clicked on the edit button. That sent me to a page like this:
https://test-ceh-poms.pantheonsite.io/enter-fit-count?sample_id=14181012

The dropdown list appears when I start typing in a location name.

However, I've just realised that the recording forms on iRecord do the same thing. And I think it is the result of me being logged in as an admin - that's certainly the case on iRecord, and having just checked on PoMS it is also the case there. So you can ignore the problem with the autocomplete names, it isn't a problem at all.

I think we can close this?

**Comment by andrewvanbreda** [comment]
@kitenetter 
Leave open at the moment so I can check what this field is doing, it shouldn't be doing what it is doing (even if iRecord does it too)

**Comment by andrewvanbreda** [comment]
@kitenetter 
Am confused about this field, it appears to be an auto-complete but free text also.
Is this supposed to just be a free text field? (i.e. just text, not linked to an actual location database record)
Cheers

**Comment by kitenetter** [comment]
On iRecord it is a bit complicated. Basically it is a free-text field, but users have the ability to save sites into their own "My sites" list, and the sites in that list are offered as auto-complete options that can either be selected, or can be ignored and over-written with free text. If an option is chosen from the "My sites" list then I believe a link is stored between the sample ID and the location ID, but if it is free text then there is no location ID.

None of that functionality is needed for PoMS though!

**Comment by andrewvanbreda** [comment]
@kitenetter Ah ok, thanks for the explanation, I will consider what you have said in regards to existing data.

**Comment by kitenetter** [comment]
@andrewvanbreda 
I think this can be closed?

**Comment by andrewvanbreda** [comment]
Just double-checked, and yes the app data does appear to be loading correctly onto the website data entry form
