### ISSUE TITLE
Indicia page - My FIT Counts

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#44]
This applies to:
https://test-ceh-poms.pantheonsite.io/my-counts

Ideally, the columns to display are:
- ID
- Date
- Location
- Habitat
- Target Flower
- Photo of target flower
- Total number of insects

If possible, it would be good to have filter boxes at the top of the columns.

This page is currently showing all counts, needs to filter for just my counts.

This page currently has the standard iRecord tools for "Create a filter" but few of these are relevant to PoMS, and the column-head filter boxes will be sufficient. Otherwise we will have to make a lot of change to the "Create a filter" tools.

**Comment by andrewvanbreda** [comment]
This page can use the same report I have created for FIT Counts

**Comment by andrewvanbreda** [comment]
These requirements have been basically been covered on this page, so will close this now so not too many issues open about grids.
