### ISSUE TITLE
Latest news

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#45]
Add a block to the home page to display headlines from Latest news articles:
https://test-ceh-poms.pantheonsite.io/news

In the articles themselves:
- Remove the "Submitted by" details
- Keep the date, but make it into a UK-format date (dd mmm yyyy)

**Comment by BirenRathod** [comment]
@kitenetter 
I have added latest news block, removed "submitted by" on latest news page. Also I have added the twitter block on home page.
Date has implemented to UK format.

**Comment by kitenetter** [comment]
Thanks @BirenRathod that's a great improvement.
