### ISSUE TITLE
Termlists require translation

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/PoMS#46]
A note to say I just thought of something.
The terms in the data entry form termlists will need translating and these won't be exported by Drupal/Transifex, the translations need adding to the Warehouse.
You may need to let me know what the translations are, then I can add them to the Warehouse.

**Comment by kitenetter** [comment]
Most of the terms should be available already in the Welsh version of the paper recording form - I will compile a list and see if we are missing anything.

**Comment by kitenetter** [comment]
I'm just about to start working on the termlists. What I intend to do is compile a Word doc that lists the terms we use for the PoMS surveys, and give the Welsh equivalent where we already have it.

@andrewvanbreda @DavidRoy let me know if there is a better way of doing this.

**Comment by andrewvanbreda** [comment]
@kitenetter This is fine, I can then add them to the Warehouse

**Comment by kitenetter** [comment]
@andrewvanbreda here are the terms for the public FIT Count form, let me know if there is anything else I need to do.

[Termlist translations.xlsx](https://github.com/BiologicalRecordsCentre/PoMS/files/6185223/Termlist.translations.xlsx)

There are just a couple of terms that I haven't been able to find translations for - @DavidRoy please let me know what is best to do to get these sorted out.

My understanding is that we are not required to translate the 1 km square forms.

**Comment by DavidRoy** [comment]
@kitenetter I suggest you send the spreadsheet direct to Elen for the additions and an overall review.

At some point we should get these terms into Transifex in preparation for needing translations in other languages

**Comment by andrewvanbreda** [comment]
@DavidRoy 
Note that importing these as Transfex terms using Drupal's translation system won't work  from my experience on my other multi-lingual project.
These will only work when I add them to the termlists in the Warehouse.

Obviously if you want to add them to Transifex for the purposes of having an elegant structure that includes everything, feel free to do that, it is just that any import using Drupal's language facilities won't work for these.

**Comment by DavidRoy** [comment]
@andrewvanbreda understood.  Transifex provides a useful way of crowd-sourcing the translations, without having to manage spreadsheets circulating.  We still then have the manual job of adding in the termlist translations in the warehouse.

**Comment by andrewvanbreda** [comment]
Note I didn't finish entering the terms yet, but I fixed an issue this morning which means I can see it working in Welsh now for the terms I have entered.

**Comment by kitenetter** [comment]
@andrewvanbreda we now have the termlists back from the translator, and more of them have been changed that I was hoping, see highlighted rows:

[Termlist translations for website.xlsx](https://github.com/BiologicalRecordsCentre/PoMS/files/6213083/Termlist.translations.for.website.xlsx)

Can you incorporate these changes please? Or alternatively, let me know when you've finished entering the first batch and then I can go in and edit the ones that need to change.

**Comment by andrewvanbreda** [comment]
Hi @kitenetter 
Yes I will do these, I have just done some of them.
It is probably best I enter them for now as I noticed a problem with the Warehouse where after about 5 entries it starts warning about the work_queue, and then I have to come back later.
What will be good is once I have done all of them is if you go and double-check all the entries as it will be critical all the translations are put in the right place without mistakes.
Will let you know.

**Comment by andrewvanbreda** [comment]
@DavidRoy @kitenetter 
I finally managed to finish these (I kept getting interrupted with work_queue warning from the warehouse).

**Comment by andrewvanbreda** [comment]
@kitenetter 
We seem to be missing translations for Wind Strength

**Comment by kitenetter** [comment]
Terms for "Weather: wind  (PoMS)" (termlist id 673):

**id | English | sort order | Welsh**
13589 | Leaves still/moving occasionally | 1 | Dail yn llonydd/symud weithiau
13590 | Leaves moving gently all the   time | 2 | Dail yn symud yn ysgafn drwy’r amser
13591 | Leaves moving strongly | 3 | Dail yn symud yn sylweddol
13606 | Not recorded | 4 | Heb ei gofnodi

**Comment by andrewvanbreda** [comment]
@kitenetter 
Done, will not appear on system just yet until background scheduled tasks have been run by warehouse.

**Comment by andrewvanbreda** [comment]
@kitenetter These are on site now.

Maybe close this if you are happy?
