### ISSUE TITLE
Typo in 2nd para Home page - remove 'more' on Latest news - then all Home page links signed off

### ISSUE THREAD

**Issue by CCarvell** [BiologicalRecordsCentre/PoMS#47]
Home page
There is one typo to correct in the second parargraph under "Welcome to... PoMS"

"and keep up with _our_ latest news. - not _out_ latest news"

Latest News
Check the link within last sentence "Contact us"
After this there is an erroneous "more" that should be removed?

Otherwise I think we can sign off the Home page and all 3 pages linked with it for translation.

I will move onto the next pages for sign off today. Claire

**Comment by kitenetter** [comment]
Home page corrected.

We'll need the "more" option once we have lots of news, but I've switched it off for now.

The "Contact us" link is working for people logged in as admins, but not yet for others. I think @andrewvanbreda is working on the user permissions that will sort this out.

The contact form is at:
https://test-ceh-poms.pantheonsite.io/user/12/contact

and looks like this:
![image](https://user-images.githubusercontent.com/16039111/111137924-46c74900-8577-11eb-8539-5024f567a9c9.png)

There is some text on that form that I assume we will need to get translated:

Contact PoMS support
Your name
Your email address
To PoMS support
Subject
Message
Send yourself a copy
Send message
Preview

**Comment by andrewvanbreda** [comment]
Hi kitenetter,

Not sure what has happened in regards to the setup of this, but this is not quite right as that is not the site contact form. I think that is a personal contact form for the PoMS Support user account.

The URL of the site contact form is here and is could be accessed by unregistered users if you setup a link to it wherever you want it.
https://test-ceh-poms.pantheonsite.io/contact/feedback

**Comment by kitenetter** [comment]
Thanks @andrewvanbreda - that's my ignorance, I didn't realise we had a site contact form and had set up the user one instead. I will change the links.

Does the site contact form go to poms@ceh.ac.uk?

**Comment by andrewvanbreda** [comment]
@kitenetter 
Yes should do. Obviously we can give that a double-check and test

**Comment by kitenetter** [comment]
Closing.
