### ISSUE TITLE
FIT Count map tidying

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#49]
On this page:
https://test-ceh-poms.pantheonsite.io/fit-counts-map

Where we have:

![image](https://user-images.githubusercontent.com/16039111/111456362-cf2c2200-870e-11eb-9aea-0d5e65cdddaf.png)

Can we remove the "Report parameters" subheading, and replace the label "Filter" with "Apply year".

And move the filter button to the right of the year dropdown.

**Comment by CCarvell** [comment]
Can I check whether the FIT Count map will have text alongside saying "XXX count submitted so far this year by XX participants"?? 
The number of participants is not critical .....
Sorry I can't view the draft map but can we also position the FIT Count logo alongside the map with the PoMS logo??

**Comment by andrewvanbreda** [comment]
@kitenetter @CCarvell 
I haven't look at the enhancements required in the specification for this page yet, but I will do shortly. The button positions are automatically set by Indicia/Drupal theme, but will try to adjust or override that

**Comment by andrewvanbreda** [comment]
"Filter" and "Apply year" label part of this has been changed. Still working on other bits

**Comment by andrewvanbreda** [comment]
@kitenetter @CCarvell 
Hi, Sorry am slow to directly respond to some of the things mentioned here.
I have now written a new report, so the wording about counts and participants should be possible.

@CCarvell 
In regards to "can we also position the FIT Count logo alongside the map with the PoMS logo??"
Am not entirely sure what you mean here as I can't see a FIT Count logo, are you able to clarify?. In regards to the PoMS logo, moving it is problematic as it is part of the general site, it isn't part of this page, it is controlled by the site.
We could move it I suppose by overriding it, but it is designed to be in a consistent place regardless of which page you are on on the site so if we move it, it will jump around as people move around the site.

Can you let me know the following things
1. What label do you now want for the button, as their is now a survey filter, not just year so Apply Year no longer makes sense.
2. Do still want the button at the side? Am not sure that is the best strategy anymore as there are now Year/Survey filters.....also need to remember that phone screens are long, so this might not necessarily look that good in that situation as I think we would need to put all the filters and button on one row to make it look good.
Let me know, obviously your site, so ultimately up to you.

**Comment by BirenRathod** [comment]
@andrewvanbreda You can upload logo from here -> https://github.com/BiologicalRecordsCentre/PoMS/issues/18

**Comment by kitenetter** [comment]
@andrewvanbreda for the button let's label it "Apply filters". Happy to keep it underneath the other boxes if that makes sense for mobile use.

I've updated the text slightly at the top of the page to allow for there being more than one filter.

**Comment by CCarvell** [comment]
Not sure if this helps, but this is the FIT Count logo used by the app. 
@andrewvanbreda I understand your points about the main PoMS logo being controlled by the site, fine.
If there is a way of having the FIT Count logo alongside the map, great, but not absolutely essential for phase 1.
![FitCount_Logo_Positive](https://user-images.githubusercontent.com/44494345/111979482-0890d300-8afd-11eb-9922-0d2bfc3030d1.jpg)

**Comment by andrewvanbreda** [comment]
@CCarvell Yes I should be able to put this alongside the map, but will have to be low priority for now

**Comment by kitenetter** [comment]
Have added the FIT Count logo to the introductory text box as a short-term solution.

I think the remaining task from this issue is to add text alongside saying "XXX count submitted so far this year by XX participants" (The number of participants is not critical .....)

**Comment by andrewvanbreda** [comment]
Done, although be aware that I misread this and it currently isn't just this year only, I will change that

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Can you pull this report whenever you get a change so the data is limited to just this year.
Thanks
projects/PoMS/result_counts.xml

**Comment by BirenRathod** [comment]
@andrewvanbreda I have pulled that report now.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Brill thanks.
Martin close this issue if you are happy with this now.

**Comment by andrewvanbreda** [comment]
@kitenetter 
Am going to close this, as Claire was concerned about the number of open issues and I think this one is done. Re-open if needed.
