### ISSUE TITLE
Move existing sample/occurrence data to new website

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/PoMS#5]
AVB to write scripts, then contact CEH for running

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod 

I have some test code to move the samples from the old iRecord surveys to the new website. Just to move a sample with a few occurrences.

I have tested this on my machine using different IDs, but obviously please take any precautions you feel the need to take before running this on live.


update indicia.samples
set survey_id=636,updated_on=now(),updated_by_id=5553
where survey_id = 467 and id in (13996817) and deleted=false;

update indicia.occurrences o
set website_id=136,updated_on=now(),updated_by_id=5553
from indicia.samples s
where sample_id = s.id
and s.id in (13996817) 
and s.survey_id = 636
and o.deleted=false
and s.deleted=false;

insert into indicia.work_queue(task, entity, record_id, cost_estimate, priority, created_on)
select 'task_cache_builder_update', 'sample', id, 100, 2, now()
from indicia.samples 
where survey_id = 636 and deleted=false
and id in (13996817);

insert into indicia.work_queue(task, entity, record_id, cost_estimate, priority, created_on)
select 'task_cache_builder_update', 'occurrence', o.id, 100, 2, now()
from indicia.occurrences o
join indicia.samples s on s.id = o.sample_id and s.survey_id = 636 and s.id in (13996817) and s.deleted=false
where o.deleted=false;

**Comment by DavidRoy** [comment]
@BirenRathod we will let you know when we want to run these updates.  No action to be taken yet, thanks

**Comment by andrewvanbreda** [comment]
@DavidRoy @BirenRathod 
I think we should go ahead with this test now.
Martin agreed in meeting this morning.
We only have week left, so think need to get on now.
Thanks

**Comment by BirenRathod** [comment]
@andrewvanbreda  I have no problem, let me know, when do you want to start?

**Comment by andrewvanbreda** [comment]
@BirenRathod 
The test SQL at the top of this email has  been checked on my own machine, but will need running on the live warehouse. This should initially only copy 1 record which can be checked, then we can look to run it for more records once this is done.
Obviously as this is running on live, you will need to take any recovery precautions you see fit before the run.

**Comment by BirenRathod** [comment]
@andrewvanbreda For one record we can easily revert it back, so seems like a very minimum risk. isn't it?

**Comment by andrewvanbreda** [comment]
@BirenRathod The one record itself isn't a risk, it would just be if there was some kind of problem with the run and it accidentally did more.
I mean you can obviously check the SQL yourself and decide yourself if you are happy to run it.
It is entirely up to you whether you feel any precautions are needed or not.

**Comment by BirenRathod** [comment]
Thanks @andrewvanbreda. I should have to worry about mostly two tables. samples & occurrences. am I right?

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Yes it updates just one occurrence and its associated sample.
The only other table it touches is the work_queue

**Comment by BirenRathod** [comment]
@andrewvanbreda yes, I seen it but I'm more concern about other two tables.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Ok, let me know if you need any further input from me.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
One test you could do is run it on DEV/Test warehouse and replace the 13996817 ID with one that doesn't exist and it should do nothing

**Comment by andrewvanbreda** [comment]
@BirenRathod 
If you are unsure, what you could do is run the SQL below first.
Then you can observe it is just updating one record (the SQL makes not change as set survey_id=survey_id & set website_id=o.website_id),  then do the real run with the sql above.
That way if the initial test goes wrong, no alteration is made to the rows

update indicia.samples
set survey_id=survey_id
where survey_id = 467 and id in (13996817) and deleted=false;

update indicia.occurrences o
set website_id=o.website_id
from indicia.samples s
where sample_id = s.id
and s.id in (13996817)
and s.survey_id = 636
and o.deleted=false
and s.deleted=false;

**Comment by BirenRathod** [comment]
@andrewvanbreda 
Both above queries run successfully.

**Comment by andrewvanbreda** [comment]
@BirenRathod Ok thanks. I will look when get chance. We probably won't be moving the rest across on a Friday afternoon anyway, so will let you know by Monday.

**Comment by BirenRathod** [comment]
No problem.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Hi Biren,
I think that is only my test SQL that has been run. To actually do the copy, the 4 SQL statements  in the second post in this thread need to be run.
Thanks

**Comment by BirenRathod** [comment]
@andrewvanbreda Ok,

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Hi Biren,
Can I check if those 4 sql statements at the top were run, as am not seeing the record I was expecting on the system.
Cheers

**Comment by BirenRathod** [comment]
@andrewvanbreda  Do you want me to run?

**Comment by andrewvanbreda** [comment]
@BirenRathod Yes please, we will have to as live is Thursday as far as I am aware. So we need to check this record survey switch is working.

**Comment by BirenRathod** [comment]
@andrewvanbreda I will let you once done.

**Comment by BirenRathod** [comment]
@andrewvanbreda I have ran all above top 4 SQLs now.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
OK thanks. Can't see it yet, but might be cache tables so will wait a bit and check again

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Um, the base records look ok in the Warehouse.
Would you be able to send this result please so can get idea what might be happening in the cache tables.

select * from indicia.cache_samples_functional where id = 13996817;

select * from indicia.cache_samples_nonfunctional where id = 13996817;

Thanks

**Comment by andrewvanbreda** [comment]
@BirenRathod @kitenetter
Hi Biren,
Just realised this has actually worked, so don't worry about running those cache select statements (I asked John to run them this evening anyway)

The problem was simply I forgot the data grids on PoMS have a year filter so the row wasn't displaying.

I will contact you about bringing the rest of the records over tomorrow.

**Comment by andrewvanbreda** [comment]
Hi  @BirenRathod 

As a test could you get me the number of rows changed by these updates, and the counts.

Notice the updates only set the website_id, survey_id fields to themselves, so are safe to run if they go wrong (hence the test).
If the counts are ok this means the sql should work and I can send you sql that actually changes the fields properly

update indicia.samples
set survey_id=survey_id
where survey_id = 467 and deleted=false;

update indicia.occurrences o
set website_id=o.website_id
from indicia.samples s
where sample_id = s.id
and s.survey_id = 467
and o.deleted=false
and s.deleted=false;



update indicia.samples
set survey_id=survey_id
where survey_id = 480 and deleted=false;

update indicia.occurrences o
set website_id=o.website_id
from indicia.samples s
where sample_id = s.id
and s.survey_id = 480
and o.deleted=false
and s.deleted=false;




update indicia.samples
set survey_id=survey_id
where survey_id = 481 and deleted=false;

update indicia.occurrences o
set website_id=o.website_id
from indicia.samples s
where sample_id = s.id
and s.survey_id = 481
and o.deleted=false
and s.deleted=false;





select count(*) from indicia.samples where survey_id = 467 and deleted=false;
select count(*) from indicia.samples where survey_id = 480 and deleted=false;
select count(*) from indicia.samples where survey_id = 481 and deleted=false;

select count(*) from indicia.occurrences where sample_id in
(select id from indicia.samples where survey_id = 467 and deleted=false);

select count(*) from indicia.occurrences where sample_id in
(select id from indicia.samples where survey_id = 480 and deleted=false);

select count(*) from indicia.occurrences where sample_id in
(select id from indicia.samples where survey_id = 481 and deleted=false);

**Comment by BirenRathod** [comment]
@andrewvanbreda Update results in same order as you posted queries above.
1 - 3623
2 - 10207
3 - 1327
4 - 4017
5 - 2992
6 - 24980

Counts results same as above query
1 - 3623
2 - 1347
3 - 2992
4 - 10221
5 - 4031
6 - 25128

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Hi Biren,

Can we have a go at rerunning these 3 counts, I forgot to add deleted flag to occurrence page, cheers.

select count(*) from indicia.occurrences where deleted=false and sample_id in
(select id from indicia.samples where survey_id = 467 and deleted=false);

select count(*) from indicia.occurrences where deleted=false and sample_id in
(select id from indicia.samples where survey_id = 480 and deleted=false);

select count(*) from indicia.occurrences where deleted=false and sample_id in
(select id from indicia.samples where survey_id = 481 and deleted=false);

**Comment by BirenRathod** [comment]
@andrewvanbreda 
Below are the results in same order.
1 - 10207
2 - 4017
3 - 24980

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Thanks Biren, so there is only 1 unexplainable disparity in these results.
Can you retry these two, I do not understand why there were not initially the same, unless there is a typo in the counts listed? (in which case they don't need a rerun). Cheers

update indicia.samples
set survey_id=survey_id
where survey_id = 480 and deleted=false;

select count(*) from indicia.samples where survey_id = 480 and deleted=false;

**Comment by BirenRathod** [comment]
@andrewvanbreda 
Both queries returned with 1347 number.

**Comment by andrewvanbreda** [comment]
@DavidRoy @CCarvell @kitenetter 
We are now in a position to do the actual copying of data to the new website from iRecord, are you happy for this to go ahead?

**Comment by kitenetter** [comment]
@andrewvanbreda I would say yes, let's go for it!

Are you deleting it from the iRecord surveys, or will we have the data duplicated in two places (which is fine for now)?

I think I will will now switch off the iRecord recording form so we don't have any new samples added there.

**Comment by andrewvanbreda** [comment]
@kitenetter 
It is the same rows, but the survey_id and website_id fields will be switched to the new site.

**Comment by kitenetter** [comment]
@andrewvanbreda oh yes, you'd told me that before, sorry, That's fine.

**Comment by DavidRoy** [comment]
@andrewvanbreda Happy to leave this decision to martin and claire

**Comment by andrewvanbreda** [comment]
@BirenRathod Final sql to run

update indicia.samples
set survey_id=636,updated_on=now(),updated_by_id=5553
where survey_id = 467 and deleted=false;

update indicia.occurrences o
set website_id=136,updated_on=now(),updated_by_id=5553
from indicia.samples s
where sample_id = s.id
and s.survey_id = 636
and o.deleted=false
and s.deleted=false;

update indicia.samples
set survey_id=637,updated_on=now(),updated_by_id=5553
where survey_id = 480 and deleted=false;

update indicia.occurrences o
set website_id=136,updated_on=now(),updated_by_id=5553
from indicia.samples s
where sample_id = s.id
and s.survey_id = 637
and o.deleted=false
and s.deleted=false;

update indicia.samples
set survey_id=638,updated_on=now(),updated_by_id=5553
where survey_id = 481 and deleted=false;

update indicia.occurrences o
set website_id=136,updated_on=now(),updated_by_id=5553
from indicia.samples s
where sample_id = s.id
and s.survey_id = 638
and o.deleted=false
and s.deleted=false;

**Comment by andrewvanbreda** [comment]
@BirenRathod Sorry, missed the work_queue statements as these hadn't been included with the tests, these afterwards cheers

insert into indicia.work_queue(task, entity, record_id, cost_estimate, priority, created_on)
select 'task_cache_builder_update', 'sample', id, 100, 2, now()
from indicia.samples
where survey_id in (636,637,638) and deleted=false;

insert into indicia.work_queue(task, entity, record_id, cost_estimate, priority, created_on)
select 'task_cache_builder_update', 'occurrence', o.id, 100, 2, now()
from indicia.occurrences o
join indicia.samples s on s.id = o.sample_id and survey_id in (636,637,638) and s.deleted=false
where o.deleted=false;

**Comment by BirenRathod** [comment]
@andrewvanbreda Here are the update results in same order as above posted query.
1 - 3626
2 - 10224
3 - 1347
4 - 4027
5 - 2992
6 - 24980

And to two work_queues are inserted successfully.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Great thanks Biren. Just have to wait for the work queue, but this all looks good so far :) thanks for your help with this

**Comment by andrewvanbreda** [comment]
@kitenetter 
Hi Martin,
I think the iRecord forms are still active? I assume you intend to deactivate them?
I can see 6 samples have been entered on iRecord since the switch over.
This won't be a problem as can get Biren to rerun the transfer SQL, but obviously need to take those forms offline in long run.

**Comment by kitenetter** [comment]
@andrewvanbreda 
Thanks for the info. What I did was to move the iRecord form to a new URL that has never been given out, and is not in any menus, so I was hoping that would be enough to prevent people from using it, but clearly not. I have now marked it as unpublished as well.

That applies to the public FIT Count - are the recent additions for the public count or the 1 km count? I'll unpublish the 1 km forms as well to be on the safe side.

**Comment by kitenetter** [comment]
@andrewvanbreda I can see that five pan-trap surveys have been added using the old iRecord form, all for location "SY8586 near Wool". Are they the samples you are talking about?

IDs are:
14423685
14423899
14423942
14423976
14424014

I assume you will move these over, but if that is a problem let me know and I can ask the recorder to enter them again.

**Comment by andrewvanbreda** [comment]
@kitenetter 
Yes additionally
14444882 which is a "PoMS FIT Count" survey item.
Note that unpublishing doesn't actually prevent use of the form (I think anyway), although hopefully the red will put the user off.
If this doesn't work you could add some "Not in use" text to the page, or we could hide the save button with jQuery.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
We will need to run this, it is just same as before but without the 1km Survey as that doesn't need running, and additional sample id restrictions to just the samples we are interest in (although it shouldn't actually matter if those aren't present in the query)

update indicia.samples
set survey_id=636,updated_on=now(),updated_by_id=5553
where survey_id = 467 and id = 14444882 and deleted=false;

update indicia.occurrences o
set website_id=136,updated_on=now(),updated_by_id=5553
from indicia.samples s
where sample_id = s.id
and s.survey_id = 636
and s.id = 14444882
and o.deleted=false
and s.deleted=false;



update indicia.samples
set survey_id=638,updated_on=now(),updated_by_id=5553
where survey_id = 481 
and id in (14423685,14423899,14423942,14423976,14424014)
and deleted=false;

update indicia.occurrences o
set website_id=136,updated_on=now(),updated_by_id=5553
from indicia.samples s
where sample_id = s.id
and s.survey_id = 638
and s.id in (14423685,14423899,14423942,14423976,14424014)
and o.deleted=false
and s.deleted=false;





insert into indicia.work_queue(task, entity, record_id, cost_estimate, priority, created_on)
select 'task_cache_builder_update', 'sample', id, 100, 2, now()
from indicia.samples
where survey_id in (636,637,638) 
and id in (14444882,14423685,14423899,14423942,14423976,14424014)
and deleted=false;




insert into indicia.work_queue(task, entity, record_id, cost_estimate, priority, created_on)
select 'task_cache_builder_update', 'occurrence', o.id, 100, 2, now()
from indicia.occurrences o
join indicia.samples s on s.id = o.sample_id and survey_id in (636,637,638) 
and s.id in (14444882,14423685,14423899,14423942,14423976,14424014)
and s.deleted=false
where o.deleted=false;

**Comment by BirenRathod** [comment]
@andrewvanbreda They all performed successfully.

**Comment by andrewvanbreda** [comment]
@BirenRathod
Thanks Biren. Think need to wait for the cache table to update, but according to Warehouse UI this worked

**Comment by andrewvanbreda** [comment]
Closing as looks like worked (nothing that only 14444882 will be visible on FIT count map as others are pan trap).
Have also committed the transfer code to Github support_files in case need to use again
