### ISSUE TITLE
Text edits for Taking part and sub-pages

### ISSUE THREAD

**Issue by CCarvell** [BiologicalRecordsCentre/PoMS#50]
A few edits for @kitenetter but otherwise signing off these pages for translation.

**Taking part**
under FIT Counts: change
"Choose a target flower and count all insects landing on it within ten minutes" to
"Choose a patch of target flowers and count all insects landing on them within ten minutes" - I'm still concerned about creating an image of the count being done on one single target flower.

**FIT Counts**

"Download a PoMS poster" - this poster will need updating for 2021 - should we leave the link off until it's ready, or can we do this before website launch late April? Only minor updates needed, plus maybe adding the app logo. Growing The Future funded the Welsh translation - we would need to update the poster in Welsh too. 
I wondered about transferring the "Ten steps to carrying out a FIT Count" to Martin's template for the Highlights in Numbers - with the divulgare insects flying about the page - adding the app logo and new website link with maybe 2 photos - possibly changing the green to the deep pink edging and pale interior with black text - this would be our printable FIT Count guide. 
Claire and @kitenetter to discuss.

**1 km square survey**
Correct typo in first paragraph:
"using pan-traps to capture _take_ samples of insects" delete _take_

Edit the sentence near the bottom:
"Equipment, training, access permissions _and identification of samples_ are all provided by PoMS.

**Taking things further**
Perfect, no changes!

**Comment by kitenetter** [comment]
Thanks @CCarvell 

**Taking part** and **1 km square survey**: edits done.

**FIT Counts**: I suggest we leave the poster text on for now so that it gets translated, but we can remove it before going live and put it back in when we have a new poster available.

It would be good to turn the ten steps into a more engaging image, but again we don't need to do that now, once the text is translated we can produce graphics for both languages.

**Comment by CCarvell** [comment]
agreed @kitenetter thanks.
Are you OK to get these pages transferred to the relevant part of Transifex? Has Elen started translating the web pages now?

**Comment by DavidRoy** [comment]
I've held off sending everything to Transifex as I think it's best for Elen to prioritise in the order:
FIT Count App
FIT Count website
PoMs website
 - home page
 - FIT count pages etc

But I will have a stock-take of 'signed off' website pages

**Comment by kitenetter** [comment]
Update: awaiting final translation before editing the PoMS poster information.

**Comment by kitenetter** [comment]
Now dealt with.
