### ISSUE TITLE
Edits for "Reports and newsletters" sub-page then signed off for translation

### ISSUE THREAD

**Issue by CCarvell** [BiologicalRecordsCentre/PoMS#51]
Some edits for @kitenetter  but otherwise signing off this page for translation.

**Reports and newsletters**
I wonder if we can make the wording more generic so that it doesn't need updating and translating each time we add a new progress report/s or newsletter to the website. Simply list each output with a link to the pdf or Defra pages? Could we also add an image of the 2019 newsletter as below to click on? sadly the text was translated but it never got re-formatted so we can't do that for the Welsh.
Note also we are not expected to retrospectively translate anything from 2018 or previous to this as the Welsh language act was not in effect. So English versions can appear on the Welsh pages. 2016 report attached as pdf.

So after "A number of reports and newsletters are available." can we list in reverse order (is this the best way with latest outputs coming first, or should older reports come first?):

PoMS progress reports:
- 2020  [_note this will be loaded in Eng and Welsh by the time website goes live_]
- 2019
- 2018

PoMS Newsletters:
- January 2019

Pollinator Monitoring and Research Partnership full technical reports (detailed reports with technical annexes):

- Establishing a UK Pollinator Monitoring and Research Partnership (final report 2017-2019)

- Design and Testing of a National Pollinator and Pollination Monitoring Framework (final report 2016)

Materials from PoMS webinar (March 2020):

Presentations and summary of question/answer sessions (PDF)
Webinar recording on YouTube:

![image](https://user-images.githubusercontent.com/44494345/111821896-15ce7780-88db-11eb-8573-c7fd262e88d8.png)
[Defra_WC1101_pollinator monitoring final_report_Carvell etal_2016.pdf](https://github.com/BiologicalRecordsCentre/PoMS/files/6173247/Defra_WC1101_pollinator.monitoring.final_report_Carvell.etal_2016.pdf)

**Comment by CCarvell** [comment]
@kitenetter my screen grab of the newsletter front page didn't work, so not to worry if you can't get that shown.

**Comment by kitenetter** [comment]
I agree it is good to simplify this page for future updating, thanks. 

Those edits are done, and newsletter image added. Still to add links to PDF docs (but that shouldn't affect translation).

**Comment by kitenetter** [comment]
Links to PDF docs still to be done on all relevant pages, will transfer that to a new issue. Closing this one.
