### ISSUE TITLE
pages lacking meaningful url

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/PoMS#54]
https://test-ceh-poms.pantheonsite.io/node/6
https://test-ceh-poms.pantheonsite.io/node/7

@kitenetter do you want urls for these?

**Comment by kitenetter** [comment]
Yes, I just haven't been prioritising the 1 km square pages. Will sort it out soon.

**Comment by DavidRoy** [comment]
No rush. I'm just logging issues as i find them

**Comment by kitenetter** [comment]
Yes, sorry, I realise that, and probably didn't need to reply the first time! Please do continue logging them, it is helpful, and I will try to refrain from unhelpful replies :)

**Comment by andrewvanbreda** [comment]
Yes, I haven't worked much on those pages, they will have meaningful URLs

**Comment by andrewvanbreda** [comment]
@DavidRoy @kitenetter 
Hi, I have added URLs, but also disabled the menu items that are not worth checking yet because I need to check them first.
I will enable them as soon as I can.
We don't want lots of issues on pages I didn't check yet, so best to disable them and re-enable when ready to test.

**Comment by kitenetter** [comment]
I think we can close this (but need to do final checks and tests of all menus and URLs prior to launch).
