### ISSUE TITLE
Website pages with Welsh translations complete

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/PoMS#56]
This is an issue to keep track of pages where welsh translation is complete.  Links to #55 

Translation done:
- [x] About PoMS https://test-ceh-poms.pantheonsite.io/about
- [x] FIT Count app https://test-ceh-poms.pantheonsite.io/fit-count-app
- [x] FAQs. https://test-ceh-poms.pantheonsite.io/faqs
- [x] taking part. https://test-ceh-poms.pantheonsite.io/taking-part
- [x] Species recording. https://test-ceh-poms.pantheonsite.io/species-recording
- [x] Terms of use
- [x] Reports and research. PoMS project reports. https://test-ceh-poms.pantheonsite.io/reports
- [x] Reports and research. PoMS research. https://test-ceh-poms.pantheonsite.io/research
- [x] Reports and research. Data from PoMS. https://test-ceh-poms.pantheonsite.io/data

Sent for translation, awaiting completion:
- [ ] home page. https://test-ceh-poms.pantheonsite.io/
- [ ] taking part. FIT counts. https://test-ceh-poms.pantheonsite.io/fit-counts
- [ ] taking part. One km survey square. https://test-ceh-poms.pantheonsite.io/one-km-square-survey
- [ ] View results. Map of FIT Counts. https://test-ceh-poms.pantheonsite.io/fit-counts-map
- [ ] View results. My results. https://test-ceh-poms.pantheonsite.io/my-results
- [ ] Add your results. Enter-fit-count. https://test-ceh-poms.pantheonsite.io/enter-fit-count
- [ ] Privacy notice

Can't find a way of sending these to transifex, so will contact Elen direct:
- [ ] Website feedback https://test-ceh-poms.pantheonsite.io/contact/feedback
- [ ] News https://test-ceh-poms.pantheonsite.io/news

Translation not needed:
- Add your results. 1km FIT count. https://test-ceh-poms.pantheonsite.io/1km-fit-count
- Add your results. 1km square survey - pan-trap results. https://test-ceh-poms.pantheonsite.io/add-1km-samples
- Add your results. Select pan-trap samples to add insect bycatch data for 2020. https://test-ceh-poms.pantheonsite.io/node/6
- Add your results. Select pan-trap samples to add insect species data for 2020. https://test-ceh-poms.pantheonsite.io/node/7

**Comment by kitenetter** [comment]
- [ ] FIT Count app

**Comment by kitenetter** [comment]
@DavidRoy the text has changed on a number of pages since it was sent to Transifex. Can you let me know how I deal with this - do I need to re-send the whole page, or just the parts that have changed, and what is the procedure for that?

- Home page (a few additions)
- Taking part - FIT Counts  (minor additions of mentions of the app, that we can probably translate based on other pages, but not sure how to integrate this into the Drupal procedure).
- Taking part - One km square survey https://test-ceh-poms.pantheonsite.io/one-km-square-survey (minor change to remove reference to ERAMMP)

**Comment by kitenetter** [comment]
Does transifex deal with Indicia recording and reporting pages?
To send to transifex, do I use "Add continuous job" from the Jobs page (https://test-ceh-poms.pantheonsite.io/admin/tmgmt/jobs)?

**Comment by kitenetter** [comment]
Loose ends:
- [ ] check that logos are displayed correctly on Welsh pages once they are finalised for English (Home and About pages, see #27)

**Comment by kitenetter** [comment]
Need to check that all relevant menu items have been translated (most have but not all as yet).

Need to work out how to deal with translating the links in the footer.

**Comment by kitenetter** [comment]
There are still a few items in transifex awaiting translation, but most is now done and I'm closing this issue.
