### ISSUE TITLE
Solutions for displaying location of grid

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/PoMS#57]
We have a problem with the recording grids. 
We want to have a location column of some kind, however I cannot display this currently because

1. The Location Name and Public Entered Sref database fields are not populated in the cache_tables when privacy precision is activated.
This is not what I thought, I thought sample Public Entered Sref would be a blurred spatial reference, but it isn't

2. Occurrences but not samples have an output_sref field which is a blurred spatial reference, but our grids are sample based.

There are several possible solutions to this.

A. 
Me add an output_sref database column, although this wasn't really taken into account with the project funding and is a bit tight for time to be getting that live.

B. Live without a location column a Fit Count Map page (although it can still be present on My Results, and the admin samples list because those show full detail)

C. Concoct a workaround. Like showing the location by joining to occurrences cache table, and taking the first occurrence output_sref. This would slow down the report a bit and it wouldn't show for empty samples.

D. Display only the first X digits of the spatial reference or something similar, but this isn't that simple as there are multiple spatial references systems and WGS84 is a single point.

Let me know any thoughts.

**Comment by kitenetter** [comment]
I think the only short-term solution is to not show a location in the grid for the FIT Count map. People will still be able to zoom in to find their own location, or to filter by their recorder name, if they need to.

So let's go with option B, and think about option A if resources allow in future.

**Comment by andrewvanbreda** [comment]
Done. 
Note that on the My Records & List of sample pages for admins, there is a column called "Detailed grid ref".....I will change this to "Grid ref", don't raise that as will do that now, but will only be moved to the site next time I get Biren to move the files across (and it probably isn't worth getting him to do that just for that change).
