### ISSUE TITLE
Create Drupal view to allow download of user data (including account fields)

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/PoMS#58]
must include a CSV download button

**Comment by andrewvanbreda** [comment]
@kitenetter 
Done (apart from CSV download), available in Administration menu.

@BirenRathod  I think we need to install this module (or similar alternative)
https://www.drupal.org/project/views_data_export

**Comment by BirenRathod** [comment]
@andrewvanbreda That module is already available, so no problem for you to install it.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Thanks Biren. Didn't realise that would be in the default list. Cheers

**Comment by BirenRathod** [comment]
@andrewvanbreda No porblem.
I recon , please search from the module list, if you can't find then let me know and I make sure to available for you.

**Comment by andrewvanbreda** [comment]
@kitenetter @CCarvell 
New Users Export option available in administration menu.
Close if happy. Note it appears to export the header twice, not sure why it is doing that. You can just manually remove one of those rows after export and perhaps that will be fixed with an update to the export module in future.

**Comment by kitenetter** [comment]
Is it possible to add the warehouse user ID for each user?

**Comment by andrewvanbreda** [comment]
@kitenetter 
Done.
Please close if happy, or let me know if not.
