### ISSUE TITLE
Custom taxon list translations

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#60]
The public FIT Counts use a custom taxon list, list ID 221 in the warehouse.

We need to add Welsh names to that list, see spreadsheet:

[Taxon list translations.xlsx](https://github.com/BiologicalRecordsCentre/PoMS/files/6221286/Taxon.list.translations.xlsx)

Let me know if you want me to make any warehouse changes.

The 1 km square FIT Counts also use list ID 221, so we need to ensure that the English names are displayed on the 1 km FIT Count data entry form.

There is also a custom taxon list, ID 234, that is usd for the pan-traps, but this does not need to be translated.

**Comment by andrewvanbreda** [comment]
@kitenetter 
I have made the following adjustments

- iRecord adjusted to stop Welsh filtering through
- Public FIT count form altered to show English/Welsh species depending on language
- 1km altered to only show English regardless of language selection. Does this mean this page won't be translated?.....or did I misunderstand and you do actually want Welsh to appear on this page?

**Comment by kitenetter** [comment]
@andrewvanbreda as things stand there is no requirement to provide Welsh versions for any of the data entry forms and data selection reports relating to the 1 km square survey. It's possible that Welsh will be needed in future, but as long as we don't do anything that would make it impossible to translate in future we are fine to keep them in English.

It would be good to have a Welsh version of the page that will show the locations of the 1 km squares (I don't think we have this page set up yet). Should i set up a new issue for that page?

**Comment by andrewvanbreda** [comment]
@kitenetter 
OK, have changed it to force the English to be shown on all data entry pages now.
Not sure how to deal with the term lists at moment, as those will still show the Welsh.
I will deal with that separately.
Ok yes please raise another Github for the page you mentioned.

Please close this issue once you are happy, if you wanted to check the translations I entered you can do so directly in the Warehouse (up to you).

**Comment by andrewvanbreda** [comment]
I have double-checked these entries on the Warehouse, so going to close this now.
If you want to double-check the translations feel free.
