### ISSUE TITLE
Documentation: FIT Count survey form

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#63]
The survey form will need updating to coincide with the launch of the new site:
- Change the link in the header to the new website
- Change the link at the end to direct people to the data entry form on the new website, rather than iRecord
- Add a link to the FIT Count app if possible (probably need to set up an additional web page for this)
- May as well change the blue line dividers to match the pink of the new look

The Welsh version of the survey form will need to be updated to match, and will require a small amount of additional translation.

Note that there is a new version of the Welsh form (v4, with corrected typo and illustrations) in:
P:\NEC06214_UK Pollinator Monitoring and Research Partnership\Task 2 Simple survey flower count\Task 2 documents\Welsh versions Survey pack and poster

**Comment by kitenetter** [comment]
@CCarvell where we are editing the FIT Count documents, and will therefore need some translation help, should I send those to Elen or do you want them to go to the translators who worked on them before?

**Comment by CCarvell** [comment]
We have not been back to the original translator who did the FIT Count materials that were translated using funding from National Botanic Garden of Wales. 
But we still have the editable versions in Welsh, hence this is a fairly small job, is that right?
If so, it would be great if Elen could add these to her list - can we get a quick response on whether this will be possible? 
I think we would share the edited versions with her by email, it's not a Transifex job. She can still include this in her overall hours to invoice for the website work.

**Comment by kitenetter** [comment]
Thanks @CCarvell - that sounds like the best approach to me, will liaise with Elen.
