### ISSUE TITLE
New web page: FIT Count app

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#64]
I've realised that we need a page on the website to inform people about the app. A page is set up here:
https://test-ceh-poms.pantheonsite.io/fit-count-app

@CCarvell to check and sign off
@DavidRoy do I need to do anything to add this to the transifex site?

**Comment by DavidRoy** [comment]
@kitenetter shall we have a quick zoom so I can go through the Tranifex process with you?

**Comment by CCarvell** [comment]
@kitenetter I had thought the same! That page looks perfect, thank you, happy to sign off.
Can we also assume that we will add a very simple News section to the current UKCEH PoMS webpage with the links to the app once it has launched end of April, and before the new website is out?

**Comment by kitenetter** [comment]
@CCarvell yes, we can continue to update the UKCEH page until the new site is available.
