### ISSUE TITLE
Holding page for PoMS website address

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#69]
The FIT Count app will launch before the new PoMS website, and the app contains URL links to http://ukpoms.org.uk

Are we able to set up a holding page so that anyone who goes to a link for http://ukpoms.org.uk can see a page that says "Website coming soon! For now please visit the PoMS pages on the [UKCEH website](https://www.ceh.ac.uk/our-science/projects/pollinator-monitoring)."

Preferably showing the PoMS logo and using the colours from the PoMS test website if possible.

I think that is preferable to having an automatic redirect to UKCEH.

**Comment by BirenRathod** [comment]
@kitenetter For that I need to make POMS test site in live env. Live env is same as test env but with active URL. I can add above message, so outside world will see this message and we internal people can still able to work on it.
For live env, how far are we of making changes on test site?

**Comment by kitenetter** [comment]
Sorry @BirenRathod, I'm not sure what you mean, Is it possible to set up the new URL without exposing the site itself? If not, would it be better to redirect to the [existing UKCEH page](https://www.ceh.ac.uk/our-science/projects/pollinator-monitoring)?

**Comment by BirenRathod** [comment]
@kitenetter In any of those things, we need to put site first to live. it will still be restricted for outside world to expose until the final date of release.

**Comment by BirenRathod** [comment]
@kitenetter One advantage of making site live is to avoid last minute waiting of URL propagation, so worth making site live now instead of waiting till last minute.

**Comment by kitenetter** [comment]
@BirenRathod the app is going live this week so we need to ensure that http://ukpoms.org.uk/ is available.

When you say that we need to make the site live, does that mean that anyone will be able to see the site if they go to the link?

Or can we make the site live but also set up a redirect so that people are sent to https://www.ceh.ac.uk/our-science/projects/pollinator-monitoring for now, and then we can switch back to the PoMS site when that is ready to launch next month?

If we can set up a redirect then please can we go ahead and do that.

**Comment by BirenRathod** [comment]
@kitenetter We can make site live and setup a redirect. After making site live, we can restrict to access by anybody until site goes live.

**Comment by BirenRathod** [comment]
@kitenetter Sorry until the release date.

**Comment by kitenetter** [comment]
That's great, thanks @BirenRathod

**Comment by BirenRathod** [comment]
@kitenetter So can I go ahead and make test site into live or ? are we still waiting something to finish yet?

**Comment by kitenetter** [comment]
The test site is still under development and will change over the coming weeks but as long as the redirect is in place that should be okay shouldn't it? And we do need to get this set up now the app has gone live.

@andrewvanbreda let us know if you have any concerns about this.

**Comment by andrewvanbreda** [comment]
@kitenetter @BirenRathod 
The test site is not ready yet.

Are you able to clarify what you mean by redirect in this particular case, as I don't understand what is redirecting where?

From my point of view, ideally I want to be able to complete the test site and then be able to move that configuration onto live without manual setup.
So you can do whatever you like as long as I am able to do that.

Let me know your thoughts if that isn't possible as I will need to allow some extra time for site setup.

**Comment by kitenetter** [comment]
The issue we have is that the FIT Count app has now gone live. The app contains links to http://ukpoms.org.uk/ but if you go to that page you get an error message. Ideally, if people try to go to http://ukpoms.org.uk/ we want them to end up on https://www.ceh.ac.uk/our-science/projects/pollinator-monitoring

I'm afraid I don't understand enough about the relationship between the test site and the live site to know what the implications are.

**Comment by BirenRathod** [comment]
@andrewvanbreda & @kitenetter 
Basically, I need to make site live using ukbms.org.uk. Same like other websites the only difference is, this website won't be available to access by outside world. And when somebody access site from app they will see coming soon message including the redirect link with it on live site until the site is ready to release.

**Comment by andrewvanbreda** [comment]
@BirenRathod @kitenetter 
OK, I think just do whatever you need to do, and I will work around it as needed.

**Comment by BirenRathod** [comment]
@andrewvanbreda The option to update live from test what ever you make changes on test site is still there. 
@kitenetter & @andrewvanbreda So, I'm starting process about 11is, is that ok?

**Comment by DavidRoy** [comment]
@BirenRathod the live site url is http://ukpoms.org.uk/ 
not ukbms.org.uk - a typo in your comment above?

**Comment by BirenRathod** [comment]
@DavidRoy yes, you are right. missing typo as I'm working ukbms site at the same time too.

**Comment by BirenRathod** [comment]
Thanks @andrewvanbreda & @kitenetter.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Yes 11 is fine. Should I make sure I am not touching the test site during this time?

**Comment by BirenRathod** [comment]
@andrewvanbreda yes, please.

**Comment by BirenRathod** [comment]
@andrewvanbreda & @kitenetter I have now initialized the live env, so you can now carry on working on test site.

**Comment by BirenRathod** [comment]
@kitenetter this is how it will be once the URL (ukpoms.org.uk) been activated. Check below link.
https://live-ceh-poms.pantheonsite.io/

**Comment by kitenetter** [comment]
Thanks @BirenRathod 

Instead of these two lines:
- Coming soon
- Website coming soon!

I think we only need:
- Website coming soon!

It's a bit hard to read the text on top of the image, especially for the link to UKCEH, can we put it into a semi-transparent box to make the text stand out more? Or use a different image?

**Comment by BirenRathod** [comment]
@kitenetter I removed the coming soon text. Also, I changed the text color but link is still hidden under the background image. Do you have another which we could use for it?

**Comment by kitenetter** [comment]
Does this work - there is a dark area at the top of the image that might be okay for white text?:

![Bombus pratorum - Great Kimble-002_cropped](https://user-images.githubusercontent.com/16039111/116236881-7c0aad80-a757-11eb-84ba-580fbb0edf92.JPG)

**Comment by BirenRathod** [comment]
@kitenetter I changed the text color and made underline should work. Also, I uploaded your image as background but logo is hidden now. If you satisfy then we can keep it like that.

**Comment by kitenetter** [comment]
Text is fine, can you use this white-out logo please:

[PoMS_Logo_WithStrap_WhiteOut.zip](https://github.com/BiologicalRecordsCentre/PoMS/files/6384548/PoMS_Logo_WithStrap_WhiteOut.zip)

**Comment by BirenRathod** [comment]
@kitenetter I don't have a choice of using this logo. I can only use the logo which the website is currently using it. If I change that it will then change on coming soon page. Do you want me to do that?

**Comment by kitenetter** [comment]
Okay, let's have one more try! Does this work - use the photo below, and keep the black logo, and change the text to black, and maybe use the PoMS purple colour to highlight the UKCEH weblink?

![Thymelicus sylvestris - Bushy Park-004](https://user-images.githubusercontent.com/16039111/116254780-8c2b8880-a769-11eb-9589-dfdf358b4393.JPG)

**Comment by BirenRathod** [comment]
@kitenetter I have uploaded new images. Have a look first and let me know if you still need to change anything.

**Comment by kitenetter** [comment]
I think that's fine Biren, let's go with that.
