### ISSUE TITLE
Welsh page URLs

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#70]
For the FIT Count website we decided to keep the URLs in English and add "cy" to the pathway for the Welsh pages.

At the moment, on the PoMS website we are using Welsh URLs, e.g. the FAQ page is currently showing as:
https://test-ceh-poms.pantheonsite.io/cy/cwestiynaucyffredin

Do you want me to change this so that it becomes:
https://test-ceh-poms.pantheonsite.io/cy/faqs

to match the English:
https://test-ceh-poms.pantheonsite.io/faqs

**Comment by andrewvanbreda** [comment]
@kitenetter 
Hi Martin.
From my point of view, I have no problem you changing URLs. It might break one or two links, but we will go through the site clicking on all the page links before go live anyway and these would be easy corrections.
Minor issue.

Also all the pages which aren't anything to do with Indicia I am not worried about anyway, you can do what you like with them.

**Comment by kitenetter** [comment]
Okay, I'm going to use the 'cy' pattern, e.g.:
https://test-ceh-poms.pantheonsite.io/cy/faqs

For consistency with what was agree [here](https://github.com/NERC-CEH/fit-count-app/issues/60#issuecomment-825207795).

Closing.
