### ISSUE TITLE
Images on Welsh pages

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#71]
When I bring in a translated page onto the PoMS website, it loses the images that are shown on the English pages. Is there any way of automatically copying the images over from the English to the Welsh or do I have to edit each one individually?

**Comment by kitenetter** [comment]
@DavidRoy 
If I download the translations direct from Transifex (rather than importing them via Drupal) it retains the images and most of the formatting. Is there any reason why I shouldn't do that?

If I do do that, should I also complete the import via Drupal so that all the jobs get marked as finished, or is it okay to do this independently of the Drupal import system?

**Comment by andrewvanbreda** [comment]
@kitenetter 
Hi Martin, 
Sorry I thought I had replied to this thread. 
What happens is on the website is there is initially there is an English page only, then at the point you tell system to create the Welsh version, that becomes a carbon copy of English one which can then be edited independently.
So if you have images which have been edited into the English version, it should be possible to copy the entire configuration from the English version into the Welsh at once (i.e. all images), although doing this would then require editing of the text into Welsh.
Do you have URL of particular page with problem you have to I can look?

**Comment by kitenetter** [comment]
Hi @andrewvanbreda I think I've sorted this out - transifex seems to be a bit erratic it how it handles, or mostly doesn't handle, images, but I've found workarounds so there isn't a problem any more. Closing.

P.S. sent you an email about a possible catch-up meeting tomorrow

**Comment by andrewvanbreda** [comment]
@kitenetter 
Yes I replied to that email, can you let me know if you didn't a reply.
Thanks

**Comment by kitenetter** [comment]
Hi @andrewvanbreda - I've just found several of your emails in my junk folder, apologies! Will try to persuade outlook that you are a legitimate operation :)

**Comment by andrewvanbreda** [comment]
@kitenetter 
Oh right, was wondering why I didn't get any replies recently about project (not just you). I just assumed everyone was mega busy.
If you just let me know your thoughts on anything (that is still relevant) via email when you get chance thanks.
