### ISSUE TITLE
A1.3 Map display of 75 x 1 km square survey sites for the 1km square pan trap survey

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/PoMS#74]
Coded a colour coded map, with optional grid.
Awaiting placement onto site

**Comment by andrewvanbreda** [comment]
Note code be used for any surveys you wanted, doesn't have to be pan-trap

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Whenever you get a second, can you pull the following report onto live. Not urgent. Thanks as always.
/projects/PoMS/squares_summary_mappable.xml

**Comment by BirenRathod** [comment]
@andrewvanbreda I have pulled that report now on live.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Great thanks. Will take a look shortly

**Comment by andrewvanbreda** [comment]
Closing as this is covered by #83
