### ISSUE TITLE
A1.4 Map display of 1 km squares with summary data from previous years 

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/PoMS#75]
A grid is coded, map in progress

**Comment by andrewvanbreda** [comment]
@kitenetter 
Didn't we decide this page didn't need a map? or was that another page?

The specification says this
"A1.4 Map display of 1 km squares with summary data from previous years 
This would allow logged-in users to click on a 1km square and see some summary information based on data from years prior to the current one. Depending on what it is possible to do, this summary could include:
•	List of bee and hoverfly species (plus total number of species in each year?)
•	List of flower species from the pan-trap surveys
•	Number of FIT Counts carried out, and average insect number per count?
•	Habitat types recorded in square"

I suppose the problem is how to display the grid.
Am not sure how best to do with.
If each row was a Square/Year combination (every year from 2017), I guess there would be rows with zeroes in.

So grid rows would be a bit like
NC0429 near Rienachait, 2017, List of bee and hoverfly species,  etc etc etc other data columns
NC0429 near Rienachait, 2018, List of bee and hoverfly species,  etc etc etc other data columns
NC0429 near Rienachait, 2019, List of bee and hoverfly species,  etc etc etc other data columns
NC0429 near Rienachait, 2020, List of bee and hoverfly species,  etc etc etc other data columns
NC0429 near Rienachait, 2021, List of bee and hoverfly species,  etc etc etc other data columns
NC2313 near Ledbeg, 2017, List of bee and hoverfly species,  etc etc etc other data columns
NC2313 near Ledbeg, 2018, List of bee and hoverfly species,  etc etc etc other data columns
NC2313 near Ledbeg, 2019, List of bee and hoverfly species,  etc etc etc other data columns
NC2313 near Ledbeg, 2020, List of bee and hoverfly species,  etc etc etc other data columns
NC2313 near Ledbeg, 2021, List of bee and hoverfly species,  etc etc etc other data columns

The problem here though is I am not sure how someone might request data for say 2018 & 2019 at same time. Thoughts?

**Comment by kitenetter** [comment]
@andrewvanbreda I'm finding it hard to think through how this relates to the data entry reports and forms for the 1 km square surveys. This A1.4 page is much less of an immediate priority compared to getting the 1 km data entry forms working.

The main purpose of A1.4 is to enable our 1 km square volunteers to gain access to the species data that is added after they have sent in their samples. So I *think* that what we mainly talking about is a (straightforward?) occurrences report, although this is probably complicated by the fact that each 1 km sample ends up with three sets of occurrences (flower counts by the volunteers, insect group counts by UKCEH staff, and insect species identification by taxonomists).

Maybe a 'normal' report page showing a map and a grid of all occurrences would work, with a 'view' button for each occurrence that will open up a single page view of the sample with all its related occurrences?

However, I think that this type of single page view will be an additional development requirement?

**Comment by kitenetter** [comment]
@andrewvanbreda I think you can ignore the previous comment, I wasn't thinking it through properly. If we just use the standard occurrences we will be exposing the individual pan-trap details, which we don't want to do.

So we do need a summarised report that lists the species for each 1 km square in each year.

Ideally the report should show:
- Square name
- 1 km grid ref
- Year being reported
- How many visits (samples) that year 
- List of bee species recorded
- List of hoverfly species recorded
- Maybe the list of flowers recorded (but this is a lower priority than the bees/hoverflies

I don't think a map is necessary for this page - we need a way to allow people to select the 1 km square they are interested in but that could be done from the square name or grid ref.

Here's an example of the sort of report we have generated in previous years - we don't have to replicate this exactly but it may give a better idea of what sort of feedback we're trying to provide:

[SP1430.pdf](https://github.com/BiologicalRecordsCentre/PoMS/files/6464406/SP1430.pdf)

**Comment by andrewvanbreda** [comment]
@kitenetter OK, I think what you might be talking about a freeform report here rather than the grid I expected.
Will chat to you sometime over video about this. Prob not in today's meeting though, we can have a specific chat sometime about it.

**Comment by andrewvanbreda** [comment]
After discussion with Martin, this needs to be a Squares list drop-down driving a freeform report after page refresh.

**Comment by kitenetter** [comment]
As far as I recall we did not proceed with this, and it has not been raised since as a requirement. Closing.

**Comment by andrewvanbreda** [comment]
Hi @kitenetter 
This was originally part of the original fixed price work but I think there was flexibility and alterations to the other requirements that took up time.
It was still officially on my task list, but again it was another issue which was was always behind other things in the priority list, and would have likely remained so.
