### ISSUE TITLE
Finish configuration of registration options and fields

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/PoMS#8]
Finish configuration of registration options and fields.

AVB extra thought: does the Indicia Easy Login code used in NPMS need a Drupal 8 conversion?

**Comment by BirenRathod** [comment]
@andrewvanbreda 
There is already developed code in Drupal 8. you will find that here -> https://github.com/Indicia-Team/drupal-8-modules-indicia_features

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Yes it is, but that isn't actually quite what I meant by the issue I have raised (maybe I need to re-word the issue)

The Warehouse syncing code actually had a lot of bugs in it which I fixed for NPMS.
I need to make sure those bug fixes are present in the Drupal 8 version as actually the syncing didn't work well at all without them.

Sorry for the confusion. Thanks for the attempt to help regarding this anyway.

**Comment by BirenRathod** [comment]
@andrewvanbreda The easy_login module works slightly different way, then drupal 7 one, so you need to check first and then make a changes according to. Of course your code specific to NPMS, still required to implement as per Drupal 8 version.

**Comment by andrewvanbreda** [comment]
@BirenRathod That is fine, I will test it and only code if it isn't working

AVB note to myself: Need to add "'Where did you hear about this survey?" registration field.

@DavidRoy
I have enabled the test site to allow users to register using registration email.
You may wish to think of wording you may want to use for a custom registration email text.
Also can you consider if you want the "Where did you hear about this survey?" registration field to be free text or series of option. Cheers

**Comment by andrewvanbreda** [comment]
Seems to be covered by a newer issue #38
So closing this
