### ISSUE TITLE
1 km FIT Count data entry: 1km square look-up

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#80]
The autocomplete look-up for the list of 1km squares produces results very quickly if you type in the first letter of the grid ref, but if you go on to type a second letter the look-up hangs.

**Comment by kitenetter** [comment]
The chosen 1km square is not recognised and the form cannot be saved.

(Apologies if I'm picking up on things that are still under development.)

**Comment by andrewvanbreda** [comment]
@kitenetter 
OK thanks. These forms have not been tested seriously yet as there are unlikely to be things that are hard to fix on the forms so rest of project taken priority. So your notes are useful.

**Comment by andrewvanbreda** [comment]
@kitenetter 
Actually just to note, anything available in the menus is available for testing.
The stuff that is completely under development and shouldn't be touched yet is hidden from the menu

**Comment by andrewvanbreda** [comment]
@kitenetter 
Ok have looked at this, I think this form is not loading its javascript at all at the moment.
So a lot of things will break.
Bit odd as it is essentially the same form as iRecord, think there is likely a general misconfiguration on the site in someway.
For now don't carry out any further testing on the data entry forms as it will be a waste of time.

**Comment by andrewvanbreda** [comment]
@kitenetter 
All mentioned problems with this page should be fixed now (including help from John with he autocomplete).
I have also fixed the save and seen this working.

**Comment by andrewvanbreda** [comment]
@kitenetter 
Data entry testing can now continue on all pages available in menu

**Comment by andrewvanbreda** [comment]
Closing this as original issue was fixed
