### ISSUE TITLE
1 km FIT Count data entry: 1km square link to map

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#81]
When a 1 km square is chosen from the autocomplete lookup, the map should automatically zoom in to that 1 km square, so that users can then add a precise location within the square (as currently happens on the equivalent iRecord form).

Nice-to-have if possible: disallow entry of grid ref outside the chosen 1 km square.

**Comment by andrewvanbreda** [comment]
@kitenetter 
Hi Martin
Fixed yesterday. Please close if happy.
The disallow grid reference is outside the scope of the current budget, but feel free to raise it separately in the future.
