### ISSUE TITLE
Footer translation capability

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/PoMS#85]
@kitenetter 
I have now made some changes to the configuration of the site, that should allow Welsh translation for the footer.
You should be able to get at the Welsh translation page for the footer here

https://test-ceh-poms.pantheonsite.io/cy/block/1

**Comment by kitenetter** [comment]
I think this is now working okay, although I seem to have lost the formatting for the Privacy Notice in Welsh. Will sort that out. Closing.
