### ISSUE TITLE
Translation of enter results page

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#87]
@andrewvanbreda I just tried to import the Welsh translation of the enter results page, and this appears to have gone horribly wrong in the resulting pages for both English and Welsh:
https://test-ceh-poms.pantheonsite.io/enter-fit-count
https://test-ceh-poms.pantheonsite.io/cy/cyflwyno-cyfrif-fit

The Welsh page doesn't seem to have created any of the Indicia content.

Apologies if I've done something stupid. Let me know what we need to do to retrieve things and get a translated page working.

**Comment by andrewvanbreda** [comment]
@kitenetter 
Hi Martin,
The Indicia configuration of the Welsh translation site of this page has been wiped. It should be the same as the English version, so I will try and reinstate it now. Shouldn't take long, so will get back to you in 10 mins or so will a result

**Comment by andrewvanbreda** [comment]
@kitenetter 
I believe I have corrected the page problems, although I don't think any translations would have imported. Perhaps a quick chat tomorrow morning about what you are attempting to do so I can advise?

**Comment by kitenetter** [comment]
Thanks @andrewvanbreda 

I'm confused about whether transifex is supposed to be able to transalte the Indicia pages or not, and if it can't what we have to do instead, so a chat would be helpful. Will send a calendar booking for 10am.

@DavidRoy do you have any experience of using transifex to translate Indicia data entry and/or reporting pages?

**Comment by andrewvanbreda** [comment]
OK, I don't know about transifex. Indicia does use Drupal's translation system however it may not for Warehouse attributes.
Worst comes to worst, as long as you have a readable list of what translations were made, I can enter them manually into Warehouse.
I will experiment in the morning.
The translation system is quite complex, but there should always be a manual solution available to any problems we experience.
Am a bit confused about translations being imported onto a specific page, but you can explain that in the meeting.

**Comment by kitenetter** [comment]
Yes, I think we have the necessary words translated, and I can extract them manually from transifex, so we should be able to find a workaround.

**Comment by DavidRoy** [comment]
@kitenetter - in theory, yes, they are sent as individual strings from the page.  Using content type = Locale

As an example. on the page: https://test-ceh-poms.pantheonsite.io/enter-fit-count
you need to send individual strings such as 'Date of FIT Count:'

However, I'm a bit confused why the strings are not appearing in the list of translatable terms:
https://test-ceh-poms.pantheonsite.io/admin/config/regional/translate

which is defined by the elements of the site that is available for translation:
https://test-ceh-poms.pantheonsite.io/admin/config/regional/content-language

please ask John if we can't get this working

**Comment by kitenetter** [comment]
@DavidRoy in that case my initial error was in sending the whole page to be translated, rather than the individual strings. Is it okay to find a workaround solution by manually transferring the page translation back onto the website, or do I need to go back to square one and work out how to send the strings (which I would prefer not to do because it will take longer)?

Behind that is a more general question that I am struggling with: how important is it to do everything via transifex, e.g. for future-proofing and to ensure that all jobs are marked as complete? E.g. if I ask Elen via email to translate a few words that I then put into the website manually does that mess things up?

**Comment by DavidRoy** [comment]
@kitenetter it’s fine to take whatever approach gets the job done for ukpoms although I have got an eye on the wider requirement for translation

**Comment by kitenetter** [comment]
@andrewvanbreda here are the translations of the various labels and help text etc. for the "Enter results" page:

[PoMS website Indicia page translations_Enter results.docx](https://github.com/BiologicalRecordsCentre/PoMS/files/6460262/PoMS.website.Indicia.page.translations_Enter.results.docx)

**Comment by kitenetter** [comment]
Here is the final set of translated terms for this page:

[PoMS website Indicia page translations_Enter results_additions.docx](https://github.com/BiologicalRecordsCentre/PoMS/files/6478069/PoMS.website.Indicia.page.translations_Enter.results_additions.docx)

**Comment by andrewvanbreda** [comment]
@kitenetter 
This final set now done, although not completed previous set yet.

**Comment by andrewvanbreda** [comment]
@kitenetter 
Have imported these. We will just have to keep our eyes open for any problems as I won't be able to go through every string to make sure it translated correctly.
I am not sure yet, but it may be necessary to remove quotes out of the strings, as they seem to be break pages even when escaped.
As there is indication here that some strings are for logged out users only, but hadn't realised this was a requirement, so will have to leave that for now, as it would need code that is outside spec. Will try to do something if budget is left over.

**Comment by andrewvanbreda** [comment]
@kitenetter 
The quote problem can be fixed by adding backslashes in front of quotes in the translations. I have tried to do this where I can
e.g.
Os ydych chi wedi cofrestru gyda\'r wefan, mewngofnodwch er mwyn i\'r Cyfrif hwn ymddangos yn eich rhestr \"Fy Nghofnodion\".

This should obviously be invisible on screen, however this does not always seem to happen and the backslash in printing on screen. I do not know why this is though. If you see backslashes literally on screen, then either remove them from translation here or let me know and I will do it.
https://test-ceh-poms.pantheonsite.io/admin/config/regional/translate

**Comment by kitenetter** [comment]
@andrewvanbreda 
The mention of "logged-out user" was just to indicate the attributes that are only relevant if the user is logged out, see: https://github.com/BiologicalRecordsCentre/PoMS/issues/10#issuecomment-797530997

That was intended to replicate the way the current iRecord form works for logged-out users.

If I try to enter a record when logged out, using the form as it currently stands, I get an error message:

> The data could not be saved.
> Validation errors occurred when this form was submitted to the server. The form configuration may be incorrect as it appears the controls associated with these messages are missing from the form.<ul><li>Please specify a value for the Email.<br/>&nbsp;&nbsp; (related to attribute [smpAttr:878])</li></ul>

**Comment by andrewvanbreda** [comment]
@kitenetter 
Yes am aware of this one (actually there was originally a second attribute it warn about also that was fixed), the problems are all linked. The system as not showing a particular kind of attribute.
I think actually once this is fixed, the profile fields for unregistered users will show (First name, surname, Email). Also I think the instruction text will work also.
So this is all one problem.

**Comment by andrewvanbreda** [comment]
@kitenetter 
All this was fixed before go live, however I don't think there was any translation provided for the profile fields? (First name, Surname etc)

https://ukpoms.org.uk/cy/enter-fit-count

**Comment by andrewvanbreda** [comment]
Also lacking translation for
Add images
Drop files here...

on the same page

**Comment by andrewvanbreda** [comment]
Note First Name, Surname label translations were added as part of another issue.

Added translation for the yellow "This FIT Count is being submitted to the UK PoMS website......." section which had been left out (possibly because it is only seen when no logged in, so perhaps missed in testing)

I have removed the following helptext in Welsh version as currently it is untranslated and not really that helpful, so better without untranslated text.
- "Please provide your first name"
- "Please provide your surname"  

The following remain untranslated
- Personal details
- Email
- Please provide your email. This will only be used to contact you if we require further information to verify the record.
- Drop files here...
- Add images
The spatial reference system names are also in English, but perhaps that is just naming standard and maybe doesn't need translation.
- Please enter a value for this field
- Click here

**Comment by kitenetter** [comment]
As far as I can see this is all resolved on the live site with the exception of the words "Personal details" for logged out users. This needs to be picked up as part of a wider review of the Welsh pages, which will be added as a separate issue. Closing this one.
