### ISSUE TITLE
Translation of Map of FIT Counts

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#90]
Some labels have not yet been translated - I will follow that up with Elen.

[PoMS website Indicia page translations_Map of FIT Counts.docx](https://github.com/BiologicalRecordsCentre/PoMS/files/6460368/PoMS.website.Indicia.page.translations_Map.of.FIT.Counts.docx)

**Comment by andrewvanbreda** [comment]
@kitenetter
 Have done the ones that are there.

The Welsh "Main text" doesn't have the Fit Count link in it, I notice that page doesn't have a Welsh translation at the moment, so I left that for now.

**Comment by kitenetter** [comment]
@andrewvanbreda as you may have seen I've been trying to tidy up the menu headings and the URL aliases. I don't know why the FIT Count page had vanished in its Welsh form but I have reinstated it. It had been done before, but I guess this is another transifex quirk that I don't understand. Anyway, it is back again now:
- English: https://test-ceh-poms.pantheonsite.io/fit-counts
- Welsh: https://test-ceh-poms.pantheonsite.io/cy/fit-counts

I have added the link to the "Main text" part of the Map page.

**Comment by andrewvanbreda** [comment]
@kitenetter 
Ok thanks, no problem

**Comment by kitenetter** [comment]
Here is the final set of translated terms for this page:

[PoMS website Indicia page translations_Map of FIT Counts_additions.docx](https://github.com/BiologicalRecordsCentre/PoMS/files/6478065/PoMS.website.Indicia.page.translations_Map.of.FIT.Counts_additions.docx)

**Comment by andrewvanbreda** [comment]
@kitenetter 
Done those, although am not sure I have been given any translation for what is on the grid

**Comment by kitenetter** [comment]
I haven't asked for a translation of the grid headings because they were not finalised before - I think we will have to live with them being in English for now.

**Comment by andrewvanbreda** [comment]
Closing this one now as both files supplied here done
