### ISSUE TITLE
Translation of My results

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#91]
I have added the translations for the title and intro text box. The labels and help text, which are the same as for Map of FIT Counts (#90), are not yet translated.

**Comment by kitenetter** [comment]
Here is the final set of translated terms for this page:

[PoMS website Indicia page translations_My results_additions.docx](https://github.com/BiologicalRecordsCentre/PoMS/files/6478060/PoMS.website.Indicia.page.translations_My.results_additions.docx)

**Comment by andrewvanbreda** [comment]
@kitenetter Have done these now and can see them on the screen.
I will close this issue as we need to get closing them, re-open needed.
