### ISSUE TITLE
How to translate sub-menu item for "Latest news"

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#92]
Under "News and contacts" we have a sub-menu item "Latest news".

For the Welsh version of the site, this should say "Newyddion diweddaraf".

I can't work out how to apply a Welsh translation to this item, which is generated from a View rather than being a standard sub-menu item.

If this isn't straightforward it can be ignored, since we are not going to be translating the actual news items into Welsh in the short-term, but if it is easy to do it could be good to apply the Welsh name in the menu.

**Comment by andrewvanbreda** [comment]
Hi @kitenetter 

I think this view needs a translation which can be added here.
https://test-ceh-poms.pantheonsite.io/admin/structure/views/view/news/translate

**Comment by kitenetter** [comment]
Thanks @andrewvanbreda - sorted and closing.
