### ISSUE TITLE
Data download via polygon select

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#93]
We already have the ability for users to download their own data, see #33 

We also wish to enable certain users to download data from others for an area of their choice, specified by a polygon drawn on the map (A1.5 in the specifications).

This needs to be a linked to a new website role: users wishing to download via a polygon will need to apply to PoMS to be given that role.

The download should only include data from the current year.

The download should only include data from the public FIT Counts (both those added via the website and via the app).

The csv file output should be identical to the output already in place for the user's own data, EXCEPT THAT it should only provide the blurred 1 km square geolocation, not the precise grid reference.

This is not essential for the launch on 20 May but it would be good to confirm whether it is possible to develop later in the year, so that we can reassure the other projects who wish to be able to download data in this way.

**Comment by andrewvanbreda** [comment]
@kitenetter 
Yes ok, think this can be done just be creating a new duplicate download page with map attached to a new full. This shouldn't be difficult.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Hi Biren,
Can you pull this PoMS report whenever you get a chance, not in use yet so it is safe to do so. Thanks

data_download_in_detail_with_blur_lingual.xml

**Comment by BirenRathod** [comment]
@andrewvanbreda I have now pulled that report.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Hi Biren,
I have made a couple of changes. Could you pull that report whenever you get a chance please.

**Comment by BirenRathod** [comment]
@andrewvanbreda I have pulled that report now.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
As always, thanks for the assitance

**Comment by andrewvanbreda** [comment]
@kitenetter 
Something like this Martin?
https://ukpoms.org.uk/data-download
(note I am aware of an issue on this screen where using the balloon tool to click does not make the grid react to the map click. Will fix that. Note the polygon tool does work though)

**Comment by kitenetter** [comment]
**Minor problem:**
I can add a polygon and use this to filter the grid. If I then "Clear the edit layer" using the map control, the grid refreshes to show all data, but the map display does not refresh, and I have to refresh the whole page to go back to showing all the records.

**Additional requests:**
1. The download page appears to be filtering so that it only includes samples added direct to the website. We would like to include samples added via the app as well.

- @CCarvell do you think we should enable members of the public to download FIT Count samples from the 1 km square surveys, alongside public and app FIT Counts?

2. Can the filters for year and survey be added to the page (i.e. the same as on the public Map of FIT Counts page?

**Comment by andrewvanbreda** [comment]
@kitenetter 
1.
There was a mistake in the page configuration that stopped app records returning-> Corrected

Added Survey filter, although not this also currently includes 1km. Awaiting response from @CCarvell 

2. Can you confirm, as the original requirement stated current year only, this one would need a report change.

**Comment by kitenetter** [comment]
The need for this functionality has been overtaken by the use of project tags. Closing.
