### ISSUE TITLE
Question: edits to Welsh text

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#95]
@andrewvanbreda 
Some of the Welsh text has got set back to English following the design changes. I will reinstate the Welsh, but I just wanted to double-check that it is okay for me to do that on the test website, and that it will then get carried over to the live site - is that correct?

**Comment by andrewvanbreda** [comment]
@kitenetter 
Yes, changes to test will carry over to live.
Be aware though if what you are noticing is on an Indicia page, it is likely because I am working on it.
I am having to do quite a lot of things to get the system to work with English on some pages Welsh on others.

**Comment by kitenetter** [comment]
Thanks @andrewvanbreda - the changes are on non-Indicia pages I think, plus some of the menu items have lost their Welsh.

Closing.
