### ISSUE TITLE
Welsh text not displaying

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#96]
On the Home page, if I choose the Welsh version, there is some text displaying in English:

![image](https://user-images.githubusercontent.com/16039111/118630665-a683df80-b7c6-11eb-9e00-3c341d40a284.png)

However, if I edit that page, the text appears to be in Welsh:

![image](https://user-images.githubusercontent.com/16039111/118630627-9bc94a80-b7c6-11eb-9f26-b5d9b2753a51.png)

@andrewvanbreda is this an issue for you or should I take this up with the designers?

**Comment by andrewvanbreda** [comment]
@kitenetter 
Think the Welsh translation needs editing here, it currently shows English

https://test-ceh-poms.pantheonsite.io/cy/block/4

**Comment by kitenetter** [comment]
Thanks @andrewvanbreda 
I hadn't realised that the home page was using blocks.

I've now edited the block at the top of the page, but having done so the layout for the rest of the (Welsh) page seems to have gone wrong.

Apologies if I've made this worse.

**Comment by andrewvanbreda** [comment]
@kitenetter 
I didn't know either until I had a sniff around, have seen this kind of thing before so I knew where to sniff.
Give me a few mins to finish something then will have a look

**Comment by andrewvanbreda** [comment]
@kitenetter 
Are you able to send a screenshot, my machine looks ok but it might be cached. Note sure what it should look like.

**Comment by kitenetter** [comment]
English:

![image](https://user-images.githubusercontent.com/16039111/118638671-fc5c8580-b7ce-11eb-8167-c7b314715590.png)

Welsh as it is currently displaing on my machine:

![image](https://user-images.githubusercontent.com/16039111/118638766-15653680-b7cf-11eb-9be8-ce30fcaf8a40.png)

I thought that the two pages looked similar in layout before I edited the block at the top, but I can't be certain of that.

**Comment by andrewvanbreda** [comment]
@kitenetter 
Fraid I have no idea as didn't have anything to do with development of the page, to me though it looks like they were never similar. If that is it gone wrong, then it has gone wrong in a very structured way. Also the images are different to that would result in a different text structure.
The image at the bottom could do with some padding I guess.

**Comment by BirenRathod** [comment]
@kitenetter This page https://test-ceh-poms.pantheonsite.io/cy/hafan requires to update content same as English one.

**Comment by kitenetter** [comment]
@BirenRathod does that mean I have to copy the images etc. from the English page, and then add the translated wording?

**Comment by BirenRathod** [comment]
@kitenetter  I have done that for you. you just need to translate sentences into welsh. Can you do it or Is it done via Transfix?

**Comment by kitenetter** [comment]
Thanks @BirenRathod - that is great, and I can add the Welsh text back in.

**Comment by BirenRathod** [comment]
@kitenetter Can you send me the welsh text of this two -> "News and contacts" & "Administrations", So I can change the menu.

**Comment by BirenRathod** [comment]
@kitenetter No need to do, I have just managed to do it. Just check the text in welsh is ok.

**Comment by kitenetter** [comment]
That's fine, thanks @BirenRathod 
Will get the home page text sorted out later this afternoon.
