### ISSUE TITLE
Image upload not working on data entry form

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/PoMS#97]
Hi @BirenRathod ,

Uploading an image on this page results in this error

"An error occurred uploading the file. Failed to open output stream."

Think you may have fixed this for NPMS in the past?

Cheers.

**Comment by BirenRathod** [comment]
@andrewvanbreda You have introduced the helper_config.php file. It has got this $interim_image_folder value empty. The photo upload stop working after that. 
One solution is disable the $interim_image_folder variable in helper_config.php. 
Second option is If you don't require helper_config.php then please remove it.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
When I did the .gitignore change you previously recommended, I saw the helper_config file already had that option I needed set in it.
So never altered the file at all, so assume it was always there.
I think we need the language option though, so the fix is to disable that variable.
I will do that, thanks for letting me know :)

**Comment by BirenRathod** [comment]
@andrewvanbreda yes please do so. If you check the indicia diagnostic here -> https://test-ceh-poms.pantheonsite.io/admin/config/iform/diagnostics, you will see it is pointing to somewhere else due to empty value.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Thanks Biren for your help with this, forgot about that diagnosis tool as long time since I used it, but that doesn't mean I shouldn't of been.
Fixed
