### ISSUE TITLE
Formatting of Welsh pages

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#98]
This is not critical, but would be nice to fix if we can.

On the English home page there is some formatting associated with the "GET INVOLVED" links:

![image](https://user-images.githubusercontent.com/16039111/118716743-145af600-b81d-11eb-9cd1-4f7a3b5096a2.png)

On the Welsh version of this page the formatting has been lost for the equivalent text: "CYMRYD RHAN".

The links still work okay, but it would be nice to have the formatting as well.

**Comment by kitenetter** [comment]
On this page:
https://test-ceh-poms.pantheonsite.io/cy/about

We have lost the bold purple formatting for parts of the text. See the English equivalent:
https://test-ceh-poms.pantheonsite.io/about

If this is something that I can change please can you let me know what I need to do.

**Comment by kitenetter** [comment]
The formatting of this page:
https://test-ceh-poms.pantheonsite.io/fit-counts

has not been applied to the Welsh version:
https://test-ceh-poms.pantheonsite.io/cy/fit-counts

**Comment by kitenetter** [comment]
The formatting of this page:
https://test-ceh-poms.pantheonsite.io/one-km-square-survey

has not been applied to the Welsh version:
https://test-ceh-poms.pantheonsite.io/cy/one-km-square-survey

**Comment by BirenRathod** [comment]
@kitenetter All formatting done.  Please check everything is ok. 
My only concern is this page -> https://test-ceh-poms.pantheonsite.io/cy/fit-counts . On this page not all contents are same as English one, so I have amended page accordingly.

**Comment by kitenetter** [comment]
Thanks @BirenRathod 
The page /cy/fit-counts should have one line of additional text that is not needed on the English page. I will reinstate that.

Closing.
