### ISSUE TITLE
Adding images

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#99]
I've just re-inserted the image at the top of this page:
https://test-ceh-poms.pantheonsite.io/fit-counts

There are no buffers around it, and I can't see a way of adding buffers.

Can I control this? If not please can you set a buffer.

Or is there a better way of adding images under the new design?

**Comment by BirenRathod** [comment]
@kitenetter What kind of buffers do you need? you can add image via "Add new file" which already available below the text edito.
![image](https://user-images.githubusercontent.com/5941255/118781700-40aa5d00-b885-11eb-8d35-99c9018bc102.png)

**Comment by kitenetter** [comment]
The image was added using "Add new file", but it does not have any border, so the text runs right up to the image:

![image](https://user-images.githubusercontent.com/16039111/118786054-5b7ed080-b889-11eb-8b31-8d4dfbc83e27.png)

It just needs a small border around the image to separate it from the text. I can't see any way of controlling that (it used to be easy on previous versions of Drupal!).

**Comment by BirenRathod** [comment]
@kitenetter It has removed by Julian's theme update. I will add it again.

**Comment by BirenRathod** [comment]
@kitenetter Added border and margin now.

**Comment by kitenetter** [comment]
Thanks - closing.
